--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/6/2021 9:33:54 AM
-- Server version: 5.5.5-10.1.41-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE `web06.test.mf901.pthieu`;

--
-- Drop procedure `Proc_GetCloneEmployeeById`
--
DROP PROCEDURE IF EXISTS Proc_GetCloneEmployeeById;

--
-- Drop procedure `Proc_GetNewEmployeeCode`
--
DROP PROCEDURE IF EXISTS Proc_GetNewEmployeeCode;

--
-- Drop procedure `Proc_GetNewReceiptPaymentCode`
--
DROP PROCEDURE IF EXISTS Proc_GetNewReceiptPaymentCode;

--
-- Drop function `Func_ExtractNumber`
--
DROP FUNCTION IF EXISTS Func_ExtractNumber;

--
-- Drop function `Func_GetNewCodeNumber`
--
DROP FUNCTION IF EXISTS Func_GetNewCodeNumber;

--
-- Drop procedure `Proc_GetReceiptPaymentById`
--
DROP PROCEDURE IF EXISTS Proc_GetReceiptPaymentById;

--
-- Drop procedure `Proc_GetReceiptPaymentFilterPaging`
--
DROP PROCEDURE IF EXISTS Proc_GetReceiptPaymentFilterPaging;

--
-- Drop procedure `Proc_GetReceiptPayments`
--
DROP PROCEDURE IF EXISTS Proc_GetReceiptPayments;

--
-- Drop view `view_receiptpayment`
--
DROP VIEW IF EXISTS view_receiptpayment CASCADE;

--
-- Drop procedure `Proc_DeleteReceiptPaymentById`
--
DROP PROCEDURE IF EXISTS Proc_DeleteReceiptPaymentById;

--
-- Drop procedure `Proc_InsertReceiptPayment`
--
DROP PROCEDURE IF EXISTS Proc_InsertReceiptPayment;

--
-- Drop procedure `Proc_UpdateReceiptPayment`
--
DROP PROCEDURE IF EXISTS Proc_UpdateReceiptPayment;

--
-- Drop table `receiptpayment`
--
DROP TABLE IF EXISTS receiptpayment;

--
-- Drop procedure `Proc_GetEmployeeById`
--
DROP PROCEDURE IF EXISTS Proc_GetEmployeeById;

--
-- Drop procedure `Proc_GetEmployees`
--
DROP PROCEDURE IF EXISTS Proc_GetEmployees;

--
-- Drop procedure `Proc_GetEmployeesFilterPaging`
--
DROP PROCEDURE IF EXISTS Proc_GetEmployeesFilterPaging;

--
-- Drop view `view_employee`
--
DROP VIEW IF EXISTS view_employee CASCADE;

--
-- Drop procedure `Proc_DeleteEmployeeById`
--
DROP PROCEDURE IF EXISTS Proc_DeleteEmployeeById;

--
-- Drop procedure `Proc_InsertEmployee`
--
DROP PROCEDURE IF EXISTS Proc_InsertEmployee;

--
-- Drop procedure `Proc_UpdateEmployee`
--
DROP PROCEDURE IF EXISTS Proc_UpdateEmployee;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop procedure `Proc_DeleteDepartmentById`
--
DROP PROCEDURE IF EXISTS Proc_DeleteDepartmentById;

--
-- Drop procedure `Proc_GetDepartmentById`
--
DROP PROCEDURE IF EXISTS Proc_GetDepartmentById;

--
-- Drop procedure `Proc_GetDepartments`
--
DROP PROCEDURE IF EXISTS Proc_GetDepartments;

--
-- Drop procedure `Proc_InsertDepartment`
--
DROP PROCEDURE IF EXISTS Proc_InsertDepartment;

--
-- Drop procedure `Proc_UpdateDepartment`
--
DROP PROCEDURE IF EXISTS Proc_UpdateDepartment;

--
-- Drop table `department`
--
DROP TABLE IF EXISTS department;

--
-- Set default database
--
USE `web06.test.mf901.pthieu`;

--
-- Create table `department`
--
CREATE TABLE department (
  DepartmentId char(36) NOT NULL COMMENT 'Khóa chính/Id đơn vị',
  DepartmentName varchar(255) NOT NULL COMMENT 'tên đơn vị',
  Description varchar(255) DEFAULT NULL COMMENT 'Mô tả đơn vị',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Tên người tạo',
  CreatedDate datetime DEFAULT NULL COMMENT 'Thời điểm tạo',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Tên người chỉnh sửa cuối',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Thời điểm chỉnh sửa cuối',
  PRIMARY KEY (DepartmentId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Danh sách đơn vị/phòng ban';

DELIMITER $$

--
-- Create procedure `Proc_UpdateDepartment`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_UpdateDepartment (IN DepartmentId char(36), IN DepartmentName varchar(255), IN Description varchar(255), IN ModifiedBy varchar(100))
COMMENT 'Chỉnh sửa thông tin đơn vị/phòng ban'
BEGIN
  UPDATE Department d
  SET d.DepartmentName = DepartmentName,
      d.Description = Description,
      d.ModifiedBy = ModifiedBy,
      d.ModifiedDate = NOW()
  WHERE d.DepartmentId = DepartmentId;
END
$$

--
-- Create procedure `Proc_InsertDepartment`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_InsertDepartment (IN DepartmentId char(36), IN DepartmentName varchar(255), IN Description varchar(255), IN CreatedBy varchar(100))
COMMENT 'Thêm đơn vị/phòng ban mới'
BEGIN
  INSERT INTO Department (DepartmentId, DepartmentName, Description, CreatedBy, CreatedDate)
    VALUES (UUID(), DepartmentName, Description, CreatedBy, NOW());
END
$$

--
-- Create procedure `Proc_GetDepartments`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetDepartments ()
COMMENT 'Lấy danh sách tất cả đơn vị/phòng ban'
BEGIN
  SELECT
    *
  FROM Department d;
END
$$

--
-- Create procedure `Proc_GetDepartmentById`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetDepartmentById (IN DepartmentId varchar(36))
COMMENT 'Lấy thông tin đơn vị/phòng ban theo khóa chính'
BEGIN
  SELECT
    *
  FROM Department d
  WHERE d.DepartmentId = DepartmentId LIMIT 1;
END
$$

--
-- Create procedure `Proc_DeleteDepartmentById`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_DeleteDepartmentById (IN DepartmentId varchar(36))
COMMENT 'Xóa đơn vị/phòng ban theo khóa chính'
BEGIN
  DELETE
    FROM Department
  WHERE Department.DepartmentId = DepartmentId;
END
$$

DELIMITER ;

--
-- Create table `employee`
--
CREATE TABLE employee (
  EmployeeId char(36) NOT NULL COMMENT 'Id nhân viên/Khóa chính',
  EmployeeCode varchar(20) NOT NULL COMMENT 'mã nhân viên',
  EmployeeName varchar(100) NOT NULL COMMENT 'tên nhân viên',
  DateOfBirth date DEFAULT NULL COMMENT 'ngày sinh',
  Gender int(11) DEFAULT NULL COMMENT 'giới tính: 0-nam; 1-nữ; 2-khác',
  DepartmentId char(36) NOT NULL COMMENT 'Id của đơn vị/phòng ban',
  IdentityNumber varchar(25) DEFAULT NULL COMMENT 'Số CMTND/CCCD',
  IdentityDate date DEFAULT NULL COMMENT 'Ngày cấp CMTND/CCCD',
  IdentityPlace varchar(255) DEFAULT NULL COMMENT 'Nơi cấp CMTND/CCCD',
  EmployeePosition varchar(100) DEFAULT NULL COMMENT 'Chức danh',
  Address varchar(255) DEFAULT NULL COMMENT 'Địa chỉ nơi ở',
  BankAccountNumber varchar(25) DEFAULT NULL COMMENT 'Số tài khoản ngân hàng',
  BankName varchar(255) DEFAULT NULL COMMENT 'Tên ngân hàng',
  BankBranchName varchar(255) DEFAULT NULL COMMENT 'Tên chi nhánh ngân hàng',
  BankProvinceName varchar(255) DEFAULT NULL COMMENT 'Tên tỉnh của ngân hàng',
  PhoneNumber varchar(50) DEFAULT NULL COMMENT 'số điện thoại di động',
  TelephoneNumber varchar(50) DEFAULT NULL COMMENT 'số điện thoại cố định',
  Email varchar(100) DEFAULT NULL COMMENT 'Địa chỉ email',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Tên người tạo',
  CreatedDate datetime DEFAULT NULL COMMENT 'Thời điểm tạo',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Tên người chỉnh sửa cuối',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Thời điểm chỉnh sửa cuối',
  PRIMARY KEY (EmployeeId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 655,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Danh sách nhân viên';

--
-- Create index `UK_Employee_EmployeeCode` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX UK_Employee_EmployeeCode (EmployeeCode);

--
-- Create foreign key
--
ALTER TABLE employee
ADD CONSTRAINT FK_Employee_DepartmentId FOREIGN KEY (DepartmentId)
REFERENCES department (DepartmentId) ON DELETE NO ACTION;

DELIMITER $$

--
-- Create procedure `Proc_UpdateEmployee`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_UpdateEmployee (IN EmployeeId char(36), IN EmployeeCode varchar(20), IN EmployeeName varchar(100), IN DateOfBirth date, IN Gender int, IN DepartmentId char(36), IN IdentityNumber varchar(25), IN IdentityDate date, IN IdentityPlace varchar(255), IN EmployeePosition varchar(100), IN Address varchar(255), IN BankAccountNumber varchar(25), IN BankName varchar(255), IN BankBranchName varchar(255), IN BankProvinceName varchar(255), IN PhoneNumber varchar(50), IN TelephoneNumber varchar(50), IN Email varchar(100), IN CreatedBy varchar(100), IN CreatedDate datetime, IN ModifiedBy varchar(100), IN ModifiedDate datetime)
COMMENT 'Chỉnh sửa thông tin nhân viên'
BEGIN
  UPDATE Employee e
  SET e.EmployeeCode = EmployeeCode,
      e.EmployeeName = EmployeeName,
      e.DateOfBirth = DateOfBirth,
      e.Gender = Gender,
      e.DepartmentId = DepartmentId,
      e.IdentityNumber = IdentityNumber,
      e.IdentityDate = IdentityDate,
      e.IdentityPlace = IdentityPlace,
      e.EmployeePosition = EmployeePosition,
      e.Address = Address,
      e.BankAccountNumber = BankAccountNumber,
      e.BankName = BankName,
      e.BankBranchName = BankBranchName,
      e.BankProvinceName = BankProvinceName,
      e.PhoneNumber = PhoneNumber,
      e.TelephoneNumber = TelephoneNumber,
      e.Email = Email,
      e.CreatedBy = CreatedBy,
      e.CreatedDate = CreatedDate,
      e.ModifiedBy = ModifiedBy,
      e.ModifiedDate = NOW()
  WHERE e.EmployeeId = EmployeeId;
END
$$

--
-- Create procedure `Proc_InsertEmployee`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_InsertEmployee (IN EmployeeId char(36), IN EmployeeCode varchar(20), IN EmployeeName varchar(100), IN DateOfBirth date, IN Gender int, IN DepartmentId char(36), IN IdentityNumber varchar(25), IN IdentityDate date, IN IdentityPlace varchar(255), IN EmployeePosition varchar(100), IN Address varchar(255), IN BankAccountNumber varchar(25), IN BankName varchar(255), IN BankBranchName varchar(255), IN BankProvinceName varchar(255), IN PhoneNumber varchar(50), IN TelephoneNumber varchar(50), IN Email varchar(100), IN CreatedBy varchar(100), IN CreatedDate datetime, IN ModifiedBy varchar(100), IN ModifiedDate datetime)
COMMENT 'Thêm nhân viên mới'
BEGIN
  INSERT INTO Employee (EmployeeId,
  EmployeeCode,
  EmployeeName,
  DateOfBirth,
  Gender,
  DepartmentId,
  IdentityNumber,
  IdentityDate,
  IdentityPlace,
  EmployeePosition,
  Address,
  BankAccountNumber,
  BankName,
  BankBranchName,
  BankProvinceName,
  PhoneNumber,
  TelephoneNumber,
  Email,
  CreatedBy,
  CreatedDate,
  ModifiedBy,
  ModifiedDate)
    VALUES (UUID(), EmployeeCode, EmployeeName, DateOfBirth, Gender, DepartmentId, IdentityNumber, IdentityDate, IdentityPlace, EmployeePosition, Address, BankAccountNumber, BankName, BankBranchName, BankProvinceName, PhoneNumber, TelephoneNumber, Email, CreatedBy, NOW(), ModifiedBy, ModifiedDate);
END
$$

--
-- Create procedure `Proc_DeleteEmployeeById`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_DeleteEmployeeById (IN EmployeeId char(36))
COMMENT 'Xóa nhân viên dựa theo khóa chính'
BEGIN
  DELETE
    FROM Employee
  WHERE Employee.EmployeeId = EmployeeId;
END
$$

DELIMITER ;

--
-- Create view `view_employee`
--
CREATE
DEFINER = 'dev'@'%'
VIEW view_employee
AS
SELECT
  `e`.`EmployeeId` AS `EmployeeId`,
  `e`.`EmployeeCode` AS `EmployeeCode`,
  `e`.`EmployeeName` AS `EmployeeName`,
  `e`.`DateOfBirth` AS `DateOfBirth`,
  `e`.`Gender` AS `Gender`,
  `e`.`DepartmentId` AS `DepartmentId`,
  `d`.`DepartmentName` AS `DepartmentName`,
  `e`.`IdentityNumber` AS `IdentityNumber`,
  `e`.`IdentityDate` AS `IdentityDate`,
  `e`.`IdentityPlace` AS `IdentityPlace`,
  `e`.`EmployeePosition` AS `EmployeePosition`,
  `e`.`Address` AS `Address`,
  `e`.`BankAccountNumber` AS `BankAccountNumber`,
  `e`.`BankName` AS `BankName`,
  `e`.`BankBranchName` AS `BankBranchName`,
  `e`.`BankProvinceName` AS `BankProvinceName`,
  `e`.`PhoneNumber` AS `PhoneNumber`,
  `e`.`TelephoneNumber` AS `TelephoneNumber`,
  `e`.`Email` AS `Email`,
  `e`.`CreatedBy` AS `CreatedBy`,
  `e`.`CreatedDate` AS `CreatedDate`,
  `e`.`ModifiedBy` AS `ModifiedBy`,
  `e`.`ModifiedDate` AS `ModifiedDate`
FROM (`employee` `e`
  LEFT JOIN `department` `d`
    ON ((`e`.`DepartmentId` = `d`.`DepartmentId`)));

DELIMITER $$

--
-- Create procedure `Proc_GetEmployeesFilterPaging`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetEmployeesFilterPaging (IN EmployeeFilter varchar(255), IN PageIndex int, IN PageSize int, OUT TotalRecord int, OUT TotalPage int)
COMMENT 'Lấy danh sách nhân viên theo tiêu chí lọc/phân trang'
BEGIN
  SET @EmployeeFilter = (SELECT
      EmployeeFilter);

  IF PageSize > 0 THEN

    SELECT
      e.EmployeeId,
      e.EmployeeCode,
      e.EmployeeName,
      e.DateOfBirth,
      e.Gender,
      e.DepartmentId,
      e.DepartmentName,
      e.IdentityNumber,
      e.IdentityDate,
      e.IdentityPlace,
      e.EmployeePosition,
      e.Address,
      e.BankAccountNumber,
      e.BankName,
      e.BankBranchName,
      e.BankProvinceName,
      e.PhoneNumber,
      e.TelephoneNumber,
      e.Email,
      e.CreatedBy,
      e.CreatedDate,
      e.ModifiedBy,
      e.ModifiedDate
    FROM View_Employee e
    WHERE (
    @EmployeeFilter IS NULL
    OR @EmployeeFilter = ""
    OR (@EmployeeFilter IS NOT NULL
    AND (e.EmployeeCode LIKE CONCAT('%', @EmployeeFilter, '%')
    --     OR e.EmployeeName LIKE BINARY CONCAT('%', @EmployeeFilter, '%')
    OR e.EmployeeName LIKE CONCAT('%', @EmployeeFilter, '%')
    OR e.PhoneNumber LIKE CONCAT('%', @EmployeeFilter, '%')
    OR e.TelephoneNumber LIKE CONCAT('%', @EmployeeFilter, '%')
    )))
    --     AND ((@DepartmentId IS NOT NULL
    --     AND e.DepartmentId = @DepartmentId)
    --     OR @DepartmentId IS NULL)
    ORDER BY e.CreatedDate DESC
    LIMIT PageSize OFFSET PageIndex;

    SET TotalRecord = (SELECT
        COUNT(*)
      FROM View_Employee e
      WHERE (
      @EmployeeFilter IS NULL
      OR @EmployeeFilter = ""
      OR (@EmployeeFilter IS NOT NULL
      AND (e.EmployeeCode LIKE CONCAT('%', @EmployeeFilter, '%')
      --       OR e.EmployeeName LIKE BINARY CONCAT('%', @EmployeeFilter, '%')
      OR e.EmployeeName LIKE CONCAT('%', @EmployeeFilter, '%')
      OR e.PhoneNumber LIKE CONCAT('%', @EmployeeFilter, '%')
      OR e.TelephoneNumber LIKE CONCAT('%', @EmployeeFilter, '%')
      )))
      --       AND ((@DepartmentId IS NOT NULL
      --       AND e.DepartmentId = @DepartmentId)
      --       OR @DepartmentId IS NULL)
      ORDER BY e.CreatedDate DESC);



    /* Tổng số trang */
    SET TotalPage = CEILING(1.0 * TotalRecord / PageSize);
  /*
    SET @NumberRecordLastPage = TotalRecord % PageSize;

    IF @NumberRecordLastPage > 0 THEN
      SET TotalPage = TotalRecord DIV PageSize + 1;
    ELSE
      SET TotalPage = TotalRecord DIV PageSize;
    END IF;
  */
  END IF;
END
$$

--
-- Create procedure `Proc_GetEmployees`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetEmployees ()
COMMENT 'Lấy tất cả danh sách nhân viên'
BEGIN
  SELECT
    *
  FROM View_Employee
  ORDER BY CreatedDate DESC;
END
$$

--
-- Create procedure `Proc_GetEmployeeById`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetEmployeeById (IN EmployeeId char(36))
COMMENT 'Lấy thông tin nhân viên theo khóa chính'
BEGIN
  SELECT
    *
  FROM View_Employee e
  WHERE e.EmployeeId = EmployeeId LIMIT 1;
-- SELECT e.*, d.DepartmentName FROM Employee e LEFT JOIN Department d ON e.DepartmentId = d.DepartmentId WHERE e.EmployeeId = EmployeeId;
END
$$

DELIMITER ;

--
-- Create table `receiptpayment`
--
CREATE TABLE receiptpayment (
  ReceiptPaymentId char(36) NOT NULL COMMENT 'Khóa chính/id phiếu thu chi tiền mặt',
  ReceiptPaymentCode varchar(20) NOT NULL COMMENT 'Mã chứng từ',
  AccountingDate date NOT NULL COMMENT 'Ngày hạch toán',
  RefDate date NOT NULL COMMENT 'Ngày phiếu thu/chi',
  TotalAmount decimal(18, 4) DEFAULT NULL COMMENT 'Tổng tiền',
  Reason varchar(255) DEFAULT NULL COMMENT 'Lý do thu/chi',
  OrganizationUnitId char(36) DEFAULT NULL COMMENT 'ID đối tượng',
  Receiver varchar(100) DEFAULT NULL COMMENT 'Người nhận',
  Address varchar(255) DEFAULT NULL,
  Description varchar(255) DEFAULT NULL COMMENT 'Diễn giải lý do thu/chi',
  EmployeeId char(36) DEFAULT NULL COMMENT 'ID nhân viên',
  RefAttach int(11) DEFAULT NULL COMMENT 'Số lượng chứng từ gốc kèm theo',
  ReceiptPaymentDetail longtext DEFAULT NULL COMMENT 'Chi tiết thu/chi',
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Thời điểm cập nhật cuối',
  ModifiedBy varchar(100) DEFAULT NULL,
  PRIMARY KEY (ReceiptPaymentId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 819,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Thông tin phiếu thu/chi tiền mặt';

--
-- Create index `ReceiptPaymentCode` on table `receiptpayment`
--
ALTER TABLE receiptpayment
ADD UNIQUE INDEX ReceiptPaymentCode (ReceiptPaymentCode);

--
-- Create foreign key
--
ALTER TABLE receiptpayment
ADD CONSTRAINT FK_ReceiptPayment_OrganizationUnitId FOREIGN KEY (OrganizationUnitId)
REFERENCES employee (EmployeeId) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE receiptpayment
ADD CONSTRAINT FK_receiptpayment_EmployeeId FOREIGN KEY (EmployeeId)
REFERENCES employee (EmployeeId) ON DELETE NO ACTION;

DELIMITER $$

--
-- Create procedure `Proc_UpdateReceiptPayment`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_UpdateReceiptPayment (IN ReceiptPaymentId char(36), IN ReceiptPaymentCode varchar(20), IN AccountingDate date, IN RefDate date, IN TotalAmount decimal, IN Reason varchar(255), IN OrganizationUnitId char(36), IN Receiver varchar(255), IN Address varchar(255), IN Description varchar(255), IN EmployeeId varchar(36), IN RefAttach int, IN ReceiptPaymentDetail longtext, IN CreatedDate datetime, IN CreatedBy varchar(100), IN ModifiedDate datetime, IN ModifiedBy varchar(100))
COMMENT 'Chỉnh sửa thông tin phiếu thu/chi tiền mặt'
BEGIN
  UPDATE receiptpayment r
  SET r.ReceiptPaymentCode = ReceiptPaymentCode,
      r.AccountingDate = AccountingDate,
      r.RefDate = RefDate,
      r.TotalAmount = TotalAmount,
      r.Reason = Reason,
      r.OrganizationUnitId = OrganizationUnitId,
      r.Receiver = Receiver,
      r.Address = Address,
      r.Description = Description,
      r.EmployeeId = EmployeeId,
      r.RefAttach = RefAttach,
      r.ReceiptPaymentDetail = ReceiptPaymentDetail,
      r.CreatedBy = CreatedBy,
      r.CreatedDate = CreatedDate,
      r.ModifiedBy = ModifiedBy,
      r.ModifiedDate = NOW()
  WHERE r.ReceiptPaymentId = ReceiptPaymentId;
END
$$

--
-- Create procedure `Proc_InsertReceiptPayment`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_InsertReceiptPayment (IN ReceiptPaymentId char(36), IN ReceiptPaymentCode varchar(20), IN AccountingDate date, IN RefDate date, IN TotalAmount decimal, IN Reason varchar(255), IN OrganizationUnitId char(36), IN Receiver varchar(255), IN Address varchar(255), IN Description varchar(255), IN EmployeeId varchar(36), IN RefAttach int, IN ReceiptPaymentDetail longtext, IN CreatedDate datetime, IN CreatedBy varchar(100), IN ModifiedDate datetime, IN ModifiedBy varchar(100))
COMMENT 'Thêm phiếu thu/chi tiền mặt mới'
BEGIN
  INSERT INTO receiptpayment (ReceiptPaymentId, ReceiptPaymentCode, AccountingDate, RefDate, TotalAmount, Reason, OrganizationUnitId, Receiver, Address, Description, EmployeeId, RefAttach, ReceiptPaymentDetail, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy)
    VALUES (UUID(), ReceiptPaymentCode, AccountingDate, RefDate, TotalAmount, Reason, OrganizationUnitId, Receiver, Address, Description, EmployeeId, RefAttach, ReceiptPaymentDetail, NOW(), CreatedBy, ModifiedDate, ModifiedBy);

END
$$

--
-- Create procedure `Proc_DeleteReceiptPaymentById`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_DeleteReceiptPaymentById (IN ReceiptPaymentId varchar(36))
COMMENT 'Xóa phiếu thu/chi tiền mặt dựa theo khóa chính'
BEGIN
  DELETE
    FROM receiptpayment
  WHERE receiptpayment.ReceiptPaymentId = ReceiptPaymentId;
END
$$

DELIMITER ;

--
-- Create view `view_receiptpayment`
--
CREATE
DEFINER = 'dev'@'%'
VIEW view_receiptpayment
AS
SELECT
  `r`.`ReceiptPaymentId` AS `ReceiptPaymentId`,
  `r`.`ReceiptPaymentCode` AS `ReceiptPaymentCode`,
  `r`.`AccountingDate` AS `AccountingDate`,
  `r`.`RefDate` AS `RefDate`,
  `r`.`TotalAmount` AS `TotalAmount`,
  `r`.`Reason` AS `Reason`,
  `r`.`OrganizationUnitId` AS `OrganizationUnitId`,
  `o`.`EmployeeName` AS `OrganizationUnitName`,
  `r`.`Receiver` AS `Receiver`,
  `r`.`Description` AS `Description`,
  `r`.`EmployeeId` AS `EmployeeId`,
  `e`.`EmployeeName` AS `EmployeeName`,
  `r`.`RefAttach` AS `RefAttach`,
  `r`.`ReceiptPaymentDetail` AS `ReceiptPaymentDetail`,
  `r`.`CreatedDate` AS `CreatedDate`,
  `r`.`CreatedBy` AS `CreatedBy`,
  `r`.`ModifiedDate` AS `ModifiedDate`,
  `r`.`ModifiedBy` AS `ModifiedBy`,
  `r`.`Address` AS `Address`
FROM ((`receiptpayment` `r`
  LEFT JOIN `employee` `o`
    ON ((`r`.`OrganizationUnitId` = `o`.`EmployeeId`)))
  LEFT JOIN `employee` `e`
    ON ((`r`.`EmployeeId` = `e`.`EmployeeId`)));

DELIMITER $$

--
-- Create procedure `Proc_GetReceiptPayments`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetReceiptPayments ()
COMMENT 'Lấy danh sách tất cả phiếu thu/chi tiền mặt'
BEGIN
  SELECT
    *
  FROM view_receiptpayment
  ORDER BY CreatedDate DESC;
END
$$

--
-- Create procedure `Proc_GetReceiptPaymentFilterPaging`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetReceiptPaymentFilterPaging (IN RefFilter varchar(255), IN DateFrom date, IN DateTo date, IN PageIndex int, IN PageSize int, OUT TotalRecord int, OUT TotalPage int, OUT TotalAmount decimal)
COMMENT 'Lấy danh sách chứng từ thu/chi tiền mặt theo tiêu chí lọc/phân trang'
BEGIN
  IF PageSize > 0 THEN
    SELECT
      r.ReceiptPaymentId,
      r.ReceiptPaymentCode,
      r.AccountingDate,
      r.RefDate,
      r.TotalAmount,
      r.Reason,
      r.OrganizationUnitId,
      r.OrganizationUnitName,
      r.Receiver,
      r.Description,
      r.EmployeeId,
      r.EmployeeName,
      r.RefAttach,
      r.ReceiptPaymentDetail,
      r.CreatedDate,
      r.CreatedBy,
      r.ModifiedDate,
      r.ModifiedBy
    FROM view_receiptpayment r
    WHERE (
    RefFilter IS NULL
    OR RefFilter = ""
    OR (RefFilter IS NOT NULL
    AND (
    r.ReceiptPaymentCode LIKE CONCAT('%', RefFilter, '%')
    OR r.Description LIKE CONCAT('%', RefFilter, '%')
    OR r.OrganizationUnitName LIKE CONCAT('%', RefFilter, '%')
    )))
    AND (
    DateFrom IS NULL
    OR DateTo IS NULL
    OR (DateFrom IS NOT NULL
    AND DateTo IS NOT NULL
    AND r.AccountingDate BETWEEN DateFrom AND DateTo))
    ORDER BY r.CreatedDate DESC
    LIMIT PageSize OFFSET PageIndex;

    /* Tổng số bản ghi */
    SELECT
      COUNT(*),
      SUM(r.TotalAmount) INTO TotalRecord, TotalAmount
    FROM view_receiptpayment r
    WHERE (
    RefFilter IS NULL
    OR RefFilter = ""
    OR (RefFilter IS NOT NULL
    AND (
    r.ReceiptPaymentCode LIKE CONCAT('%', RefFilter, '%')
    OR r.Description LIKE CONCAT('%', RefFilter, '%')
    OR r.OrganizationUnitName LIKE CONCAT('%', RefFilter, '%')
    )))
    AND (DateFrom IS NULL
    OR DateTo IS NULL
    OR (DateFrom IS NOT NULL
    AND DateTo IS NOT NULL
    AND r.AccountingDate BETWEEN DateFrom AND DateTo));

    /* Tổng số trang */
    SET TotalPage = CEILING(1.0 * TotalRecord / PageSize);

  END IF;
END
$$

--
-- Create procedure `Proc_GetReceiptPaymentById`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetReceiptPaymentById (IN ReceiptPaymentId varchar(36))
COMMENT 'Lấy thông tin phiếu thu/chi tiền mặt theo khóa chính'
BEGIN
  SELECT
    *
  FROM view_receiptpayment r
  WHERE r.ReceiptPaymentId = ReceiptPaymentId LIMIT 1;
END
$$

--
-- Create function `Func_GetNewCodeNumber`
--
CREATE DEFINER = 'dev'@'%'
FUNCTION Func_GetNewCodeNumber (MaxNumber bigint, Len int)
RETURNS varchar(50) CHARSET utf8
BEGIN
  DECLARE newCodeNumber varchar(50) DEFAULT '';
  --   Tăng mã thêm 1 đơn vị
  SET newCodeNumber = CAST((MaxNumber + 1) AS char);
  --   Thêm số 0 đằng trước nếu chưa đủ độ dài (so với mã cũ)
  WHILE LENGTH(newCodeNumber) < Len DO
    SET newCodeNumber = CONCAT('0', newCodeNumber);
  END WHILE;

  RETURN newCodeNumber;
END
$$

--
-- Create function `Func_ExtractNumber`
--
CREATE DEFINER = 'dev'@'%'
FUNCTION Func_ExtractNumber (InputStr varchar(255))
RETURNS bigint(20)
COMMENT 'Lấy ra số từ xâu ký tự'
BEGIN
  DECLARE flag varchar(50);
  DECLARE findNumber varchar(50) DEFAULT '';
  DECLARE sChar varchar(1);
  DECLARE i integer DEFAULT 1;

  IF LENGTH(InputStr) > 0 THEN
    WHILE (i <= LENGTH(InputStr)) DO
      SET sChar = SUBSTRING(InputStr, i, 1);
      SET flag = FIND_IN_SET(sChar, '0,1,2,3,4,5,6,7,8,9');
      IF flag > 0 THEN
        SET findNumber = CONCAT(findNumber, sChar);
      END IF;
      SET i = i + 1;
    END WHILE;
    RETURN CAST(findNumber AS UNSIGNED integer);
  ELSE
    RETURN 0;
  END IF;
END
$$

--
-- Create procedure `Proc_GetNewReceiptPaymentCode`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetNewReceiptPaymentCode ()
BEGIN
  SET @MAX_NUMBER = (SELECT
      MAX(Func_ExtractNumber(r.ReceiptPaymentCode))
    FROM receiptpayment r);
  SET @MAX_CODE = (SELECT
      r.ReceiptPaymentCode
    FROM receiptpayment r
    WHERE Func_ExtractNumber(r.ReceiptPaymentCode) = @MAX_NUMBER);
  SET @PREFIX_CODE = "PC";
  SET @NEW_CODE_NUMBER = (SELECT
      Func_GetNewCodeNumber(@MAX_NUMBER, LENGTH(@MAX_CODE) - LENGTH(@PREFIX_CODE)));

  SET @NEW_CODE = CONCAT(@PREFIX_CODE, @NEW_CODE_NUMBER);
  SELECT
    @NEW_CODE;
END
$$

--
-- Create procedure `Proc_GetNewEmployeeCode`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetNewEmployeeCode ()
COMMENT 'Lấy mã nhân viên mới'
BEGIN

  SET @MAX_NUMBER = (SELECT
      MAX(Func_ExtractNumber(e.EmployeeCode))
    FROM Employee e);
  SET @MAX_CODE = (SELECT
      e.EmployeeCode
    FROM Employee e
    WHERE Func_ExtractNumber(e.EmployeeCode) = @MAX_NUMBER);
  SET @PREFIX_CODE = "NV-";
  SET @NEW_CODE_NUMBER = (SELECT
      Func_GetNewCodeNumber(@MAX_NUMBER, LENGTH(@MAX_CODE) - LENGTH(@PREFIX_CODE)));

  SET @NEW_CODE = CONCAT(@PREFIX_CODE, @NEW_CODE_NUMBER);
  SELECT
    @NEW_CODE;
END
$$

--
-- Create procedure `Proc_GetCloneEmployeeById`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetCloneEmployeeById (IN EmployeeId varchar(36))
COMMENT 'Lấy bản sao thông tin nhân viên và thay mã nhân viên bằng mã mới'
BEGIN
  SET @MAX_NUMBER = (SELECT
      MAX(Func_ExtractNumber(e.EmployeeCode))
    FROM Employee e);
  SET @MAX_CODE = (SELECT
      e.EmployeeCode
    FROM Employee e
    WHERE Func_ExtractNumber(e.EmployeeCode) = @MAX_NUMBER);
  SET @PREFIX_CODE = "NV-";
  SET @NEW_CODE_NUMBER = (SELECT
      Func_GetNewCodeNumber(@MAX_NUMBER, LENGTH(@MAX_CODE) - LENGTH(@PREFIX_CODE)));

  SET @NEW_CODE = CONCAT(@PREFIX_CODE, @NEW_CODE_NUMBER);
  SELECT
    @NEW_CODE AS EmployeeCode,
    e.EmployeeName,
    e.DateOfBirth,
    e.Gender,
    e.DepartmentId,
    e.DepartmentName,
    e.IdentityNumber,
    e.IdentityDate,
    e.IdentityPlace,
    e.EmployeePosition,
    e.Address,
    e.BankAccountNumber,
    e.BankName,
    e.BankBranchName,
    e.BankProvinceName,
    e.PhoneNumber,
    e.TelephoneNumber,
    e.Email,
    e.CreatedBy,
    e.CreatedDate,
    e.ModifiedBy,
    e.ModifiedDate
  FROM View_Employee e
  WHERE e.EmployeeId = EmployeeId LIMIT 1;
END
$$

DELIMITER ;

-- 
-- Dumping data for table department
--
INSERT INTO department VALUES
('11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Phòng Đào tạo', 'Quo et consectetur. Omnis dolorem delectus quo corporis suscipit officiis; incidunt saepe vel nostrum ex et sed.', 'Lê Ngọc Mai', '2021-09-29 10:14:55', 'Lê Ngọc Mai', '2021-09-29 10:14:55'),
('142cb08f-7c31-21fa-8e90-67245e8b283e', 'Phòng Công nghệ', 'Praesentium excepturi architecto ipsum possimus. Dolore molestiae omnis nihil. Aliquid perspiciatis qui. Ea sed nam; accusantium ipsam ut. Soluta.', 'Phạm Gia Thành', '2021-09-29 10:14:55', 'Phạm Gia Thành', '2021-09-29 10:14:55'),
('17120d02-6ab5-3e43-18cb-66948daf6128', 'Phòng Nhân sự', 'Neque amet ut. Natus quis ratione. Itaque tempore ut. Enim impedit magnam. Quo consectetur temporibus! Excepturi debitis perspiciatis. Quis et expedita!', 'Đào Thùy Yến', '2021-09-29 10:14:55', 'Đào Thùy Yến', '2021-09-29 10:14:55'),
('469b3ece-744a-45d5-957d-e8c757976496', 'Phòng Marketing', 'Quam odit provident dolor. Natus error velit consequatur hic vero ut! Est nemo molestiae adipisci qui quia ipsam.', 'Nguyễn Thị  Hân', '2021-09-29 10:14:55', 'Nguyễn Thị  Hân', '2021-09-29 10:14:55'),
('4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Phòng Sản xuất', 'Qui tempora nisi similique laboriosam illum nesciunt. Unde similique omnis voluptatem sit nisi ipsum. Illum accusantium sit quia quidem; in et fuga.', 'Phạm Văn Hùng', '2021-09-29 10:14:55', 'Phạm Văn Hùng', '2021-09-29 10:14:55');

-- 
-- Dumping data for table employee
--
INSERT INTO employee VALUES
('11a8748f-3464-740c-28c2-579daad24557', 'NV-0017', 'Trịnh Thùy Nga', '1971-09-29', 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '005690571067', '2018-10-04', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', 'Xã Tân Quới, Huyện Thanh Bình, Tỉnh Đồng Tháp', '01035876', 'BIDV', 'Chi nhánh Thăng Long', 'Hà Nội', '0954016489', '0288443398', NULL, 'Nguyễn Thị Hân ', '2020-01-16 10:50:00', 'Phạm Gia Thành', '2020-01-16 10:50:00'),
('12693b29-274c-35ce-d11d-086412a8ea97', 'NV-0039', 'Đường Bảo Hoàng', '2000-01-07', 2, '142cb08f-7c31-21fa-8e90-67245e8b283e', '009425323252', '2020-01-13', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', 'hường Trường An, Thành phố Huế, Tỉnh Thừa Thiên Huế', '25477671', 'Agribank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0814407095', '0241108022', NULL, 'Phạm Gia Thành', '2020-01-16 14:30:00', 'Phạm Gia Thành', '2020-01-16 14:30:00'),
('12e1b096-3542-127a-1077-d9ebc53aac3d', 'NV-0021', 'Lê Bảo Bảo', '2000-06-17', 0, '469b3ece-744a-45d5-957d-e8c757976496', '002957443991', '2020-09-30', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Quản lý', 'Phường 8, Thành phố Mỹ Tho, Tỉnh Tiền Giang', '06686345', 'BIDV', 'Chi nhánh Đông Anh', 'Hà Nội', '0849406195', '0242321057', 'Edward.B_Craddock933@gmail.com', 'Nguyễn Thị Hân ', '2020-01-16 11:30:00', 'Nguyễn Thị Hân', '2020-01-16 11:30:00'),
('13ede5b6-19dd-563e-1980-de64d090a2c2', 'NV-0015', 'Hoàng Thanh Mai', '1992-10-28', 2, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '008138567961', '2019-07-24', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Xà Hồ, Huyện Trạm Tấu, Tỉnh Yên Bái', '95168695', 'BIDV', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0929006249', '0282909769', NULL, 'Phạm Gia Thành', '2020-01-16 10:30:00', 'Nguyễn Thị Hân', '2020-01-16 10:30:00'),
('14aa1334-3d35-32c4-30c2-579daad24557', 'NV-0079', 'Nguyễn Văn Thành', NULL, 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '000691269386', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, NULL, '69856315', 'VietinBank', 'Chi nhánh Chương Dương', 'Hà Nội', NULL, '0286705533', NULL, 'Phạm Gia Thành', '2020-01-16 21:10:00', 'Phạm Gia Thành', '2020-01-16 21:10:00'),
('17872e95-3d24-6d1a-32c2-579daad24557', 'NV-0090', 'Đoàn Đức Nghĩa', '2002-12-08', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '001810775825', '2017-09-28', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Quản lý', 'Xã Đông Hải, Huyện Tiên Yên, Tỉnh Quảng Ninh', '03322600', 'MBBank', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', '0989847849', '0287420307', NULL, 'Nguyễn Thị Hân ', '2020-01-16 23:00:00', 'Nguyễn Thị Hân', '2020-01-16 23:00:00'),
('18baaac1-2b18-2317-b9d2-89b22d10517e', 'NV-0043', 'Nguyễn Thị Hân', '1994-01-28', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '006634667656', '2020-03-31', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'ị trấn Trà Lĩnh, Huyện Trùng Khánh, Tỉnh Cao Bằng', '82325106', 'VietinBank', 'Chi nhánh Hà Đông', 'Hà Nội', '0390383678', '0281709847', NULL, 'Nguyễn Thị Hân ', '2020-01-16 15:10:00', 'Nguyễn Thị Hân', '2020-01-16 15:10:00'),
('18bbd5d8-6c2d-154c-bad2-89b22d10517e', 'NV-0057', 'Nguyễn Vân Nguyệt', '1953-06-15', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '001182054341', '2021-02-19', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng phòng', 'Phường Ngọc Lâm, Quận Long Biên, Thành phố Hà Nội', '15605556', 'Á Châu (ACB)', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0810922124', '0289621277', NULL, 'Nguyễn Thị Hân ', '2020-01-16 17:30:00', 'Phạm Gia Thành', '2020-01-16 17:30:00'),
('18d2ec1b-61c5-1896-2ec2-579daad24557', 'NV-0064', 'Nguyễn Minh Chí', '1978-10-30', 2, '469b3ece-744a-45d5-957d-e8c757976496', '009726138258', '2020-10-14', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'Xã Đại Lai, Huyện Gia Bình, Tỉnh Bắc Ninh', '06918541', 'Tiên Phong - TPBank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0817830265', '0249034597', 'wasuacm08@gmail.com', 'Phạm Gia Thành', '2020-01-16 18:40:00', 'Phạm Gia Thành', '2020-01-16 18:40:00'),
('1906737f-3aed-5704-1777-d9ebc53aac3d', 'NV-0074', 'Nguyễn Trung Bách', '1967-04-16', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '002658295113', '2019-11-27', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'ã Trường Thịnh, Huyện Ứng Hòa, Thành phố Hà Nội', '97918377', 'Đông Á - Dong A Bank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0399410863', '0240706527', NULL, 'Nguyễn Thị Hân ', '2020-01-16 20:20:00', 'Nguyễn Thị Hân', '2020-01-16 20:20:00'),
('19256041-7623-2834-6df6-423b4e874d0f', 'NV-0087', 'Nguyễn Thùy Ánh', '1951-02-16', 1, '142cb08f-7c31-21fa-8e90-67245e8b283e', '003575948397', '2017-10-27', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Phong Dụ, Huyện Tiên Yên, Tỉnh Quảng Ninh', '09256964', 'VietinBank', NULL, 'Hà Nội', '0972629953', NULL, NULL, 'Nguyễn Thị Hân ', '2020-01-16 22:30:00', 'Phạm Gia Thành', '2020-01-16 22:30:00'),
('197fda97-5a35-781d-0e77-d9ebc53aac3d', 'NV-0005', 'Nguyễn Khánh Thành', NULL, 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '005930433253', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', NULL, '64201413', 'VietinBank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', NULL, '0284746538', NULL, 'Nguyễn Thị Hân ', '2020-01-16 08:50:00', 'Nguyễn Thị Hân', '2020-01-16 08:50:00'),
('1d05a704-5376-15ba-1477-d9ebc53aac3d', 'NV-0052', 'Phạm Thùy Hương', '1980-08-21', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '005745631617', '2018-07-16', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Phường 10, Thành phố Vũng Tàu, Tỉnh Bà Rịa - Vũng Tàu', '44009197', 'BIDV', 'Chi nhánh Hà Đông', 'Hà Nội', '0860757357', '0282363413', NULL, 'Phạm Gia Thành', '2020-01-16 16:40:00', 'Nguyễn Thị Hân', '2020-01-16 16:40:00'),
('1e5ce342-2eec-79a4-5380-7ed9d1ea06ea', 'NV-0056', 'Nguyễn Văn Huy', '2001-05-26', 1, '142cb08f-7c31-21fa-8e90-67245e8b283e', '006715902274', '2017-05-15', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Xã Buôn Choah, Huyện Krông Nô, Tỉnh Đắk Nông', '73873651', 'Vietcom Bank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0991917484', '0280861723', NULL, 'Nguyễn Thị Hân ', '2020-01-16 17:20:00', 'Phạm Gia Thành', '2020-01-16 17:20:00'),
('1e5e96fa-5d7a-599d-27c2-579daad24557', 'NV-0008', 'Nguyễn Bảo Khôi', '1993-02-05', 2, '469b3ece-744a-45d5-957d-e8c757976496', '008149797383', '2018-04-06', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'ã Hòa Long, Huyện Lai Vung, Tỉnh Đồng Tháp', '94143734', 'BIDV', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', '0887746182', '0287808140', NULL, 'Phạm Gia Thành', '2020-01-16 09:20:00', 'Phạm Gia Thành', '2020-01-16 09:20:00'),
('1f85f165-3ed3-370a-b7d2-89b22d10517e', 'NV-0028', 'Trương Thị Nhung', '1989-07-07', 2, '469b3ece-744a-45d5-957d-e8c757976496', '006842979828', '2016-11-12', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng phòng', 'Xã Thị Hoa, Huyện Hạ Lang, Tỉnh Cao Bằng', '00411721', 'Sacombank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0954100200', '0242022157', NULL, 'Phạm Gia Thành', '2020-01-16 12:40:00', 'Nguyễn Thị Hân', '2020-01-16 12:40:00'),
('1fecd07f-2488-638c-8141-c1ec321fe728', 'NV-0050', 'Trần Thanh Hoàng', '1951-01-12', 1, '469b3ece-744a-45d5-957d-e8c757976496', '001758589319', '2016-06-17', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Phường Ninh Dương, Thành phố Móng Cái, Tỉnh Quảng Ninh', '10611829', 'Đông Á - Dong A Bank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0977100141', '0286940562', NULL, 'Phạm Gia Thành', '2020-01-16 16:20:00', 'Nguyễn Thị Hân', '2020-01-16 16:20:00'),
('2107e2a5-49f8-237b-5780-7ed9d1ea06ea', 'NV-0095', 'Nguyễn Ngọc Anh', NULL, 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '000088556643', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, NULL, '97661979', NULL, 'Chi nhánh Hà Đông', NULL, NULL, '0284886303', NULL, 'Nguyễn Thị Hân ', '2020-01-16 23:50:00', 'Nguyễn Thị Hân', '2020-01-16 23:50:00'),
('212a5f62-4eb8-203c-4035-0028ed526dd0', 'NV-0077', 'Nguyễn Thùy Mai', '1997-01-16', 0, '469b3ece-744a-45d5-957d-e8c757976496', '001302217873', '2016-03-31', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'Xã Ân Phong, Huyện Hoài Ân, Tỉnh Bình Định', '36359403', 'VietinBank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0852664464', '0244504312', NULL, 'Phạm Gia Thành', '2020-01-16 20:50:00', 'Phạm Gia Thành', '2020-01-16 20:50:00'),
('21ae5078-5e68-3790-6af6-423b4e874d0f', 'NV-0061', 'Nguyễn Văn Hoàng', '1995-01-06', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '008377417404', '2019-09-29', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, '� Thắng Thuỷ, Huyện Vĩnh Bảo, Thành phố Hải Phòng', '94028504', 'Sacombank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0915973385', '0286712120', NULL, 'Phạm Gia Thành', '2020-01-16 18:10:00', 'Phạm Gia Thành', '2020-01-16 18:10:00'),
('2356a2d8-7751-6f97-66f6-423b4e874d0f', 'NV-0026', 'Nguyễn Vân Hân', '1957-09-07', 2, '142cb08f-7c31-21fa-8e90-67245e8b283e', '006463144348', '2020-07-19', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Trưởng phòng', 'Xã Tư Mại, Huyện Yên Dũng, Tỉnh Bắc Giang', '25621405', 'Kỹ thương - Techcombank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0880602383', '0249744399', 'ArnulfoBatten@yahoo.com', 'Nguyễn Thị Hân ', '2020-01-16 12:20:00', 'Phạm Gia Thành', '2020-01-16 12:20:00'),
('27e60da2-385e-6804-8441-c1ec321fe728', 'NV-0071', 'Nguyễn Thanh Bắc', '1988-11-18', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '002085103075', '2016-01-02', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Xã Công Bằng, Huyện Pác Nặm, Tỉnh Bắc Kạn', '34968970', 'Agribank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0343169243', '0288891965', NULL, 'Phạm Gia Thành', '2020-01-16 19:50:00', 'Phạm Gia Thành', '2020-01-16 19:50:00'),
('28a16581-1fd1-546b-1677-d9ebc53aac3d', 'NV-0070', 'Nguyễn Trung Chí', '1951-03-03', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '000026402484', '2020-09-26', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Xã Cư Ni, Huyện Ea Kar, Tỉnh Đắk Lắk', '46345460', 'Việt Á - VietABank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0381898384', '0243552121', 'Riggs76@gmail.com', 'Nguyễn Thị Hân ', '2020-01-16 19:40:00', 'Nguyễn Thị Hân', '2020-01-16 19:40:00'),
('28cd1599-63bf-785f-4f80-7ed9d1ea06ea', 'NV-0006', 'Triệu Khánh Duy', '1964-01-15', 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '004756200678', '2018-01-08', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', 'Xã Cẩm Bình, Huyện Cẩm Thủy, Tỉnh Thanh Hóa', '47728258', 'Á Châu (ACB)', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0992987488', '0245097331', NULL, 'Phạm Gia Thành', '2020-01-16 09:00:00', 'Nguyễn Thị Hân', '2020-01-16 09:00:00'),
('2afb2146-430d-394b-3d35-0028ed526dd0', 'NV-0047', 'Ngô Văn Hùng', '1978-11-02', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '008582712865', '2016-03-18', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Trung Hoà, Quận Cầu Giấy, Thành phố Hà Nội', '34761780', 'Việt Á - VietABank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0962636553', '0241666260', 'Charlton419@gmail.com', 'Nguyễn Thị Hân ', '2020-01-16 15:50:00', 'Nguyễn Thị Hân', '2020-01-16 15:50:00'),
('2efc0ff3-37c0-286f-bbd2-89b22d10517e', 'NV-0067', 'Trần Thùy Anh', '1991-03-15', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '008911549398', '2016-01-02', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Trưởng phòng', 'Phường Kim Mã, Quận Ba Đình, Thành phố Hà Nội', '99920357', 'Á Châu (ACB)', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', '0847317802', '0288999356', NULL, 'Nguyễn Thị Hân ', '2020-01-16 19:10:00', 'Nguyễn Thị Hân', '2020-01-16 19:10:00'),
('2f43fc9d-1f7a-25fc-5280-7ed9d1ea06ea', 'NV-0042', 'Đỗ Thanh Khôi', '2000-05-18', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '009694136694', '2016-01-02', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Xã Viên Thành, Huyện Yên Thành, Tỉnh Nghệ An', '03030848', 'BIDV', 'Chi nhánh Chương Dương', 'Hà Nội', '0922702110', '0283177909', NULL, 'Nguyễn Thị Hân ', '2020-01-16 15:00:00', 'Nguyễn Thị Hân', '2020-01-16 15:00:00'),
('2f4cc91d-6f13-4b4c-1c80-de64d090a2c2', 'NV-0065', 'Phan Ngọc Nhung', '1959-08-17', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '004682852438', '2020-01-09', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'ã Lộc Đức, Huyện Bảo Lâm, Tỉnh Lâm Đồng', '92445165', 'Việt Á - VietABank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0338967537', '0249141084', NULL, 'Nguyễn Thị Hân ', '2020-01-16 18:50:00', 'Phạm Gia Thành', '2020-01-16 18:50:00'),
('322105dd-142f-392d-2fc2-579daad24557', 'NV-0073', 'Ngô Mai Oanh', '1990-03-18', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '006197426424', '2016-09-18', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Giám đốc', 'Phường Thượng Đình, Quận Thanh Xuân, Thành phố Hà Nội', '58537594', 'Vietcom Bank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0358818041', '0248989258', 'Elia_L_Bunnell86@gmail.com', 'Phạm Gia Thành', '2020-01-16 20:10:00', 'Nguyễn Thị Hân', '2020-01-16 20:10:00'),
('324ac33a-77c5-13a5-0535-60b3ebf808a9', 'NV-0098', 'Phạm Đức Bách', '1999-04-10', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '005146248864', '2016-01-04', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Hướng Phùng, Huyện Hướng Hóa, Tỉnh Quảng Trị', '60880418', NULL, NULL, NULL, '0324873602', NULL, NULL, 'Nguyễn Thị Hân ', '2020-01-17 00:20:00', 'Phạm Gia Thành', '2020-01-17 00:20:00'),
('3304dddb-1b72-607f-25c2-579daad24557', 'NV-0000', 'Nguyễn Thanh Tùng', '1979-01-16', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '008169527271', '2017-08-30', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Thực tập sinh', 'Xã Ngọc Linh, Huyện Vị Xuyên, Tỉnh Hà Giang', '31170770', 'VietinBank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0923549424', '0288474996', NULL, 'Phạm Gia Thành', '2020-01-16 08:00:00', 'Phạm Gia Thành', '2020-01-16 08:00:00'),
('337faf61-662b-461a-69f6-423b4e874d0f', 'NV-0051', 'Nguyễn Ngọc Oanh', '1974-07-10', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '009134806274', '2018-09-28', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'ị trấn Cô Tô, Huyện Cô Tô, Tỉnh Quảng Ninh', '29315050', 'HD Bank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0394082302', '0285658720', NULL, 'Nguyễn Thị Hân ', '2020-01-16 16:30:00', 'Nguyễn Thị Hân', '2020-01-16 16:30:00'),
('350cf027-3245-532d-bcd2-89b22d10517e', 'NV-0082', 'Đỗ Thảo Thảo', '1993-08-04', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '007168834329', '2017-02-23', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Thực tập sinh', 'Phường Đội Cấn, Quận Ba Đình, Thành phố Hà Nội', '60711364', 'VietinBank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0914999494', '0284819105', NULL, 'Phạm Gia Thành', '2020-01-16 21:40:00', 'Phạm Gia Thành', '2020-01-16 21:40:00'),
('35c3a053-254d-33f3-1b80-de64d090a2c2', 'NV-0035', 'Nguyễn Văn Khang', '1957-01-06', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '004782118454', '2017-12-03', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', '� Ea Phê, Huyện Krông Pắc, Tỉnh Đắk Lắk', '17620136', 'Á Châu (ACB)', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0327028568', '0240480366', 'PrestonHeadley13@yahoo.com', 'Phạm Gia Thành', '2020-01-16 13:50:00', 'Nguyễn Thị Hân', '2020-01-16 13:50:00'),
('360bd1e4-7bbf-3971-d41d-086412a8ea97', 'NV-0072', 'Trương Văn Chí', '1966-11-20', 1, '142cb08f-7c31-21fa-8e90-67245e8b283e', '005671921873', '2020-09-21', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Xã Liên Sơn, Huyện Kim Bảng, Tỉnh Hà Nam', '76814016', 'Tiên Phong - TPBank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0815239278', '0247418905', NULL, 'Nguyễn Thị Hân ', '2020-01-16 20:00:00', 'Phạm Gia Thành', '2020-01-16 20:00:00'),
('36ac2df8-2b1e-368f-cc1d-086412a8ea97', 'NV-0009', 'Triệu Trung Hoàng', '1992-01-24', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '002837180179', '2021-03-26', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Thị trấn Tân Quới, Huyện Bình Tân, Tỉnh Vĩnh Long', '66263877', 'HD Bank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0994637469', '0281685932', 'Conrad_Frizzell61@gmail.com', 'Nguyễn Thị Hân ', '2020-01-16 09:30:00', 'Nguyễn Thị Hân', '2020-01-16 09:30:00'),
('3738ce93-1661-5628-2cc2-579daad24557', 'NV-0049', 'Đỗ Khánh Bình', '1956-01-13', 0, '469b3ece-744a-45d5-957d-e8c757976496', '000422120078', '2020-08-06', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Thị trấn Đà Bắc, Huyện Đà Bắc, Tỉnh Hoà Bình', '08650237', 'BIDV', 'Chi nhánh Thăng Long', 'Hà Nội', '0892860953', '0283591458', NULL, 'Nguyễn Thị Hân ', '2020-01-16 16:10:00', 'Phạm Gia Thành', '2020-01-16 16:10:00'),
('38dc720e-654a-29d5-34c2-579daad24557', 'NV-0097', 'Lương Mai Ánh', '1961-11-04', 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '000454300318', '2021-06-14', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'Xã Bản Giang, Huyện Tam Đường, Tỉnh Lai Châu', '55299518', NULL, NULL, NULL, '0838574917', NULL, NULL, 'Phạm Gia Thành', '2020-01-17 00:10:00', 'Nguyễn Thị Hân', '2020-01-17 00:10:00'),
('3a425a4d-6066-116b-6bf6-423b4e874d0f', 'NV-0069', 'Trịnh Thanh Bách', '1998-06-20', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '001654076962', '2016-09-28', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Phố Huế, Quận Hai Bà Trưng, Thành phố Hà Nội', '16527608', 'BIDV', 'Chi nhánh Chương Dương', 'Hà Nội', '0971272763', '0285421915', NULL, 'Nguyễn Thị Hân ', '2020-01-16 19:30:00', 'Nguyễn Thị Hân', '2020-01-16 19:30:00'),
('3abffc51-2a43-18c6-6cf6-423b4e874d0f', 'NV-0075', 'Vũ Khánh Nguyệt', '1973-03-14', 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '001708014036', '2021-05-21', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Hang Kia, Huyện Mai Châu, Tỉnh Hoà Bình', '76743080', 'Sacombank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0987598705', '0240587417', 'Tad.Shumaker37@gmail.com', 'Nguyễn Thị Hân ', '2020-01-16 20:30:00', 'Phạm Gia Thành', '2020-01-16 20:30:00'),
('3d18d4c2-2f39-3dce-d61d-086412a8ea97', 'NV-0088', 'Nguyễn Khánh Hoàng', '1953-10-29', 1, '469b3ece-744a-45d5-957d-e8c757976496', '004463968074', '2016-04-23', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Phú Hòa, Huyện Định Quán, Tỉnh Đồng Nai', '63087529', 'Đông Á - Dong A Bank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0327628775', '0283107800', NULL, 'Phạm Gia Thành', '2020-01-16 22:40:00', 'Phạm Gia Thành', '2020-01-16 22:40:00'),
('3e51a46c-4153-229c-7f41-c1ec321fe728', 'NV-0033', 'Nguyễn Thùy Tâm', '1990-10-04', 1, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '007928831641', '2020-08-17', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'Xã Tây Cốc, Huyện Đoan Hùng, Tỉnh Phú Thọ', '53996785', 'Á Châu (ACB)', NULL, 'Hà Nội', '0928897373', NULL, NULL, 'Phạm Gia Thành', '2020-01-16 13:30:00', 'Phạm Gia Thành', '2020-01-16 13:30:00'),
('3e7dd0ec-7ee5-392a-1277-d9ebc53aac3d', 'NV-0040', 'Đường Văn Hòa', '2001-09-01', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '004771306443', '2018-11-11', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Nguyễn Huệ, Huyện Hoà An, Tỉnh Cao Bằng', '83724266', 'Kỹ thương - Techcombank', 'Chi nhánh Chương Dương', 'Hà Nội', '0890593284', '0287357091', NULL, 'Phạm Gia Thành', '2020-01-16 14:40:00', 'Phạm Gia Thành', '2020-01-16 14:40:00'),
('3fc4ed08-1219-1c6d-5480-7ed9d1ea06ea', 'NV-0060', 'Hoàng Văn Trung', '1995-09-04', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '003408612767', '2019-05-23', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng phòng', 'Xã Tịnh Ấn Tây, Thành phố Quảng Ngãi, Tỉnh Quảng Ngãi', '22850850', 'Kỹ thương - Techcombank', 'Chi nhánh Hà Đông', 'Hà Nội', '0995241862', '0246228047', NULL, 'Nguyễn Thị Hân ', '2020-01-16 18:00:00', 'Phạm Gia Thành', '2020-01-16 18:00:00'),
('3fed64ec-2f94-798f-0335-60b3ebf808a9', 'NV-0045', 'Lương Thị Diễm', '1992-08-31', 2, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '007233796212', '2020-11-27', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Xã Thái Xuyên, Huyện Thái Thụy, Tỉnh Thái Bình', '57622097', 'Vietcom Bank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0346484564', '0282633002', NULL, 'Nguyễn Thị Hân ', '2020-01-16 15:30:00', 'Phạm Gia Thành', '2020-01-16 15:30:00'),
('407db4d1-222b-287d-0135-60b3ebf808a9', 'NV-0020', 'Lê Thanh Yến', '1992-08-13', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '003491535160', '2017-04-12', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Văn Đẩu, Quận Kiến An, Thành phố Hải Phòng', '76640815', 'BIDV', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0984823792', '0242106666', NULL, 'Nguyễn Thị Hân ', '2020-01-16 11:20:00', 'Nguyễn Thị Hân', '2020-01-16 11:20:00'),
('409dcd1a-426a-23f7-3a35-0028ed526dd0', 'NV-0011', 'Đỗ Minh Bảo', '1961-03-06', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '006046324945', '2021-03-28', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'ã Định Thủy, Huyện Mỏ Cày Nam, Tỉnh Bến Tre', '10609386', 'Kỹ thương - Techcombank', 'Chi nhánh Đông Anh', 'Hà Nội', '0932926668', '0249914972', 'JeremyHaywood255@gmail.com', 'Phạm Gia Thành', '2020-01-16 09:50:00', 'Nguyễn Thị Hân', '2020-01-16 09:50:00'),
('42b9446a-790b-3892-2ac2-579daad24557', 'NV-0032', 'Phan Thị Diễm', '1969-10-03', 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '008046890429', '2018-07-17', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Phường 1, Thành phố Bạc Liêu, Tỉnh Bạc Liêu', '84223397', 'BIDV', 'Chi nhánh Hà Đông', 'Hà Nội', '0866354494', '0283144348', NULL, 'Nguyễn Thị Hân ', '2020-01-16 13:20:00', 'Phạm Gia Thành', '2020-01-16 13:20:00'),
('42db9027-5e76-257b-33c2-579daad24557', 'NV-0093', 'Nguyễn Thảo Oanh', '1959-05-22', 1, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '007627938872', '2016-03-06', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Đội Cấn, Quận Ba Đình, Thành phố Hà Nội', '43754995', 'Tiên Phong - TPBank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0862495537', '0244246808', 'Jung648@gmail.com', 'Phạm Gia Thành', '2020-01-16 23:30:00', 'Nguyễn Thị Hân', '2020-01-16 23:30:00'),
('45bd4aa1-3832-3db8-d21d-086412a8ea97', 'NV-0053', 'Ngô Kim Chí', '1963-02-27', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '004284597256', '2016-07-21', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'ã An Sơn, Huyện Kiên Hải, Tỉnh Kiên Giang', '88140693', 'VietinBank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0830370303', '0243949654', NULL, 'Nguyễn Thị Hân ', '2020-01-16 16:50:00', 'Phạm Gia Thành', '2020-01-16 16:50:00'),
('481183cb-5a6c-795b-68f6-423b4e874d0f', 'NV-0044', 'Trịnh Minh Nam', NULL, 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '007045502291', NULL, 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Quản lý', NULL, '85862914', 'Á Châu (ACB)', 'Chi nhánh Hà Thành', 'Hà Nội', NULL, '0241184542', NULL, 'Phạm Gia Thành', '2020-01-16 15:20:00', 'Nguyễn Thị Hân', '2020-01-16 15:20:00'),
('4989ff24-23e7-7b82-b6d2-89b22d10517e', 'NV-0022', 'Triệu Văn Long', '1981-02-22', 1, '142cb08f-7c31-21fa-8e90-67245e8b283e', '000454612260', '2017-11-08', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Thọ Bình, Huyện Triệu Sơn, Tỉnh Thanh Hóa', '04199565', 'Kỹ thương - Techcombank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0348594964', '0286724028', NULL, 'Phạm Gia Thành', '2020-01-16 11:40:00', 'Phạm Gia Thành', '2020-01-16 11:40:00'),
('4bf9ecda-2d8e-1724-1d80-de64d090a2c2', 'NV-0080', 'Đỗ Trung Khôi', '1956-02-27', 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '008901083975', '2017-12-29', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Quản lý', 'Phường 19, Quận Bình Thạnh, Thành phố Hồ Chí Minh', '18052726', 'Kỹ thương - Techcombank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0395547964', '0244654771', NULL, 'Nguyễn Thị Hân ', '2020-01-16 21:20:00', 'Phạm Gia Thành', '2020-01-16 21:20:00'),
('4c9ebdde-5f9a-58dd-4235-0028ed526dd0', 'NV-0096', 'Lương Văn Chính', '1980-06-13', 2, '469b3ece-744a-45d5-957d-e8c757976496', '003623645110', '2016-01-09', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, '� Tiên Ngoại, Thị Xã Duy Tiên, Tỉnh Hà Nam', '28086444', NULL, NULL, NULL, '0885649057', NULL, NULL, 'Phạm Gia Thành', '2020-01-17 00:00:00', 'Nguyễn Thị Hân', '2020-01-17 00:00:00'),
('4cc606bb-3068-7d32-3f35-0028ed526dd0', 'NV-0062', 'Trương Minh Bắc', '1977-02-23', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '004217911469', '2019-08-21', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Xã Minh Tân, Huyện Đông Hưng, Tỉnh Thái Bình', '48870738', 'BIDV', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0969144407', '0243217585', NULL, 'Phạm Gia Thành', '2020-01-16 18:20:00', 'Phạm Gia Thành', '2020-01-16 18:20:00'),
('4db9a514-6d87-2ec1-3b35-0028ed526dd0', 'NV-0031', 'Trịnh Trung Long', '1960-12-10', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '009651108022', '2019-02-02', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Cư Suê, Huyện Cư M''gar, Tỉnh Đắk Lắk', '74984179', 'Kỹ thương - Techcombank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0872326094', '0281465294', NULL, 'Phạm Gia Thành', '2020-01-16 13:10:00', 'Nguyễn Thị Hân', '2020-01-16 13:10:00'),
('4f65f6c1-4525-16e5-4135-0028ed526dd0', 'NV-0092', 'Nguyễn Văn Duy', NULL, 2, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '008867107731', NULL, 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Thực tập sinh', NULL, '48501410', 'Vietcom Bank', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', NULL, '0285161974', NULL, 'Nguyễn Thị Hân ', '2020-01-16 23:20:00', 'Phạm Gia Thành', '2020-01-16 23:20:00'),
('506acf1e-5331-67a9-0d77-d9ebc53aac3d', 'NV-0002', 'Lê Khánh Bắc', '1991-01-20', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '003408520312', '2018-12-07', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Giám đốc', 'Xã An Thủy, Huyện Lệ Thủy, Tỉnh Quảng Bình', '54212612', 'Vietcom Bank', 'Chi nhánh Thăng Long', 'Hà Nội', '0884323787', '0244224085', NULL, 'Nguyễn Thị Hân ', '2020-01-16 08:20:00', 'Nguyễn Thị Hân', '2020-01-16 08:20:00'),
('50c07587-55d5-5b36-1b77-d9ebc53aac3d', 'NV-0094', 'Lê Thị Oanh', '1975-03-29', 1, '469b3ece-744a-45d5-957d-e8c757976496', '002942766038', '2018-07-01', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', 'Xã Suối Tọ, Huyện Phù Yên, Tỉnh Sơn La', '62586148', NULL, 'Chi nhánh Hà Đông', NULL, '0906851714', '0245113561', 'AbrahamF@gmail.com', 'Nguyễn Thị Hân ', '2020-01-16 23:40:00', 'Phạm Gia Thành', '2020-01-16 23:40:00'),
('524751f2-1577-523d-ce1d-086412a8ea97', 'NV-0019', 'Vũ Bảo Hòa', '1951-01-07', 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '004877545669', '2018-12-19', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', 'Phường An Hòa, Thị Xã Trảng Bàng, Tỉnh Tây Ninh', '01072355', 'Sacombank', 'Chi nhánh Hà Đông', 'Hà Nội', '0390380123', '0240205878', 'KearneyG616@gmail.com', 'Nguyễn Thị Hân ', '2020-01-16 11:10:00', 'Nguyễn Thị Hân', '2020-01-16 11:10:00'),
('5254e49d-4368-3162-29c2-579daad24557', 'NV-0027', 'Nguyễn Văn Duy', '1966-11-16', 1, '469b3ece-744a-45d5-957d-e8c757976496', '004461660255', '2019-10-11', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Cam Phúc Nam, Thành phố Cam Ranh, Tỉnh Khánh Hòa', '18709971', 'MBBank', 'Chi nhánh Hà Thành', 'Hà Nội', '0818896641', '0280073773', NULL, 'Phạm Gia Thành', '2020-01-16 12:30:00', 'Phạm Gia Thành', '2020-01-16 12:30:00'),
('527e293c-2185-6d0a-5580-7ed9d1ea06ea', 'NV-0068', 'Lương Khánh Nam', '1959-11-28', 0, '469b3ece-744a-45d5-957d-e8c757976496', '004365409658', '2019-06-30', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Giám đốc', 'Xã Long Kiến, Huyện Chợ Mới, Tỉnh An Giang', '31043829', 'MBBank', 'Chi nhánh Hà Thành', 'Hà Nội', '0883951309', '0280251052', NULL, 'Phạm Gia Thành', '2020-01-16 19:20:00', 'Nguyễn Thị Hân', '2020-01-16 19:20:00'),
('53f68d51-267f-2d1e-8241-c1ec321fe728', 'NV-0055', 'Nguyễn Thùy Ánh', '1998-06-15', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '005867105299', '2018-11-06', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Phường Đông Vệ, Thành phố Thanh Hóa, Tỉnh Thanh Hóa', '41885532', 'BIDV', 'Chi nhánh Hà Đông', 'Hà Nội', '0849367078', '0241177045', 'Adair@gmail.com', 'Phạm Gia Thành', '2020-01-16 17:10:00', 'Nguyễn Thị Hân', '2020-01-16 17:10:00'),
('5697b103-5179-7ac3-d31d-086412a8ea97', 'NV-0066', 'Ngô Ngọc Trang', '1995-04-08', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '007980143407', '2016-08-07', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Xã Đắk Tờ Re, Huyện Kon Rẫy, Tỉnh Kon Tum', '90033103', 'VP Bank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0815010413', '0240877256', NULL, 'Nguyễn Thị Hân ', '2020-01-16 19:00:00', 'Nguyễn Thị Hân', '2020-01-16 19:00:00'),
('56aaf263-3355-23ea-b8d2-89b22d10517e', 'NV-0037', 'Dương Bảo Trung', '1953-05-17', 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '004683240416', '2019-02-20', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Đồng Tân, Huyện Hiệp Hòa, Tỉnh Bắc Giang', '73744810', 'Việt Á - VietABank', 'Chi nhánh Hà Thành', 'Hà Nội', '0918247825', '0285093286', NULL, 'Nguyễn Thị Hân ', '2020-01-16 14:10:00', 'Phạm Gia Thành', '2020-01-16 14:10:00'),
('56dce332-76f0-6b9b-5080-7ed9d1ea06ea', 'NV-0016', 'Vương Thanh Mai', '1966-11-30', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '007336367754', '2017-07-14', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'ã Minh Thạnh, Huyện Dầu Tiếng, Tỉnh Bình Dương', '70405875', 'BIDV', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', '0936922631', '0243012377', NULL, 'Nguyễn Thị Hân ', '2020-01-16 10:40:00', 'Nguyễn Thị Hân', '2020-01-16 10:40:00'),
('57cdf8c4-47e3-5560-7e41-c1ec321fe728', 'NV-0001', 'Nguyễn Thị Uyên', NULL, 1, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '008815566304', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Giám đốc', NULL, '59574742', 'VietinBank', 'Chi nhánh Thanh Xuân', 'Hà Nội', NULL, '0246927756', NULL, 'Nguyễn Thị Hân ', '2020-01-16 08:10:00', 'Nguyễn Thị Hân', '2020-01-16 08:10:00'),
('595e7d51-318c-39e8-1377-d9ebc53aac3d', 'NV-0048', 'Dương Vân Hiền', '2001-04-09', 0, '469b3ece-744a-45d5-957d-e8c757976496', '000636948966', '2016-09-08', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Liêng Srônh, Huyện Đam Rông, Tỉnh Lâm Đồng', '53921372', NULL, 'Chi nhánh Chương Dương', NULL, '0840736673', '0280700444', NULL, 'Nguyễn Thị Hân ', '2020-01-16 16:00:00', 'Nguyễn Thị Hân', '2020-01-16 16:00:00'),
('5a841b92-791c-78df-5180-7ed9d1ea06ea', 'NV-0034', 'Phạm Gia Bắc', '1983-06-14', 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '005806442926', '2020-02-11', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Kim Mã, Quận Ba Đình, Thành phố Hà Nội', '53494265', 'Á Châu (ACB)', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0377139811', '0288030395', NULL, 'Phạm Gia Thành', '2020-01-16 13:40:00', 'Nguyễn Thị Hân', '2020-01-16 13:40:00'),
('5c7f0ec4-77f2-3794-cf1d-086412a8ea97', 'NV-0023', 'Đặng Đức Hùng', '1966-09-12', 1, '469b3ece-744a-45d5-957d-e8c757976496', '000221571059', '2020-10-16', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'ã Thu Cúc, Huyện Tân Sơn, Tỉnh Phú Thọ', '83075092', 'Vietcom Bank', 'Chi nhánh Chương Dương', 'Hà Nội', '0833140555', '0283203677', 'Winston@yahoo.com', 'Phạm Gia Thành', '2020-01-16 11:50:00', 'Phạm Gia Thành', '2020-01-16 11:50:00'),
('5c85f9f2-1de1-4f0a-3e35-0028ed526dd0', 'NV-0059', 'Nguyễn Thanh Duy', '1999-10-15', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '001560906523', '2019-02-15', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Xã Lạc Vân, Huyện Nho Quan, Tỉnh Ninh Bình', '55355976', 'Agribank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0824058166', '0285792736', 'Ivelisse_Beattie@gmail.com', 'Phạm Gia Thành', '2020-01-16 17:50:00', 'Phạm Gia Thành', '2020-01-16 17:50:00'),
('5de704c2-573f-1a71-1a80-de64d090a2c2', 'NV-0024', 'Hoàng Phương Duyên', NULL, 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '002360928628', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Quản lý', NULL, '54984373', NULL, 'Chi nhánh Bắc Từ Liêm', NULL, NULL, '0285669402', NULL, 'Phạm Gia Thành', '2020-01-16 12:00:00', 'Phạm Gia Thành', '2020-01-16 12:00:00'),
('5eaa6527-768d-3ae7-1977-d9ebc53aac3d', 'NV-0089', 'Ngô Văn Chí', '1988-07-28', 2, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '009614775078', '2016-02-06', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'ã Hát Môn, Huyện Phúc Thọ, Thành phố Hà Nội', '92541320', 'BIDV', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0979943258', '0246402484', NULL, 'Nguyễn Thị Hân ', '2020-01-16 22:50:00', 'Nguyễn Thị Hân', '2020-01-16 22:50:00'),
('5f03d745-7702-1c85-2bc2-579daad24557', 'NV-0046', 'Vương Hoàng Bách', '2001-03-21', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '002536497565', '2017-08-10', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Trưởng nhóm', 'Xã Xuân Lam, Huyện Hưng Nguyên, Tỉnh Nghệ An', '88169493', 'Sacombank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0993782076', '0244683240', 'Reeder@gmail.com', 'Nguyễn Thị Hân ', '2020-01-16 15:40:00', 'Nguyễn Thị Hân', '2020-01-16 15:40:00'),
('5fab4ff7-1b8e-64d0-1880-de64d090a2c2', 'NV-0007', 'Trần Ngọc Quỳnh', '1991-04-28', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '009524835076', '2018-04-15', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Phường Đông Hương, Thành phố Thanh Hóa, Tỉnh Thanh Hóa', '76270931', 'HD Bank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0949968669', '0282878594', NULL, 'Phạm Gia Thành', '2020-01-16 09:10:00', 'Phạm Gia Thành', '2020-01-16 09:10:00'),
('62563348-7bd5-6519-3c35-0028ed526dd0', 'NV-0036', 'Lê Khánh Tùng', '1964-11-20', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '001236023511', '2018-12-18', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Hoàng Trĩ, Huyện Ba Bể, Tỉnh Bắc Kạn', '13735576', 'VietinBank', 'Chi nhánh Hà Thành', 'Hà Nội', '0990414565', '0240886446', NULL, 'Phạm Gia Thành', '2020-01-16 14:00:00', 'Nguyễn Thị Hân', '2020-01-16 14:00:00'),
('62af2231-78a7-7caa-cd1d-086412a8ea97', 'NV-0014', 'Nguyễn Thị Nguyệt', '2003-12-29', 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '002548028117', '2017-06-11', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', '� Liên Vị, Thị Xã Quảng Yên, Tỉnh Quảng Ninh', '25822148', 'Agribank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0857129667', '0281194929', NULL, 'Nguyễn Thị Hân ', '2020-01-16 10:20:00', 'Nguyễn Thị Hân', '2020-01-16 10:20:00'),
('6485b64f-7835-65a4-8041-c1ec321fe728', 'NV-0041', 'Phạm Phương Linh', '2000-10-10', 1, '469b3ece-744a-45d5-957d-e8c757976496', '005474477783', '2018-04-04', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Giám đốc', 'Thị trấn Yên Mỹ, Huyện Yên Mỹ, Tỉnh Hưng Yên', '87173817', NULL, 'Chi nhánh Thanh Xuân', NULL, '0929204048', '0244792883', NULL, 'Nguyễn Thị Hân ', '2020-01-16 14:50:00', 'Phạm Gia Thành', '2020-01-16 14:50:00'),
('65ecf5c2-5298-156e-d51d-086412a8ea97', 'NV-0085', 'Đoàn Gia Khang', '1970-01-29', 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '009012238487', '2018-04-06', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Thực tập sinh', 'Xã Pú Nhi, Huyện Điện Biên Đông, Tỉnh Điện Biên', '59024554', 'MBBank', 'Chi nhánh Hà Đông', 'Hà Nội', '0859021138', '0249426108', NULL, 'Phạm Gia Thành', '2020-01-16 22:10:00', 'Phạm Gia Thành', '2020-01-16 22:10:00'),
('66ef0b11-1892-1443-1877-d9ebc53aac3d', 'NV-0081', 'Đường Vân Hân', '1996-06-29', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '002540578426', '2021-04-26', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Tam Thành, Huyện Phú Ninh, Tỉnh Quảng Nam', '35712566', 'Agribank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0962323892', '0242818524', NULL, 'Phạm Gia Thành', '2020-01-16 21:30:00', 'Phạm Gia Thành', '2020-01-16 21:30:00'),
('677132b4-2a33-68d1-26c2-579daad24557', 'NV-0004', 'Đoàn Văn Hoàng', '1985-08-14', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '003677548818', '2019-10-21', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Thực tập sinh', 'Xã Bản Mù, Huyện Trạm Tấu, Tỉnh Yên Bái', '12706222', 'Agribank', 'Chi nhánh Hà Đông', 'Hà Nội', '0865549385', '0284071905', NULL, 'Phạm Gia Thành', '2020-01-16 08:40:00', 'Nguyễn Thị Hân', '2020-01-16 08:40:00'),
('6a763a51-4322-5c5a-b5d2-89b22d10517e', 'NV-0018', 'Trần Thanh Duyên', '1993-04-15', 2, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '002327756120', '2020-05-25', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Giám đốc', 'ã Chiềng Ngần, Thành phố Sơn La, Tỉnh Sơn La', '96349204', 'Agribank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0970866610', '0280281178', NULL, 'Nguyễn Thị Hân ', '2020-01-16 11:00:00', 'Phạm Gia Thành', '2020-01-16 11:00:00'),
('6b550b8f-7ff9-51bc-0f77-d9ebc53aac3d', 'NV-0012', 'Trương Vân Hương', NULL, 2, '142cb08f-7c31-21fa-8e90-67245e8b283e', '008039661821', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', NULL, '60850765', 'Kỹ thương - Techcombank', 'Chi nhánh Thanh Xuân', 'Hà Nội', NULL, '0280214373', NULL, 'Phạm Gia Thành', '2020-01-16 10:00:00', 'Phạm Gia Thành', '2020-01-16 10:00:00'),
('6b76d607-7d60-38a2-5680-7ed9d1ea06ea', 'NV-0083', 'Phạm Gia Long', '1999-11-09', 1, '469b3ece-744a-45d5-957d-e8c757976496', '003803844615', '2019-05-16', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Lê Hồ, Huyện Kim Bảng, Tỉnh Hà Nam', '54055085', 'BIDV', NULL, 'Hà Nội', '0336589308', NULL, 'ElfredaLynn@yahoo.com', 'Phạm Gia Thành', '2020-01-16 21:50:00', 'Phạm Gia Thành', '2020-01-16 21:50:00'),
('6c5b9fe7-14c9-3bb5-b4d2-89b22d10517e', 'NV-0013', 'Trịnh Thị  Anh', '1955-04-11', 2, '469b3ece-744a-45d5-957d-e8c757976496', '009869134733', '2017-08-15', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Phường Quán Thánh, Quận Ba Đình, Thành phố Hà Nội', '34621363', 'Vietcom Bank', NULL, 'Hà Nội', '0913609485', NULL, NULL, 'Nguyễn Thị Hân ', '2020-01-16 10:10:00', 'Nguyễn Thị Hân', '2020-01-16 10:10:00'),
('6c80a684-1cb5-41af-ff34-60b3ebf808a9', 'NV-0003', 'Đặng Thảo Yến', '1993-01-29', 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '005051343912', '2021-01-10', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Xã Phú Lệ, Huyện Quan Hóa, Tỉnh Thanh Hóa', '07332383', 'BIDV', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', '0912672420', '0244120102', NULL, 'Nguyễn Thị Hân ', '2020-01-16 08:30:00', 'Phạm Gia Thành', '2020-01-16 08:30:00'),
('6d489b13-7396-7986-1577-d9ebc53aac3d', 'NV-0058', 'Nguyễn Anh Hòa', '2001-11-03', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '007938202056', '2020-04-28', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Giám đốc', 'ã Cát Thành, Huyện Phù Cát, Tỉnh Bình Định', '96150760', 'Á Châu (ACB)', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0325249542', '0286355192', 'Grayson31@gmail.com', 'Phạm Gia Thành', '2020-01-16 17:40:00', 'Phạm Gia Thành', '2020-01-16 17:40:00'),
('6dcdb6b6-273a-6aaa-8541-c1ec321fe728', 'NV-0078', 'Nguyễn Văn Long', '1999-11-08', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '009077202087', '2019-10-30', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'hường Tiên Cát, Thành phố Việt Trì, Tỉnh Phú Thọ', '05573993', NULL, 'Chi nhánh Thanh Xuân', NULL, '0898257270', '0244835044', 'Sheets524@yahoo.com', 'Phạm Gia Thành', '2020-01-16 21:00:00', 'Phạm Gia Thành', '2020-01-16 21:00:00'),
('6f1014db-2ff0-613b-bdd2-89b22d10517e', 'NV-0086', 'Phan Thị Oanh', '1967-06-17', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '004080475342', '2020-04-16', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Giám đốc', 'Xã Xuân Hội, Huyện Nghi Xuân, Tỉnh Hà Tĩnh', '27527568', 'Á Châu (ACB)', 'Chi nhánh Đông Anh', 'Hà Nội', '0373691011', '0289880474', NULL, 'Nguyễn Thị Hân ', '2020-01-16 22:20:00', 'Nguyễn Thị Hân', '2020-01-16 22:20:00'),
('6f51ea57-13b2-139f-1177-d9ebc53aac3d', 'NV-0030', 'Đường Ngọc Phương', '2000-09-19', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '002639113798', '2017-07-21', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Linh Thông, Huyện Định Hóa, Tỉnh Thái Nguyên', '15156709', 'Kỹ thương - Techcombank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0995239569', '0283091219', NULL, 'Nguyễn Thị Hân ', '2020-01-16 13:00:00', 'Nguyễn Thị Hân', '2020-01-16 13:00:00'),
('707e1336-6584-55de-8341-c1ec321fe728', 'NV-0063', 'Nguyễn Thanh Anh', '1992-11-08', 1, '142cb08f-7c31-21fa-8e90-67245e8b283e', '005109278055', '2021-08-08', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Xã Sơn Hải, Huyện Kiên Lương, Tỉnh Kiên Giang', '99056864', 'Á Châu (ACB)', 'Chi nhánh Thăng Long', 'Hà Nội', '0384566605', '0243195041', NULL, 'Nguyễn Thị Hân ', '2020-01-16 18:30:00', 'Phạm Gia Thành', '2020-01-16 18:30:00'),
('721b7460-7378-2203-0435-60b3ebf808a9', 'NV-0076', 'Lê Ngọc Hiền', '1966-03-18', 1, '469b3ece-744a-45d5-957d-e8c757976496', '007621355666', '2021-03-12', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Tân Hà, Huyện Hàm Tân, Tỉnh Bình Thuận', '42193733', 'HD Bank', NULL, 'Hà Nội', '0375092752', NULL, NULL, 'Nguyễn Thị Hân ', '2020-01-16 20:40:00', 'Phạm Gia Thành', '2020-01-16 20:40:00'),
('73dc79e1-1ccb-35a6-0235-60b3ebf808a9', 'NV-0025', 'Đường Thảo Diễm', NULL, 1, '142cb08f-7c31-21fa-8e90-67245e8b283e', '000995433115', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', NULL, '91783500', 'Agribank', 'Chi nhánh Hà Thành', 'Hà Nội', NULL, '0241597732', NULL, 'Phạm Gia Thành', '2020-01-16 12:10:00', 'Phạm Gia Thành', '2020-01-16 12:10:00'),
('78b1d514-338c-3cdc-8641-c1ec321fe728', 'NV-0099', 'Lê Văn Bảo', NULL, 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '000922109721', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, NULL, '73134011', NULL, NULL, NULL, NULL, NULL, NULL, 'Nguyễn Thị Hân ', '2020-01-17 00:30:00', 'Phạm Gia Thành', '2020-01-17 00:30:00'),
('7a301ea4-331e-73f6-1a77-d9ebc53aac3d', 'NV-0091', 'Phan Khánh Bảo', '1997-02-16', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '002405056668', '2020-09-16', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', 'Xã Thục Luyện, Huyện Thanh Sơn, Tỉnh Phú Thọ', '88867766', 'VP Bank', 'Chi nhánh Đông Anh', 'Hà Nội', '0845253407', '0282665649', NULL, 'Nguyễn Thị Hân ', '2020-01-16 23:10:00', 'Phạm Gia Thành', '2020-01-16 23:10:00'),
('7ad34860-1ac8-7ad7-d01d-086412a8ea97', 'NV-0029', 'Phạm Thị Uyên', '1995-09-02', 0, '469b3ece-744a-45d5-957d-e8c757976496', '000644636629', '2018-05-01', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Phường Quán Thánh, Quận Ba Đình, Thành phố Hà Nội', '45449011', 'BIDV', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0369661749', '0285900271', NULL, 'Nguyễn Thị Hân ', '2020-01-16 12:50:00', 'Phạm Gia Thành', '2020-01-16 12:50:00'),
('7b666cc3-1b67-6037-67f6-423b4e874d0f', 'NV-0038', 'Trần Vân Uyên', '1951-01-07', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '005457773815', '2019-04-21', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'Phường Nguyễn An Ninh, Thành phố Vũng Tàu, Tỉnh Bà Rịa - Vũng Tàu', '20923472', 'Vietcom Bank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0853067321', '0244369959', NULL, 'Phạm Gia Thành', '2020-01-16 14:20:00', 'Nguyễn Thị Hân', '2020-01-16 14:20:00'),
('7bd9cf39-3f55-3a7b-0035-60b3ebf808a9', 'NV-0010', 'Hồ Gia Bắc', '1997-02-27', 2, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '004067437313', '2017-03-13', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'ường Tân Giang, Thành phố Hà Tĩnh, Tỉnh Hà Tĩnh', '06837288', 'Sacombank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0377950492', '0288775222', NULL, 'Nguyễn Thị Hân ', '2020-01-16 09:40:00', 'Nguyễn Thị Hân', '2020-01-16 09:40:00'),
('7c1ae6ac-6c72-7436-2dc2-579daad24557', 'NV-0054', 'Nguyễn Thị Mai', '1972-03-07', 0, '469b3ece-744a-45d5-957d-e8c757976496', '000578523169', '2016-01-01', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Đăk Năng, Thành phố Kon Tum, Tỉnh Kon Tum', '74264835', 'Sacombank', NULL, 'Hà Nội', '0862318121', NULL, NULL, 'Nguyễn Thị Hân ', '2020-01-16 17:00:00', 'Nguyễn Thị Hân', '2020-01-16 17:00:00'),
('7f1b6c7c-2b74-3ebb-31c2-579daad24557', 'NV-0084', 'Nguyễn Văn Khôi', '1991-03-12', 0, '469b3ece-744a-45d5-957d-e8c757976496', '005973182044', '2019-02-19', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Giám đốc', 'Xã Thuận Đức, Thành Phố Đồng Hới, Tỉnh Quảng Bình', '46413788', 'HD Bank', 'Chi nhánh Hà Thành', 'Hà Nội', '0342532196', '0288004627', NULL, 'Phạm Gia Thành', '2020-01-16 22:00:00', 'Nguyễn Thị Hân', '2020-01-16 22:00:00');

-- 
-- Dumping data for table receiptpayment
--
INSERT INTO receiptpayment VALUES
('12437806-26ac-3517-9c0b-87ae14180c33', 'PC000014', '2020-11-18', '2020-11-17', 2300000.0000, 'Chi khác', '1e5ce342-2eec-79a4-5380-7ed9d1ea06ea', 'Nguyễn Văn Huy', 'Xã Buôn Choah, Huyện Krông Nô, Tỉnh Đắk Nông', 'Chi tiền cho Nguyễn Văn Huy', '38dc720e-654a-29d5-34c2-579daad24557', 0, '[{"Description":"Chi tiền cho Nguyễn Văn Huy","DebitAccount":"3384","CreditAccount":"1111HAD","Amount":2300000,"OrganizationUnitId":"1e5ce342-2eec-79a4-5380-7ed9d1ea06ea","OrganizationUnitName":"Nguyễn Văn Huy"}]', '2020-11-18 08:00:33', 'Nguyễn Văn Duy', '2021-10-03 10:31:18', 'Nguyễn Văn Duy'),
('148ed882-32b8-218e-9c20-39c2f00615e8', 'PC000000', '2021-06-22', '2021-06-18', 500000.0000, 'Chi khác', '324ac33a-77c5-13a5-0535-60b3ebf808a9', 'Phạm Đức Bách', 'Xã Hướng Phùng, Huyện Hướng Hóa, Tỉnh Quảng Trị', 'Chi tiền cho Phạm Đức Bách', '7a301ea4-331e-73f6-1a77-d9ebc53aac3d', 1, '[{"Description":"Chi tiền cơm trưa","DebitAccount":"6416","CreditAccount":"1111CAG","Amount":500000,"OrganizationUnitId":"324ac33a-77c5-13a5-0535-60b3ebf808a9","OrganizationUnitName":"Phạm Đức Bách"}]', '2021-06-22 20:53:46', 'Phạm Gia Thành', '2021-10-03 10:34:47', 'Phạm Gia Thành'),
('15d0d796-1465-4665-fc83-196123975cb2', 'PC000009', '2021-06-10', '2021-06-10', 4560000.0000, 'Chi khác', '6b76d607-7d60-38a2-5680-7ed9d1ea06ea', 'Phạm Gia Long', 'Xã Lê Hồ, Huyện Kim Bảng, Tỉnh Hà Nam', 'Chi tiền cho tổng kết 6 tháng đầu năm', '78b1d514-338c-3cdc-8641-c1ec321fe728', 3, '[{"Description":"Chi tiền cho tổng kết 6 tháng đầu năm","DebitAccount":"3382","CreditAccount":"1111HAD","Amount":4560000,"OrganizationUnitId":"6b76d607-7d60-38a2-5680-7ed9d1ea06ea","OrganizationUnitName":"Phạm Gia Long"}]', '2021-06-10 01:18:41', 'Trương Thị Ngân', '2021-10-03 10:40:59', 'Trương Thị Ngân'),
('22f29725-54f0-11f0-9d0b-87ae14180c33', 'PC000019', '2021-08-03', '2021-07-31', 2250000.0000, 'Chi khác', '3d18d4c2-2f39-3dce-d61d-086412a8ea97', 'Nguyễn Khánh Hoàng', 'Xã Phú Hòa, Huyện Định Quán, Tỉnh Đồng Nai', 'Chi tiền cho Nguyễn Khánh Hoàng', '6485b64f-7835-65a4-8041-c1ec321fe728', 1, '[{"Description":"Chi tiền bảo hiểm","DebitAccount":"3384","CreditAccount":"1111CAG","Amount":2250000,"OrganizationUnitId":"3d18d4c2-2f39-3dce-d61d-086412a8ea97","OrganizationUnitName":"Nguyễn Khánh Hoàng"}]', '2021-08-03 14:43:35', 'Lương Phương Hương', '2021-10-03 10:26:04', 'Lương Phương Hương'),
('2ea8deee-1b95-2a51-88d5-ba100c6f7bce', 'PC000012', '2021-05-23', '2021-05-20', 3700000.0000, 'Chi khác', '324ac33a-77c5-13a5-0535-60b3ebf808a9', 'Phạm Đức Bách', 'Xã Hướng Phùng, Huyện Hướng Hóa, Tỉnh Quảng Trị', 'Chi tiền cho Phạm Đức Bách', '38dc720e-654a-29d5-34c2-579daad24557', 3, '[{"Description":"Chi tiền bảo hiểm thất nghiệp","DebitAccount":"3386","CreditAccount":"1111HBT","Amount":3700000,"OrganizationUnitId":"324ac33a-77c5-13a5-0535-60b3ebf808a9","OrganizationUnitName":"Phạm Đức Bách"}]', '2021-05-23 04:34:50', 'Phan Vân Hoài', '2021-10-03 10:39:20', 'Phan Vân Hoài'),
('354f1b13-17bf-1b52-87d5-ba100c6f7bce', 'PC000003', '2020-11-19', '2020-11-15', 6820000.0000, 'Chi khác', '7f1b6c7c-2b74-3ebb-31c2-579daad24557', 'Nguyễn Văn Khôi', 'Xã Thuận Đức, Thành Phố Đồng Hới, Tỉnh Quảng Bình', 'Chi tiền cho Nguyễn Văn Khôi', '38dc720e-654a-29d5-34c2-579daad24557', 0, '[{"Description":"Chi tiền cơm trưa","DebitAccount":"6416","CreditAccount":"1111CAG","Amount":500000,"OrganizationUnitId":"7f1b6c7c-2b74-3ebb-31c2-579daad24557","OrganizationUnitName":"Nguyễn Văn Khôi"},{"Description":"Chi tiền lương","DebitAccount":"6417","CreditAccount":"1111CAG","Amount":6320000,"OrganizationUnitId":"7f1b6c7c-2b74-3ebb-31c2-579daad24557","OrganizationUnitName":"Nguyễn Văn Khôi"}]', '2020-11-19 10:30:26', 'Đào Thùy Yến', '2021-10-03 10:24:17', 'Đào Thùy Yến'),
('357d7c4e-4b7f-11c2-84c0-08fd2f807219', 'PC000018', '2021-07-27', '2021-07-21', 2500000.0000, 'Chi khác', '42b9446a-790b-3892-2ac2-579daad24557', 'Phan Thị Diễm', 'Phường 1, Thành phố Bạc Liêu, Tỉnh Bạc Liêu', 'Chi tiền cho Phan Thị Diễm', '38dc720e-654a-29d5-34c2-579daad24557', 1, '[{"Description":"Chi tiền Bảo hiểm","DebitAccount":"3384","CreditAccount":"1111CAG","Amount":2500000,"OrganizationUnitId":"42b9446a-790b-3892-2ac2-579daad24557","OrganizationUnitName":"Phan Thị Diễm"}]', '2021-07-27 09:36:06', 'Nguyễn Phương Nguyệt', '2021-10-03 10:25:32', 'Nguyễn Phương Nguyệt'),
('36104b10-705b-57a8-83c0-08fd2f807219', 'PC000008', '2021-02-04', '2021-01-31', 4000000.0000, 'Chi khác', '78b1d514-338c-3cdc-8641-c1ec321fe728', 'Lê Văn Bảo', NULL, 'Chi tiền cho Lê Văn Bảo', '38dc720e-654a-29d5-34c2-579daad24557', 2, '[{"Description":"Chi tiền bảo hiểm thất nghiệp","DebitAccount":"3386","CreditAccount":"1111CAG","Amount":4000000,"OrganizationUnitId":"78b1d514-338c-3cdc-8641-c1ec321fe728","OrganizationUnitName":"Lê Văn Bảo"}]', '2021-02-04 15:01:14', 'Nguyễn Thị Linh', '2021-10-03 10:31:00', 'Nguyễn Thị Linh'),
('3700cc49-55b5-69ea-4929-a2925c0f334d', 'PC000002', '2021-01-11', '2021-01-09', 12540000.0000, 'Chi khác', '5254e49d-4368-3162-29c2-579daad24557', 'Nguyễn Văn Duy', 'Phường Cam Phúc Nam, Thành phố Cam Ranh, Tỉnh Khánh Hòa', 'Chi tiền cho Nguyễn Văn Duy', '38dc720e-654a-29d5-34c2-579daad24557', 2, '[{"Description":"Chi tiền bảo hiểm y tế","DebitAccount":"3384","CreditAccount":"1111HBT","Amount":2040000,"OrganizationUnitId":"5254e49d-4368-3162-29c2-579daad24557","OrganizationUnitName":"Nguyễn Văn Duy"},{"Description":"Chi tiền bảo hiểm thất nghiệp","DebitAccount":"3386","CreditAccount":"1111HBT","Amount":4000000,"OrganizationUnitId":"5254e49d-4368-3162-29c2-579daad24557","OrganizationUnitName":"Nguyễn Văn Duy"},{"Description":"Chi tiền lương","DebitAccount":"6417","CreditAccount":"1111HBT","Amount":6500000,"OrganizationUnitId":"5254e49d-4368-3162-29c2-579daad24557","OrganizationUnitName":"Nguyễn Văn Duy"}]', '2021-01-11 07:45:34', 'Phạm Văn Hùng', '2021-10-03 10:31:50', 'Phạm Văn Hùng'),
('37dd9bb0-4c53-4134-31de-23e177779933', 'PC000007', '2021-01-03', '2020-12-29', 4000000.0000, 'Chi khác', '6f1014db-2ff0-613b-bdd2-89b22d10517e', 'Phan Thị Oanh', 'Xã Xuân Hội, Huyện Nghi Xuân, Tỉnh Hà Tĩnh', 'Chi tiền cho hoạt động 8/3', '38dc720e-654a-29d5-34c2-579daad24557', 2, '[{"Description":"Chi tiền 8/3","DebitAccount":"3382","CreditAccount":"1111HBT","Amount":4000000,"OrganizationUnitId":"6f1014db-2ff0-613b-bdd2-89b22d10517e","OrganizationUnitName":"Phan Thị Oanh"}]', '2021-01-03 19:06:58', 'Phạm Minh Chí', '2021-10-03 10:31:31', 'Phạm Minh Chí'),
('38528581-656f-2902-32de-23e177779933', 'PC000016', '2020-11-11', '2020-11-11', 5460000.0000, 'Chi khác', '4c9ebdde-5f9a-58dd-4235-0028ed526dd0', 'Lương Văn Chính', '� Tiên Ngoại, Thị Xã Duy Tiên, Tỉnh Hà Nam', 'Chi tiền cho Lương Văn Chính', '38dc720e-654a-29d5-34c2-579daad24557', NULL, '[{"Description":"Chi tiền cho Lương Văn Chính","DebitAccount":"6417","CreditAccount":"1111HAD","Amount":5460000,"OrganizationUnitId":"4c9ebdde-5f9a-58dd-4235-0028ed526dd0","OrganizationUnitName":"Lương Văn Chính"}]', '2020-11-11 17:34:01', 'Vương Văn Bách', '2021-10-03 10:31:09', 'Vương Văn Bách'),
('4ae83cbf-238d-11ec-9e1d-a44cc8756a37', 'PC000022', '2021-10-02', '2021-10-02', 6500000.0000, 'Chi khác', '324ac33a-77c5-13a5-0535-60b3ebf808a9', 'Phạm Đức Bách', 'Xã Hướng Phùng, Huyện Hướng Hóa, Tỉnh Quảng Trị', 'Chi tiền cho Phạm Đức Bách', NULL, NULL, '[{"Amount":6500000,"DebitAccount":"3384","CreditAccount":"1111CAG","Description":"Chi tiền lương"}]', '2021-10-02 21:28:30', NULL, '2021-10-03 10:41:58', NULL),
('53baae5e-52f2-2642-4a29-a2925c0f334d', 'PC000010', '2021-06-25', '2021-06-23', 24404000.0000, 'Chi khác', '4c9ebdde-5f9a-58dd-4235-0028ed526dd0', 'Lương Văn Chính', '� Tiên Ngoại, Thị Xã Duy Tiên, Tỉnh Hà Nam', 'Chi phí Marketting 6 tháng đầu năm', '38dc720e-654a-29d5-34c2-579daad24557', 1, '[{"Description":"Chi phí Marketting 6 tháng đầu năm","DebitAccount":"6411","CreditAccount":"1111HBT","Amount":23984000,"OrganizationUnitId":"4c9ebdde-5f9a-58dd-4235-0028ed526dd0","OrganizationUnitName":"Lương Văn Chính"},{"Description":"Phụ phí phát sinh","DebitAccount":"6411","CreditAccount":"1111HBT","Amount":420000,"OrganizationUnitId":"4c9ebdde-5f9a-58dd-4235-0028ed526dd0","OrganizationUnitName":"Lương Văn Chính"}]', '2021-06-25 13:56:48', 'Lê Khánh Bình', '2021-10-03 10:36:54', 'Lê Khánh Bình'),
('57a3f48f-1c1d-1f04-9e20-39c2f00615e8', 'PC000015', '2021-03-23', '2021-03-22', 3460000.0000, 'Chi khác', '3abffc51-2a43-18c6-6cf6-423b4e874d0f', 'Vũ Khánh Nguyệt', 'Xã Hang Kia, Huyện Mai Châu, Tỉnh Hoà Bình', 'Chi tiền cho Vũ Khánh Nguyệt', '38dc720e-654a-29d5-34c2-579daad24557', 1, '[{"Description":"Chi tiền bảo hiểm y tế","DebitAccount":"3384","CreditAccount":"1111CAG","Amount":3460000,"OrganizationUnitId":"3abffc51-2a43-18c6-6cf6-423b4e874d0f","OrganizationUnitName":"Vũ Khánh Nguyệt"}]', '2021-03-23 22:46:03', 'Nguyễn Khánh Hiền', '2021-10-03 10:37:44', 'Nguyễn Khánh Hiền'),
('62a849b4-1145-4227-7009-bf1378b8dc91', 'PC000017', '2021-02-07', '2021-02-02', 7970000.0000, 'Chi khác', '721b7460-7378-2203-0435-60b3ebf808a9', 'Lê Ngọc Hiền', 'Xã Tân Hà, Huyện Hàm Tân, Tỉnh Bình Thuận', 'Chi tiền cho Lê Ngọc Hiền', '6f1014db-2ff0-613b-bdd2-89b22d10517e', 2, '[{"Description":"Chi tiền bảo hiểm y tế","DebitAccount":"3384","CreditAccount":"1111HAD","Amount":3470000,"OrganizationUnitId":"721b7460-7378-2203-0435-60b3ebf808a9","OrganizationUnitName":"Lê Ngọc Hiền"},{"Description":"Chi tiền bảo hiểm xã hội","DebitAccount":"3383","CreditAccount":"1111HAD","Amount":2000000,"OrganizationUnitId":"721b7460-7378-2203-0435-60b3ebf808a9","OrganizationUnitName":"Lê Ngọc Hiền"},{"Description":"Chi phí hỗ trợ từ công đoàn","DebitAccount":"3382","CreditAccount":"1111HAD","Amount":2500000,"OrganizationUnitId":"721b7460-7378-2203-0435-60b3ebf808a9","OrganizationUnitName":"Lê Ngọc Hiền"}]', '2021-02-07 11:30:14', 'Vũ Ngọc Mai', '2021-10-03 10:34:05', 'Vũ Ngọc Mai'),
('83d71956-2456-11ec-9e1d-a44cc8756a37', 'PC000025', '2021-10-03', '2021-10-03', 1000000.0000, 'Chi khác', '324ac33a-77c5-13a5-0535-60b3ebf808a9', 'Phạm Đức Bách', 'Xã Hướng Phùng, Huyện Hướng Hóa, Tỉnh Quảng Trị', 'Chi tiền cho Phạm Đức Bách', '38dc720e-654a-29d5-34c2-579daad24557', 2, '[{"Description":"Chi tiền cho Phạm Đức Bách","DebitAccount":"6417","CreditAccount":"1111HAD","Amount":1000000,"OrganizationUnitId":"4c9ebdde-5f9a-58dd-4235-0028ed526dd0","OrganizationIUnitName":null,"OrganizationUnitName":"Lương Văn Chính"}]', '2021-10-03 21:28:42', NULL, NULL, NULL),
('9580854d-2119-11ec-9e1d-a44cc8756a37', 'PC000020', '2021-09-30', '2021-09-23', 15000000.0000, 'Chi khác', '2107e2a5-49f8-237b-5780-7ed9d1ea06ea', 'Nguyễn Ngọc Anh', NULL, 'Chi tiền cho Công đoàn', '78b1d514-338c-3cdc-8641-c1ec321fe728', 2, '[{"Amount":15000000,"CreditAccount":"1111HBT","DebitAccount":"3382","Description":"Chi tiền cho công đoàn","OrganizationUnitId":"2107e2a5-49f8-237b-5780-7ed9d1ea06ea","OrganizationUnitName":"Nguyễn Ngọc Anh"}]', '2021-09-29 18:35:36', NULL, '2021-10-02 20:59:33', NULL),
('9da039f5-2437-11ec-9e1d-a44cc8756a37', 'PC000023', '2021-10-03', '2021-10-03', 5152000.0000, 'Chi khác', '324ac33a-77c5-13a5-0535-60b3ebf808a9', 'Phạm Đức Bách', 'Xã Hướng Phùng, Huyện Hướng Hóa, Tỉnh Quảng Trị', 'Chi tiền cho Phạm Đức Bách', '38dc720e-654a-29d5-34c2-579daad24557', 2, '[{"Description":"Chi tiền cho Phạm Đức Bách","DebitAccount":"3384","CreditAccount":"1111HAD","Amount":3652000,"OrganizationUnitId":"324ac33a-77c5-13a5-0535-60b3ebf808a9","OrganizationIUnitName":null,"OrganizationUnitName":"Phạm Đức Bách"},{"Description":"Chi tiền hỗ trợ từ công đoàn","DebitAccount":"3382","CreditAccount":"1111HAD","Amount":1500000,"OrganizationUnitId":"2107e2a5-49f8-237b-5780-7ed9d1ea06ea","OrganizationIUnitName":null,"OrganizationUnitName":"Nguyễn Ngọc Anh"}]', '2021-10-03 17:47:32', NULL, '2021-10-03 21:29:39', NULL),
('c248c627-2456-11ec-9e1d-a44cc8756a37', 'PC000026', '2021-10-03', '2021-10-03', 5500000.0000, 'Chi khác', '4c9ebdde-5f9a-58dd-4235-0028ed526dd0', 'Lương Văn Chính', '� Tiên Ngoại, Thị Xã Duy Tiên, Tỉnh Hà Nam', 'Chi tiền cho Lương Văn Chính', '38dc720e-654a-29d5-34c2-579daad24557', 2, '[{"Description":"Chi tiền cho Lương Văn Chính","DebitAccount":"3384","CreditAccount":"1111HAD","Amount":4000000,"OrganizationUnitId":"4c9ebdde-5f9a-58dd-4235-0028ed526dd0","OrganizationIUnitName":null,"OrganizationUnitName":"Lương Văn Chính"},{"Description":"Chi tiền hỗ trợ từ công đoàn","DebitAccount":"3382","CreditAccount":"1111HAD","Amount":1500000,"OrganizationUnitId":"2107e2a5-49f8-237b-5780-7ed9d1ea06ea","OrganizationIUnitName":null,"OrganizationUnitName":"Nguyễn Ngọc Anh"}]', '2021-10-03 21:30:27', NULL, '2021-10-03 21:29:39', NULL),
('c40faa23-2128-11ec-9e1d-a44cc8756a37', 'PC000021', '2021-10-01', '2021-10-01', 900000.0000, 'Chi khác', '38dc720e-654a-29d5-34c2-579daad24557', 'Lương Mai Ánh', 'Xã Bản Giang, Huyện Tam Đường, Tỉnh Lai Châu', 'Chi tiền cho Lương Mai Ánh', '4c9ebdde-5f9a-58dd-4235-0028ed526dd0', 2, '[{"Amount":500000,"Description":"Chi tiền cho Lương Mai Ánh","DebitAccount":"3384","CreditAccount":"1112","OrganizationUnitId":"4c9ebdde-5f9a-58dd-4235-0028ed526dd0","OrganizationUnitName":"Lương Văn Chính"},{"Amount":400000,"Description":"Chi tiền cho Lương Mai Ánh","DebitAccount":"3382","CreditAccount":"1111HBT","OrganizationUnitId":"2107e2a5-49f8-237b-5780-7ed9d1ea06ea","OrganizationUnitName":"Nguyễn Ngọc Anh"}]', '2021-09-29 20:24:17', NULL, '2021-10-03 21:11:59', NULL);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;