--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 9/24/2021 10:55:27 AM
-- Server version: 5.5.5-10.1.41-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE `web06.test.mf901.pthieu`;

--
-- Drop procedure `Proc_GetCloneEmployeeById`
--
DROP PROCEDURE IF EXISTS Proc_GetCloneEmployeeById;

--
-- Drop procedure `Proc_GetNewEmployeeCode`
--
DROP PROCEDURE IF EXISTS Proc_GetNewEmployeeCode;

--
-- Drop function `Func_ExtractNumber`
--
DROP FUNCTION IF EXISTS Func_ExtractNumber;

--
-- Drop function `Func_GetNewCodeNumber`
--
DROP FUNCTION IF EXISTS Func_GetNewCodeNumber;

--
-- Drop procedure `Proc_GetEmployeeById`
--
DROP PROCEDURE IF EXISTS Proc_GetEmployeeById;

--
-- Drop procedure `Proc_GetEmployees`
--
DROP PROCEDURE IF EXISTS Proc_GetEmployees;

--
-- Drop procedure `Proc_GetEmployeesFilterPaging`
--
DROP PROCEDURE IF EXISTS Proc_GetEmployeesFilterPaging;

--
-- Drop view `view_employee`
--
DROP VIEW IF EXISTS view_employee CASCADE;

--
-- Drop procedure `Proc_DeleteEmployeeById`
--
DROP PROCEDURE IF EXISTS Proc_DeleteEmployeeById;

--
-- Drop procedure `Proc_InsertEmployee`
--
DROP PROCEDURE IF EXISTS Proc_InsertEmployee;

--
-- Drop procedure `Proc_UpdateEmployee`
--
DROP PROCEDURE IF EXISTS Proc_UpdateEmployee;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop procedure `Proc_DeleteDepartmentById`
--
DROP PROCEDURE IF EXISTS Proc_DeleteDepartmentById;

--
-- Drop procedure `Proc_GetDepartmentById`
--
DROP PROCEDURE IF EXISTS Proc_GetDepartmentById;

--
-- Drop procedure `Proc_GetDepartments`
--
DROP PROCEDURE IF EXISTS Proc_GetDepartments;

--
-- Drop procedure `Proc_InsertDepartment`
--
DROP PROCEDURE IF EXISTS Proc_InsertDepartment;

--
-- Drop procedure `Proc_UpdateDepartment`
--
DROP PROCEDURE IF EXISTS Proc_UpdateDepartment;

--
-- Drop table `department`
--
DROP TABLE IF EXISTS department;

--
-- Set default database
--
USE `web06.test.mf901.pthieu`;

--
-- Create table `department`
--
CREATE TABLE department (
  DepartmentId char(36) NOT NULL COMMENT 'Khóa chính/Id đơn vị',
  DepartmentName varchar(255) NOT NULL COMMENT 'tên đơn vị',
  Description varchar(255) DEFAULT NULL COMMENT 'Mô tả đơn vị',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Tên người tạo',
  CreatedDate datetime DEFAULT NULL COMMENT 'Thời điểm tạo',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Tên người chỉnh sửa cuối',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Thời điểm chỉnh sửa cuối',
  PRIMARY KEY (DepartmentId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Danh sách đơn vị/phòng ban';

DELIMITER $$

--
-- Create procedure `Proc_UpdateDepartment`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_UpdateDepartment (IN DepartmentId char(36), IN DepartmentName varchar(255), IN Description varchar(255), IN ModifiedBy varchar(100))
COMMENT 'Chỉnh sửa thông tin đơn vị/phòng ban'
BEGIN
  UPDATE Department d
  SET d.DepartmentName = DepartmentName,
      d.Description = Description,
      d.ModifiedBy = ModifiedBy,
      d.ModifiedDate = NOW()
  WHERE d.DepartmentId = DepartmentId;
END
$$

--
-- Create procedure `Proc_InsertDepartment`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_InsertDepartment (IN DepartmentId char(36), IN DepartmentName varchar(255), IN Description varchar(255), IN CreatedBy varchar(100))
COMMENT 'Thêm đơn vị/phòng ban mới'
BEGIN
  INSERT INTO Department (DepartmentId, DepartmentName, Description, CreatedBy, CreatedDate)
    VALUES (UUID(), DepartmentName, Description, CreatedBy, NOW());
END
$$

--
-- Create procedure `Proc_GetDepartments`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetDepartments ()
COMMENT 'Lấy danh sách tất cả đơn vị/phòng ban'
BEGIN
  SELECT
    *
  FROM Department d;
END
$$

--
-- Create procedure `Proc_GetDepartmentById`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetDepartmentById (IN DepartmentId varchar(36))
COMMENT 'Lấy thông tin đơn vị/phòng ban theo khóa chính'
BEGIN
  SELECT
    *
  FROM Department d
  WHERE d.DepartmentId = DepartmentId LIMIT 1;
END
$$

--
-- Create procedure `Proc_DeleteDepartmentById`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_DeleteDepartmentById (IN DepartmentId varchar(36))
COMMENT 'Xóa đơn vị/phòng ban theo khóa chính'
BEGIN
  DELETE
    FROM Department
  WHERE Department.DepartmentId = DepartmentId;
END
$$

DELIMITER ;

--
-- Create table `employee`
--
CREATE TABLE employee (
  EmployeeId char(36) NOT NULL COMMENT 'Id nhân viên/Khóa chính',
  EmployeeCode varchar(20) NOT NULL COMMENT 'mã nhân viên',
  EmployeeName varchar(100) NOT NULL COMMENT 'tên nhân viên',
  DateOfBirth date DEFAULT NULL COMMENT 'ngày sinh',
  Gender int(11) DEFAULT NULL COMMENT 'giới tính: 0-nam; 1-nữ; 2-khác',
  DepartmentId char(36) NOT NULL COMMENT 'Id của đơn vị/phòng ban',
  IdentityNumber varchar(25) DEFAULT NULL COMMENT 'Số CMTND/CCCD',
  IdentityDate date DEFAULT NULL COMMENT 'Ngày cấp CMTND/CCCD',
  IdentityPlace varchar(255) DEFAULT NULL COMMENT 'Nơi cấp CMTND/CCCD',
  EmployeePosition varchar(100) DEFAULT NULL COMMENT 'Chức danh',
  Address varchar(255) DEFAULT NULL COMMENT 'Địa chỉ nơi ở',
  BankAccountNumber varchar(25) DEFAULT NULL COMMENT 'Số tài khoản ngân hàng',
  BankName varchar(255) DEFAULT NULL COMMENT 'Tên ngân hàng',
  BankBranchName varchar(255) DEFAULT NULL COMMENT 'Tên chi nhánh ngân hàng',
  BankProvinceName varchar(255) DEFAULT NULL COMMENT 'Tên tỉnh của ngân hàng',
  PhoneNumber varchar(50) DEFAULT NULL COMMENT 'số điện thoại di động',
  TelephoneNumber varchar(50) DEFAULT NULL COMMENT 'số điện thoại cố định',
  Email varchar(100) DEFAULT NULL COMMENT 'Địa chỉ email',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Tên người tạo',
  CreatedDate datetime DEFAULT NULL COMMENT 'Thời điểm tạo',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Tên người chỉnh sửa cuối',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Thời điểm chỉnh sửa cuối',
  PRIMARY KEY (EmployeeId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 655,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Danh sách nhân viên';

--
-- Create index `UK_Employee_EmployeeCode` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX UK_Employee_EmployeeCode (EmployeeCode);

--
-- Create foreign key
--
ALTER TABLE employee
ADD CONSTRAINT FK_Employee_DepartmentId FOREIGN KEY (DepartmentId)
REFERENCES department (DepartmentId) ON DELETE NO ACTION;

DELIMITER $$

--
-- Create procedure `Proc_UpdateEmployee`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_UpdateEmployee (IN EmployeeId char(36), IN EmployeeCode varchar(20), IN EmployeeName varchar(100), IN DateOfBirth date, IN Gender int, IN DepartmentId char(36), IN IdentityNumber varchar(25), IN IdentityDate date, IN IdentityPlace varchar(255), IN EmployeePosition varchar(100), IN Address varchar(255), IN BankAccountNumber varchar(25), IN BankName varchar(255), IN BankBranchName varchar(255), IN BankProvinceName varchar(255), IN PhoneNumber varchar(50), IN TelephoneNumber varchar(50), IN Email varchar(100), IN CreatedBy varchar(100), IN CreatedDate datetime, IN ModifiedBy varchar(100), IN ModifiedDate datetime)
COMMENT 'Chỉnh sửa thông tin nhân viên'
BEGIN
  UPDATE Employee e
  SET e.EmployeeCode = EmployeeCode,
      e.EmployeeName = EmployeeName,
      e.DateOfBirth = DateOfBirth,
      e.Gender = Gender,
      e.DepartmentId = DepartmentId,
      e.IdentityNumber = IdentityNumber,
      e.IdentityDate = IdentityDate,
      e.IdentityPlace = IdentityPlace,
      e.EmployeePosition = EmployeePosition,
      e.Address = Address,
      e.BankAccountNumber = BankAccountNumber,
      e.BankName = BankName,
      e.BankBranchName = BankBranchName,
      e.BankProvinceName = BankProvinceName,
      e.PhoneNumber = PhoneNumber,
      e.TelephoneNumber = TelephoneNumber,
      e.Email = Email,
      e.CreatedBy = CreatedBy,
      e.CreatedDate = CreatedDate,
      e.ModifiedBy = ModifiedBy,
      e.ModifiedDate = NOW()
  WHERE e.EmployeeId = EmployeeId;
END
$$

--
-- Create procedure `Proc_InsertEmployee`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_InsertEmployee (IN EmployeeId char(36), IN EmployeeCode varchar(20), IN EmployeeName varchar(100), IN DateOfBirth date, IN Gender int, IN DepartmentId char(36), IN IdentityNumber varchar(25), IN IdentityDate date, IN IdentityPlace varchar(255), IN EmployeePosition varchar(100), IN Address varchar(255), IN BankAccountNumber varchar(25), IN BankName varchar(255), IN BankBranchName varchar(255), IN BankProvinceName varchar(255), IN PhoneNumber varchar(50), IN TelephoneNumber varchar(50), IN Email varchar(100), IN CreatedBy varchar(100), IN CreatedDate datetime, IN ModifiedBy varchar(100), IN ModifiedDate datetime)
COMMENT 'Thêm nhân viên mới'
BEGIN
  INSERT INTO Employee (EmployeeId,
  EmployeeCode,
  EmployeeName,
  DateOfBirth,
  Gender,
  DepartmentId,
  IdentityNumber,
  IdentityDate,
  IdentityPlace,
  EmployeePosition,
  Address,
  BankAccountNumber,
  BankName,
  BankBranchName,
  BankProvinceName,
  PhoneNumber,
  TelephoneNumber,
  Email,
  CreatedBy,
  CreatedDate,
  ModifiedBy,
  ModifiedDate)
    VALUES (UUID(), EmployeeCode, EmployeeName, DateOfBirth, Gender, DepartmentId, IdentityNumber, IdentityDate, IdentityPlace, EmployeePosition, Address, BankAccountNumber, BankName, BankBranchName, BankProvinceName, PhoneNumber, TelephoneNumber, Email, CreatedBy, NOW(), ModifiedBy, ModifiedDate);
END
$$

--
-- Create procedure `Proc_DeleteEmployeeById`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_DeleteEmployeeById (IN EmployeeId char(36))
COMMENT 'Xóa nhân viên dựa theo khóa chính'
BEGIN
  DELETE
    FROM Employee
  WHERE Employee.EmployeeId = EmployeeId;
END
$$

DELIMITER ;

--
-- Create view `view_employee`
--
CREATE
DEFINER = 'dev'@'%'
VIEW view_employee
AS
SELECT
  `e`.`EmployeeId` AS `EmployeeId`,
  `e`.`EmployeeCode` AS `EmployeeCode`,
  `e`.`EmployeeName` AS `EmployeeName`,
  `e`.`DateOfBirth` AS `DateOfBirth`,
  `e`.`Gender` AS `Gender`,
  `e`.`DepartmentId` AS `DepartmentId`,
  `d`.`DepartmentName` AS `DepartmentName`,
  `e`.`IdentityNumber` AS `IdentityNumber`,
  `e`.`IdentityDate` AS `IdentityDate`,
  `e`.`IdentityPlace` AS `IdentityPlace`,
  `e`.`EmployeePosition` AS `EmployeePosition`,
  `e`.`Address` AS `Address`,
  `e`.`BankAccountNumber` AS `BankAccountNumber`,
  `e`.`BankName` AS `BankName`,
  `e`.`BankBranchName` AS `BankBranchName`,
  `e`.`BankProvinceName` AS `BankProvinceName`,
  `e`.`PhoneNumber` AS `PhoneNumber`,
  `e`.`TelephoneNumber` AS `TelephoneNumber`,
  `e`.`Email` AS `Email`,
  `e`.`CreatedBy` AS `CreatedBy`,
  `e`.`CreatedDate` AS `CreatedDate`,
  `e`.`ModifiedBy` AS `ModifiedBy`,
  `e`.`ModifiedDate` AS `ModifiedDate`
FROM (`employee` `e`
  LEFT JOIN `department` `d`
    ON ((`e`.`DepartmentId` = `d`.`DepartmentId`)));

DELIMITER $$

--
-- Create procedure `Proc_GetEmployeesFilterPaging`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetEmployeesFilterPaging (IN EmployeeFilter varchar(255), IN PageIndex int, IN PageSize int, OUT TotalRecord int, OUT TotalPage int)
COMMENT 'Lấy danh sách nhân viên theo tiêu chí lọc/phân trang'
BEGIN
  SET @EmployeeFilter = (SELECT
      EmployeeFilter);

  IF PageSize > 0 THEN

    SELECT
      e.EmployeeId,
      e.EmployeeCode,
      e.EmployeeName,
      e.DateOfBirth,
      e.Gender,
      e.DepartmentId,
      e.DepartmentName,
      e.IdentityNumber,
      e.IdentityDate,
      e.IdentityPlace,
      e.EmployeePosition,
      e.Address,
      e.BankAccountNumber,
      e.BankName,
      e.BankBranchName,
      e.BankProvinceName,
      e.PhoneNumber,
      e.TelephoneNumber,
      e.Email,
      e.CreatedBy,
      e.CreatedDate,
      e.ModifiedBy,
      e.ModifiedDate
    FROM View_Employee e
    WHERE (
    @EmployeeFilter IS NULL
    OR @EmployeeFilter = ""
    OR (@EmployeeFilter IS NOT NULL
    AND (e.EmployeeCode LIKE CONCAT('%', @EmployeeFilter, '%')
    --     OR e.EmployeeName LIKE BINARY CONCAT('%', @EmployeeFilter, '%')
    OR e.EmployeeName LIKE CONCAT('%', @EmployeeFilter, '%')
    OR e.PhoneNumber LIKE CONCAT('%', @EmployeeFilter, '%')
    OR e.TelephoneNumber LIKE CONCAT('%', @EmployeeFilter, '%')
    )))
    --     AND ((@DepartmentId IS NOT NULL
    --     AND e.DepartmentId = @DepartmentId)
    --     OR @DepartmentId IS NULL)
    ORDER BY e.CreatedDate DESC
    LIMIT PageSize OFFSET PageIndex;

    SET TotalRecord = (SELECT
        COUNT(*)
      FROM View_Employee e
      WHERE (
      @EmployeeFilter IS NULL
      OR @EmployeeFilter = ""
      OR (@EmployeeFilter IS NOT NULL
      AND (e.EmployeeCode LIKE CONCAT('%', @EmployeeFilter, '%')
      --       OR e.EmployeeName LIKE BINARY CONCAT('%', @EmployeeFilter, '%')
      OR e.EmployeeName LIKE CONCAT('%', @EmployeeFilter, '%')
      OR e.PhoneNumber LIKE CONCAT('%', @EmployeeFilter, '%')
      OR e.TelephoneNumber LIKE CONCAT('%', @EmployeeFilter, '%')
      )))
      --       AND ((@DepartmentId IS NOT NULL
      --       AND e.DepartmentId = @DepartmentId)
      --       OR @DepartmentId IS NULL)
      ORDER BY e.CreatedDate DESC);



    /* Tổng số trang */
    SET TotalPage = CEILING(1.0 * TotalRecord / PageSize);
  /*
    SET @NumberRecordLastPage = TotalRecord % PageSize;

    IF @NumberRecordLastPage > 0 THEN
      SET TotalPage = TotalRecord DIV PageSize + 1;
    ELSE
      SET TotalPage = TotalRecord DIV PageSize;
    END IF;
  */
  END IF;
END
$$

--
-- Create procedure `Proc_GetEmployees`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetEmployees ()
COMMENT 'Lấy tất cả danh sách nhân viên'
BEGIN
  SELECT
    *
  FROM View_Employee
  ORDER BY CreatedDate DESC;
END
$$

--
-- Create procedure `Proc_GetEmployeeById`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetEmployeeById (IN EmployeeId char(36))
COMMENT 'Lấy thông tin nhân viên theo khóa chính'
BEGIN
  SELECT
    *
  FROM View_Employee e
  WHERE e.EmployeeId = EmployeeId LIMIT 1;
-- SELECT e.*, d.DepartmentName FROM Employee e LEFT JOIN Department d ON e.DepartmentId = d.DepartmentId WHERE e.EmployeeId = EmployeeId;
END
$$

--
-- Create function `Func_GetNewCodeNumber`
--
CREATE DEFINER = 'dev'@'%'
FUNCTION Func_GetNewCodeNumber (MaxNumber int, Len int)
RETURNS varchar(50) CHARSET utf8
BEGIN
  DECLARE newCodeNumber varchar(50) DEFAULT '';
  --   Tăng mã thêm 1 đơn vị
  SET newCodeNumber = CAST((MaxNumber + 1) AS char);
  --   Thêm số 0 đằng trước nếu chưa đủ độ dài (so với mã cũ)
  WHILE LENGTH(newCodeNumber) < Len DO
    SET newCodeNumber = CONCAT('0', newCodeNumber);
  END WHILE;

  RETURN newCodeNumber;
END
$$

--
-- Create function `Func_ExtractNumber`
--
CREATE DEFINER = 'dev'@'%'
FUNCTION Func_ExtractNumber (InputStr varchar(255))
RETURNS int(11)
COMMENT 'Lấy ra số từ xâu ký tự'
BEGIN
  DECLARE flag varchar(50);
  DECLARE findNumber varchar(50) DEFAULT '';
  DECLARE sChar varchar(1);
  DECLARE i integer DEFAULT 1;

  IF LENGTH(InputStr) > 0 THEN
    WHILE (i <= LENGTH(InputStr)) DO
      SET sChar = SUBSTRING(InputStr, i, 1);
      SET flag = FIND_IN_SET(sChar, '0,1,2,3,4,5,6,7,8,9');
      IF flag > 0 THEN
        SET findNumber = CONCAT(findNumber, sChar);
      END IF;
      SET i = i + 1;
    END WHILE;
    RETURN CAST(findNumber AS UNSIGNED);
  ELSE
    RETURN 0;
  END IF;
END
$$

--
-- Create procedure `Proc_GetNewEmployeeCode`
--
CREATE DEFINER = 'dev'@'%'
PROCEDURE Proc_GetNewEmployeeCode ()
COMMENT 'Lấy mã nhân viên mới'
BEGIN

  SET @MAX_NUMBER = (SELECT
      MAX(Func_ExtractNumber(e.EmployeeCode))
    FROM Employee e);
  SET @MAX_CODE = (SELECT
      e.EmployeeCode
    FROM Employee e
    WHERE Func_ExtractNumber(e.EmployeeCode) = @MAX_NUMBER);
  SET @PREFIX_CODE = "NV-";
  SET @NEW_CODE_NUMBER = (SELECT
      Func_GetNewCodeNumber(@MAX_NUMBER, LENGTH(@MAX_CODE) - LENGTH(@PREFIX_CODE)));

  SET @NEW_CODE = CONCAT(@PREFIX_CODE, @NEW_CODE_NUMBER);
  SELECT
    @NEW_CODE;
END
$$

--
-- Create procedure `Proc_GetCloneEmployeeById`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetCloneEmployeeById (IN EmployeeId varchar(36))
COMMENT 'Lấy bản sao thông tin nhân viên và thay mã nhân viên bằng mã mới'
BEGIN
  SET @MAX_NUMBER = (SELECT
      MAX(Func_ExtractNumber(e.EmployeeCode))
    FROM Employee e);
  SET @MAX_CODE = (SELECT
      e.EmployeeCode
    FROM Employee e
    WHERE Func_ExtractNumber(e.EmployeeCode) = @MAX_NUMBER);
  SET @PREFIX_CODE = "NV-";
  SET @NEW_CODE_NUMBER = (SELECT
      Func_GetNewCodeNumber(@MAX_NUMBER, LENGTH(@MAX_CODE) - LENGTH(@PREFIX_CODE)));

  SET @NEW_CODE = CONCAT(@PREFIX_CODE, @NEW_CODE_NUMBER);
  SELECT
    @NEW_CODE AS EmployeeCode,
    e.EmployeeName,
    e.DateOfBirth,
    e.Gender,
    e.DepartmentId,
    e.DepartmentName,
    e.IdentityNumber,
    e.IdentityDate,
    e.IdentityPlace,
    e.EmployeePosition,
    e.Address,
    e.BankAccountNumber,
    e.BankName,
    e.BankBranchName,
    e.BankProvinceName,
    e.PhoneNumber,
    e.TelephoneNumber,
    e.Email,
    e.CreatedBy,
    e.CreatedDate,
    e.ModifiedBy,
    e.ModifiedDate
  FROM View_Employee e
  WHERE e.EmployeeId = EmployeeId LIMIT 1;
END
$$

DELIMITER ;

-- 
-- Dumping data for table department
--
INSERT INTO department VALUES
('11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Phòng Đào tạo', 'Quo et consectetur. Omnis dolorem delectus quo corporis suscipit officiis; incidunt saepe vel nostrum ex et sed.', 'Lê Ngọc Mai', '2021-08-17 10:11:34', 'Lê Ngọc Mai', '2021-08-17 10:11:34'),
('142cb08f-7c31-21fa-8e90-67245e8b283e', 'Phòng Công nghệ', 'Praesentium excepturi architecto ipsum possimus. Dolore molestiae omnis nihil. Aliquid perspiciatis qui. Ea sed nam; accusantium ipsam ut. Soluta.', 'Phạm Gia Thành', '2021-08-17 10:11:34', 'Phạm Gia Thành', '2021-08-17 10:11:34'),
('17120d02-6ab5-3e43-18cb-66948daf6128', 'Phòng Nhân sự', 'Neque amet ut. Natus quis ratione. Itaque tempore ut. Enim impedit magnam. Quo consectetur temporibus! Excepturi debitis perspiciatis. Quis et expedita!', 'Đào Thùy Yến', '2021-08-17 10:11:34', 'Đào Thùy Yến', '2021-08-17 10:11:34'),
('469b3ece-744a-45d5-957d-e8c757976496', 'Phòng Marketing', 'Quam odit provident dolor. Natus error velit consequatur hic vero ut! Est nemo molestiae adipisci qui quia ipsam.', 'Nguyễn Thị  Hân', '2021-08-17 10:11:34', 'Nguyễn Thị  Hân', '2021-08-17 10:11:34'),
('4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Phòng Sản xuất', 'Qui tempora nisi similique laboriosam illum nesciunt. Unde similique omnis voluptatem sit nisi ipsum. Illum accusantium sit quia quidem; in et fuga.', 'Phạm Văn Hùng', '2021-08-17 10:11:34', 'Phạm Văn Hùng', '2021-08-17 10:11:34');

-- 
-- Dumping data for table employee
--
INSERT INTO employee VALUES
('12e12a5c-6e3a-503a-d71d-086412a8ea97', 'NV-0109', 'Nguyễn Vân Nga', '1997-08-05', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '004454600979', '2020-06-09', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Đông Mỹ, Huyện Thanh Trì, Thành phố Hà Nội', '56646559', 'BIDV', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0972667122', '0249179962', NULL, 'Nguyễn Thị Hân ', '2020-01-17 02:10:00', 'Phạm Gia Thành', '2020-01-17 02:10:00'),
('143e4110-751a-5474-1f80-de64d090a2c2', 'NV-0107', 'Nguyễn Gia Huy', '1999-02-16', 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '006661227423', '2018-12-31', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Quản lý', 'Phường Hàng Buồm, Quận Hoàn Kiếm, Thành phố Hà Nội', '85725682', 'Kỹ thương - Techcombank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0959110137', '0280851901', NULL, 'Nguyễn Thị Hân ', '2020-01-17 01:50:00', 'Nguyễn Thị Hân', '2020-01-17 01:50:00'),
('14aa1334-3d35-32c4-30c2-579daad24557', 'NV-0079', 'Nguyễn Văn Thành', NULL, 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '000691269386', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, NULL, '69856315', 'VietinBank', 'Chi nhánh Chương Dương', 'Hà Nội', NULL, '0286705533', NULL, 'Phạm Gia Thành', '2020-01-16 21:10:00', 'Phạm Gia Thành', '2020-01-16 21:10:00'),
('1518ced5-6993-37f8-6180-7ed9d1ea06ea', 'NV-0175', 'Dương Phương Duyên', '1991-08-01', 2, '142cb08f-7c31-21fa-8e90-67245e8b283e', '004427466478', '2020-02-27', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Trưởng nhóm', 'Phường Phúc Xá, Quận Ba Đình, Thành phố Hà Nội', '11092896', 'Á Châu (ACB)', 'Chi nhánh Thăng Long', 'Hà Nội', '0822841632', '0240881445', 'Ackerman@gmail.com', 'Nguyễn Thị Hân ', '2020-01-17 13:10:00', 'Phạm Gia Thành', '2020-01-17 13:10:00'),
('156bb711-53c6-12ee-5d80-7ed9d1ea06ea', 'NV-0148', 'Đỗ Hoàng Nghĩa', '1956-09-02', 1, '142cb08f-7c31-21fa-8e90-67245e8b283e', '005491391719', '2016-01-10', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'Xã Hòa Trị, Huyện Phú Hoà, Tỉnh Phú Yên', '62129818', 'VietinBank', NULL, 'Hà Nội', '0815305769', NULL, NULL, 'Phạm Gia Thành', '2020-01-17 08:40:00', 'Phạm Gia Thành', '2020-01-17 08:40:00'),
('15f7fc94-6dce-3bce-2680-de64d090a2c2', 'NV-0200', 'Trương Phương Oanh', '1962-09-16', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '005033003753', '2016-01-08', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'Xã Hà Lương, Huyện Hạ Hoà, Tỉnh Phú Thọ', '40101464', NULL, NULL, NULL, '0398982087', NULL, NULL, 'Phạm Gia Thành', '2020-01-17 17:20:00', 'Phạm Gia Thành', '2020-01-17 17:20:00'),
('1737c16a-1277-1be3-3bc2-579daad24557', 'NV-0161', 'Trương Bảo Chính', '1970-12-10', 0, '469b3ece-744a-45d5-957d-e8c757976496', '004729105860', '2017-04-24', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'ã Đức Liên, Huyện Vũ Quang, Tỉnh Hà Tĩnh', '33809128', 'Đông Á - Dong A Bank', 'Chi nhánh Hà Thành', 'Hà Nội', '0901678385', '0288702415', NULL, 'Phạm Gia Thành', '2020-01-17 10:50:00', 'Phạm Gia Thành', '2020-01-17 10:50:00'),
('17872e95-3d24-6d1a-32c2-579daad24557', 'NV-0090', 'Đoàn Đức Nghĩa', '2002-12-08', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '001810775825', '2017-09-28', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Quản lý', 'Xã Đông Hải, Huyện Tiên Yên, Tỉnh Quảng Ninh', '03322600', 'MBBank', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', '0989847849', '0287420307', NULL, 'Nguyễn Thị Hân ', '2020-01-16 23:00:00', 'Nguyễn Thị Hân', '2020-01-16 23:00:00'),
('1906737f-3aed-5704-1777-d9ebc53aac3d', 'NV-0074', 'Nguyễn Trung Bách', '1967-04-16', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '002658295113', '2019-11-27', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'ã Trường Thịnh, Huyện Ứng Hòa, Thành phố Hà Nội', '97918377', 'Đông Á - Dong A Bank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0399410863', '0240706527', NULL, 'Nguyễn Thị Hân ', '2020-01-16 20:20:00', 'Nguyễn Thị Hân', '2020-01-16 20:20:00'),
('19256041-7623-2834-6df6-423b4e874d0f', 'NV-0087', 'Nguyễn Thùy Ánh', '1951-02-16', 1, '142cb08f-7c31-21fa-8e90-67245e8b283e', '003575948397', '2017-10-27', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Phong Dụ, Huyện Tiên Yên, Tỉnh Quảng Ninh', '09256964', 'VietinBank', NULL, 'Hà Nội', '0972629953', NULL, NULL, 'Nguyễn Thị Hân ', '2020-01-16 22:30:00', 'Phạm Gia Thành', '2020-01-16 22:30:00'),
('192b3b9d-5e60-3b13-5b80-7ed9d1ea06ea', 'NV-0136', 'Triệu Khánh Duyên', NULL, 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '008400168459', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', NULL, '94598459', 'BIDV', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', NULL, '0240612661', NULL, 'Nguyễn Thị Hân ', '2020-01-17 06:40:00', 'Phạm Gia Thành', '2020-01-17 06:40:00'),
('199db575-444b-2633-6880-7ed9d1ea06ea', 'NV-0243', 'Đào Khánh Oanh', '2000-01-12', 1, '142cb08f-7c31-21fa-8e90-67245e8b283e', '004155135587', '2016-01-04', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Phường Ngã Tư Sở, Quận Đống Đa, Thành phố Hà Nội', '61648146', 'Sacombank', 'Chi nhánh Đông Anh', 'Hà Nội', '0843573160', '0246797068', NULL, 'Phạm Gia Thành', '2020-01-18 00:30:00', 'Phạm Gia Thành', '2021-09-13 18:28:26'),
('1b05fdba-145b-7ab0-8d41-c1ec321fe728', 'NV-0172', 'Đường Anh Trung', '1974-10-23', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '004723026270', '2016-01-02', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Nậm Giải, Huyện Quế Phong, Tỉnh Nghệ An', '89923893', 'BIDV', 'Chi nhánh Hà Thành', 'Hà Nội', '0384571665', '0241420034', 'Eddy8@gmail.com', 'Nguyễn Thị Hân ', '2020-01-17 12:40:00', 'Phạm Gia Thành', '2020-01-17 12:40:00'),
('1b972dfb-67eb-5f25-39c2-579daad24557', 'NV-0149', 'Trần Anh Hoàng', '1959-04-25', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '008115592950', '2019-07-11', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Phường Long Hưng, Thị Xã Tân Châu, Tỉnh An Giang', '78737036', 'Vietcom Bank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0869998724', '0244155798', NULL, 'Nguyễn Thị Hân ', '2020-01-17 08:50:00', 'Nguyễn Thị Hân', '2020-01-17 08:50:00'),
('1d21993b-3612-2485-1035-60b3ebf808a9', 'NV-0207', 'Trần Thanh Chính', NULL, 2, '142cb08f-7c31-21fa-8e90-67245e8b283e', '002100768246', NULL, 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', NULL, '23583347', 'Sacombank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', NULL, '0247089442', NULL, 'Nguyễn Thị Hân ', '2020-01-17 18:30:00', 'Phạm Gia Thành', '2020-01-17 18:30:00'),
('1dc115ba-6479-33a7-44c2-579daad24557', 'NV-0227', 'Lê Thị Phương Mai', '1995-04-01', 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '002612873966', '2016-01-06', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Bản Bo, Huyện Tam Đường, Tỉnh Lai Châu', '51994866', 'VietinBank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0829931506', '0246683140', 'Lowry1@gmail.com', 'Nguyễn Thị Hân', '2020-01-17 21:50:00', 'Phạm Gia Thành', '2021-08-27 21:08:32'),
('1f88699a-3e19-718a-d81d-086412a8ea97', 'NV-0112', 'Đỗ Hoàng Chí', '1957-10-01', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '003473505017', '2016-02-24', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng phòng', 'Xã Mỹ Thành, Huyện Lạc Sơn, Tỉnh Hoà Bình', '01781922', 'MBBank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0852282616', '0282715241', NULL, 'Nguyễn Thị Hân ', '2020-01-17 02:40:00', 'Phạm Gia Thành', '2020-01-17 02:40:00'),
('1fbf8e6f-17d3-6a04-2180-de64d090a2c2', 'NV-0133', 'Lê Gia Long', '1964-02-08', 1, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '007102229592', '2020-12-02', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Thực tập sinh', 'Phường Thượng Thanh, Quận Long Biên, Thành phố Hà Nội', '70163897', 'VietinBank', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', '0925755477', '0289620347', NULL, 'Phạm Gia Thành', '2020-01-17 06:10:00', 'Nguyễn Thị Hân', '2020-01-17 06:10:00'),
('201b9639-5997-303c-5880-7ed9d1ea06ea', 'NV-0101', 'Đỗ Văn Hòa', '1978-01-30', 2, '142cb08f-7c31-21fa-8e90-67245e8b283e', '001663174247', '2019-05-02', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Bình Thanh, Huyện Kiến Xương, Tỉnh Thái Bình', '76536683', 'Vietcom Bank', NULL, 'Hà Nội', '0339164421', NULL, NULL, 'Phạm Gia Thành', '2020-01-17 00:50:00', 'Nguyễn Thị Hân', '2020-01-17 00:50:00'),
('2107e2a5-49f8-237b-5780-7ed9d1ea06ea', 'NV-0095', 'Nguyễn Ngọc Anh', NULL, 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '000088556643', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, NULL, '97661979', 'Á Châu (ACB)', 'Chi nhánh Hà Đông', 'Hà Nội', NULL, '0284886303', NULL, 'Nguyễn Thị Hân ', '2020-01-16 23:50:00', 'Nguyễn Thị Hân', '2020-01-16 23:50:00'),
('212a5f62-4eb8-203c-4035-0028ed526dd0', 'NV-0077', 'Nguyễn Thùy Mai', '1997-01-16', 0, '469b3ece-744a-45d5-957d-e8c757976496', '001302217873', '2016-03-31', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'Xã Ân Phong, Huyện Hoài Ân, Tỉnh Bình Định', '36359403', 'VietinBank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0852664464', '0244504312', NULL, 'Phạm Gia Thành', '2020-01-16 20:50:00', 'Phạm Gia Thành', '2020-01-16 20:50:00'),
('214977d8-66ff-5762-1335-60b3ebf808a9', 'NV-0231', 'Ngô Thanh Hiền', NULL, 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '006615772149', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng phòng', NULL, '18028422', 'VP Bank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', NULL, '0281508456', NULL, 'Phạm Gia Thành', '2020-01-17 22:30:00', 'Nguyễn Thị Hân', '2020-01-17 22:30:00'),
('22732821-2015-1da3-4335-0028ed526dd0', 'NV-0117', 'Trần Thảo Nga', '2000-08-06', 0, '469b3ece-744a-45d5-957d-e8c757976496', '004231526261', '2016-01-11', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Hải Ninh, Huyện Quảng Ninh, Tỉnh Quảng Bình', '82712087', 'HD Bank', NULL, 'Hà Nội', '0956592147', NULL, 'Minh.Snyder69@yahoo.com', 'Nguyễn Thị Hân ', '2020-01-17 03:30:00', 'Nguyễn Thị Hân', '2020-01-17 03:30:00'),
('22bba567-6206-6bf1-0c35-60b3ebf808a9', 'NV-0178', 'Nguyễn Gia Chính', '1962-08-17', 0, '469b3ece-744a-45d5-957d-e8c757976496', '001197149682', '2018-04-08', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Nguyễn An Ninh, Thành phố Vũng Tàu, Tỉnh Bà Rịa - Vũng Tàu', '17256554', 'Việt Á - VietABank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0874201481', '0241495995', 'KermitBullard@gmail.com', 'Phạm Gia Thành', '2020-01-17 13:40:00', 'Phạm Gia Thành', '2020-01-17 13:40:00'),
('22df58b0-55d2-6108-2480-de64d090a2c2', 'NV-0166', 'Nguyễn Thảo Mai', '1962-11-06', 2, '142cb08f-7c31-21fa-8e90-67245e8b283e', '009425986609', '2018-06-06', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'ã Hồng Lộc, Huyện Lộc Hà, Tỉnh Hà Tĩnh', '37825825', 'VietinBank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0958397711', '0244302989', NULL, 'Phạm Gia Thành', '2020-01-17 11:40:00', 'Nguyễn Thị Hân', '2020-01-17 11:40:00'),
('231ea7f8-1468-6e29-5235-0028ed526dd0', 'NV-0233', 'Trần Văn Nghĩa', '1951-01-05', 1, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '008706949035', '2017-03-16', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'ường Trần Phú, Thành phố Bắc Giang, Tỉnh Bắc Giang', '87737355', 'Vietcom Bank', 'Chi nhánh Hà Thành', 'Hà Nội', '0925829099', '0281971496', NULL, 'Phạm Gia Thành', '2020-01-17 22:50:00', 'Nguyễn Thị Hân', '2020-01-17 22:50:00'),
('233d36ab-4bd0-431e-78f6-423b4e874d0f', 'NV-0196', 'Lê Thảo Duyên', '1991-01-02', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '004830275148', '2016-02-22', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'Xã Thái Hòa, Huyện Bình Giang, Tỉnh Hải Dương', '29791232', 'Vietcom Bank', 'Chi nhánh Chương Dương', 'Hà Nội', '0918049817', '0289376477', NULL, 'Phạm Gia Thành', '2020-01-17 16:40:00', 'Nguyễn Thị Hân', '2020-01-17 16:40:00'),
('234865cb-5d80-7244-70f6-423b4e874d0f', 'NV-0123', 'Đoàn Vân Diễm', '1994-03-28', 0, '469b3ece-744a-45d5-957d-e8c757976496', '008815778122', '2017-11-23', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Thực tập sinh', 'ã Long Xuyên, Huyện Phúc Thọ, Thành phố Hà Nội', '94672003', 'Vietcom Bank', 'Chi nhánh Đông Anh', 'Hà Nội', '0890255302', '0245681784', NULL, 'Nguyễn Thị Hân ', '2020-01-17 04:30:00', 'Nguyễn Thị Hân', '2020-01-17 04:30:00'),
('237092c3-5684-7bb6-0a35-60b3ebf808a9', 'NV-0153', 'Phan Khánh Khang', '1955-07-10', 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '007577613832', '2017-07-11', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Vĩnh An, Huyện Tây Sơn, Tỉnh Bình Định', '85894027', NULL, 'Chi nhánh Chương Dương', NULL, '0333264286', '0284603794', NULL, 'Phạm Gia Thành', '2020-01-17 09:30:00', 'Phạm Gia Thành', '2020-01-17 09:30:00'),
('244b1b16-56fc-1f92-73f6-423b4e874d0f', 'NV-0144', 'Đường Thanh Khôi', '1992-02-25', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '005683471352', '2017-11-26', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Liễu Giai, Quận Ba Đình, Thành phố Hà Nội', '26527046', 'Việt Á - VietABank', 'Chi nhánh Đông Anh', 'Hà Nội', '0962696415', '0280996896', NULL, 'Phạm Gia Thành', '2020-01-17 08:00:00', 'Nguyễn Thị Hân', '2020-01-17 08:00:00'),
('255b28ba-2177-6baf-0835-60b3ebf808a9', 'NV-0124', 'Ngô Kim Bình', '1989-03-30', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '008508565746', '2016-03-27', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Xã Phú Lộc, Huyện Nho Quan, Tỉnh Ninh Bình', '44644018', 'BIDV', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0995595514', '0287218899', NULL, 'Phạm Gia Thành', '2020-01-17 04:40:00', 'Phạm Gia Thành', '2020-01-17 04:40:00'),
('26942456-25a8-5ec2-8b41-c1ec321fe728', 'NV-0143', 'Trương Phương Uyên', '1963-08-15', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '005798842749', '2016-03-30', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', '� Hà Vinh, Huyện Hà Trung, Tỉnh Thanh Hóa', '21452186', 'BIDV', 'Chi nhánh Thăng Long', 'Hà Nội', '0905093959', '0242233073', NULL, 'Nguyễn Thị Hân ', '2020-01-17 07:50:00', 'Phạm Gia Thành', '2020-01-17 07:50:00'),
('27e60da2-385e-6804-8441-c1ec321fe728', 'NV-0071', 'Nguyễn Thanh Bắc', '1988-11-18', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '002085103075', '2016-01-02', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Xã Công Bằng, Huyện Pác Nặm, Tỉnh Bắc Kạn', '34968970', 'Agribank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0343169243', '0288891965', NULL, 'Phạm Gia Thành', '2020-01-16 19:50:00', 'Phạm Gia Thành', '2020-01-16 19:50:00'),
('285d6b44-3b0c-4697-e01d-086412a8ea97', 'NV-0238', 'Dương Phương Hương', '1994-05-20', 1, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '008098489576', '2018-08-04', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Kim Cúc, Huyện Bảo Lạc, Tỉnh Cao Bằng', '10626654', 'Vietcom Bank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0351419058', '0240887189', NULL, 'Nguyễn Thị Hân ', '2020-01-17 23:40:00', 'Nguyễn Thị Hân', '2020-01-17 23:40:00'),
('28692b18-2ec1-574b-6780-7ed9d1ea06ea', 'NV-0229', 'Hồ Văn Bắc', '1951-01-01', 2, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '003377530071', '2016-03-11', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Phường Dịch Vọng, Quận Cầu Giấy, Thành phố Hà Nội', '29810696', 'VP Bank', NULL, 'Hà Nội', '0972022015', NULL, NULL, 'Nguyễn Thị Hân ', '2020-01-17 22:10:00', 'Nguyễn Thị Hân', '2020-01-17 22:10:00'),
('2872c174-68d3-29c1-4935-0028ed526dd0', 'NV-0159', 'Lê Thùy Quỳnh', '1957-05-27', 1, '142cb08f-7c31-21fa-8e90-67245e8b283e', '003708944209', '2016-01-18', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Đắk Wil, Huyện Cư Jút, Tỉnh Đắk Nông', '81545420', 'Á Châu (ACB)', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0901637431', '0280508565', NULL, 'Nguyễn Thị Hân ', '2020-01-17 10:30:00', 'Nguyễn Thị Hân', '2020-01-17 10:30:00'),
('28a16581-1fd1-546b-1677-d9ebc53aac3d', 'NV-0070', 'Nguyễn Trung Chí', '1951-03-03', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '000026402484', '2020-09-26', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Xã Cư Ni, Huyện Ea Kar, Tỉnh Đắk Lắk', '46345460', 'Việt Á - VietABank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0381898384', '0243552121', 'Riggs76@gmail.com', 'Nguyễn Thị Hân ', '2020-01-16 19:40:00', 'Nguyễn Thị Hân', '2020-01-16 19:40:00'),
('2bd927cf-7faf-452e-4535-0028ed526dd0', 'NV-0135', 'Hồ Phương Nga', NULL, 2, '142cb08f-7c31-21fa-8e90-67245e8b283e', '001342179803', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', NULL, '24548280', 'BIDV', 'Chi nhánh Hà Đông', 'Hà Nội', NULL, '0289884367', NULL, 'Phạm Gia Thành', '2020-01-17 06:30:00', 'Phạm Gia Thành', '2020-01-17 06:30:00'),
('2c06d3cb-7ef7-4462-5e80-7ed9d1ea06ea', 'NV-0158', 'Trương Hoàng Chí', '1967-12-07', 1, '469b3ece-744a-45d5-957d-e8c757976496', '007261944761', '2020-11-15', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', '� Tân Dân, Huyện Đầm Dơi, Tỉnh Cà Mau', '20229914', NULL, 'Chi nhánh Nam Từ Liêm', NULL, '0916862464', '0249727824', NULL, 'Phạm Gia Thành', '2020-01-17 10:20:00', 'Phạm Gia Thành', '2020-01-17 10:20:00'),
('2c380a42-1611-28c2-3ac2-579daad24557', 'NV-0151', 'Nguyễn Thị Hương', '1991-04-03', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '001621891057', '2021-02-01', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Trưởng phòng', 'Xã An Thượng, Huyện Hoài Đức, Thành phố Hà Nội', '92059276', 'BIDV', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0364338997', '0285262611', 'Millard.Rains458@gmail.com', 'Phạm Gia Thành', '2020-01-17 09:10:00', 'Phạm Gia Thành', '2020-01-17 09:10:00'),
('2d3ae261-2b44-7713-41c2-579daad24557', 'NV-0210', 'Dương Kim Hùng', '1951-04-01', 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '000122674564', '2016-01-24', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', '� Ea Wy, Huyện Ea H''leo, Tỉnh Đắk Lắk', '03495706', 'Tiên Phong - TPBank', 'Chi nhánh Đông Anh', 'Hà Nội', '0884710482', '0281180071', NULL, 'Phạm Gia Thành', '2020-01-17 19:00:00', 'Nguyễn Thị Hân', '2020-01-17 19:00:00'),
('2efc0ff3-37c0-286f-bbd2-89b22d10517e', 'NV-0067', 'Trần Thùy Anh', '1991-03-15', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '008911549398', '2016-01-02', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Trưởng phòng', 'Phường Kim Mã, Quận Ba Đình, Thành phố Hà Nội', '99920357', 'Á Châu (ACB)', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', '0847317802', '0288999356', NULL, 'Nguyễn Thị Hân ', '2020-01-16 19:10:00', 'Nguyễn Thị Hân', '2020-01-16 19:10:00'),
('2f25e35e-15fb-71e4-4e35-0028ed526dd0', 'NV-0209', 'Triệu Thanh Chí', '1993-04-25', 2, '469b3ece-744a-45d5-957d-e8c757976496', '002399953098', '2017-11-25', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Xã Sơn Hà, Huyện Bảo Thắng, Tỉnh Lào Cai', '06224274', 'BIDV', 'Chi nhánh Hà Thành', 'Hà Nội', '0393542995', '0245412103', NULL, 'Phạm Gia Thành', '2020-01-17 18:50:00', 'Nguyễn Thị Hân', '2020-01-17 18:50:00'),
('2fde0921-432c-64c5-0935-60b3ebf808a9', 'NV-0138', 'Hoàng Khánh Thành', '1952-02-25', 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '005883686149', '2016-03-08', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Tắc Vân, Thành phố Cà Mau, Tỉnh Cà Mau', '45416868', 'VietinBank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0940756126', '0243743674', NULL, 'Nguyễn Thị Hân ', '2020-01-17 07:00:00', 'Nguyễn Thị Hân', '2020-01-17 07:00:00'),
('31ae1818-7baf-1872-1e77-d9ebc53aac3d', 'NV-0128', 'Lê Bảo Hùng', '1981-06-16', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '002560390816', '2019-10-31', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, '� Hoả Lựu, Thành phố Vị Thanh, Tỉnh Hậu Giang', '77748479', 'Vietcom Bank', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', '0826952814', '0241814912', NULL, 'Phạm Gia Thành', '2020-01-17 05:20:00', 'Nguyễn Thị Hân', '2020-01-17 05:20:00'),
('322105dd-142f-392d-2fc2-579daad24557', 'NV-0073', 'Ngô Mai Oanh', '1990-03-18', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '006197426424', '2016-09-18', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Giám đốc', 'Phường Thượng Đình, Quận Thanh Xuân, Thành phố Hà Nội', '58537594', 'Vietcom Bank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0358818041', '0248989258', 'Elia_L_Bunnell86@gmail.com', 'Phạm Gia Thành', '2020-01-16 20:10:00', 'Nguyễn Thị Hân', '2020-01-16 20:10:00'),
('324ac33a-77c5-13a5-0535-60b3ebf808a9', 'NV-0098', 'Phạm Đức Bách', '1999-04-10', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '005146248864', '2016-01-04', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Xã Hướng Phùng, Huyện Hướng Hóa, Tỉnh Quảng Trị', '60880418', 'BIDV', 'Chi nhánh Hà Thành', 'Hà Nội', '0324873602', '0289220127', 'Adrien_Snell193@gmail.com', 'Nguyễn Thị Hân ', '2020-01-17 00:20:00', 'Phạm Gia Thành', '2020-01-17 00:20:00'),
('329b5332-34e3-1ae4-6ef6-423b4e874d0f', 'NV-0100', 'Nguyễn Bảo Bắc', '1992-05-30', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '000509716136', '2019-10-09', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Tân Xã, Huyện Thạch Thất, Thành phố Hà Nội', '40590667', 'VietinBank', 'Chi nhánh Đông Anh', 'Hà Nội', '0920088857', '0243386594', NULL, 'Phạm Gia Thành', '2020-01-17 00:40:00', 'Phạm Gia Thành', '2020-01-17 00:40:00'),
('32d33559-61a5-4afd-d91d-086412a8ea97', 'NV-0120', 'Đỗ Minh Khang', '1991-01-02', 1, '469b3ece-744a-45d5-957d-e8c757976496', '005969511677', '2019-12-18', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Quản lý', 'Thị trấn Hưng Nhân, Huyện Hưng Hà, Tỉnh Thái Bình', '71839223', NULL, 'Chi nhánh Hai Bà Trưng', NULL, '0920103145', '0246215854', 'Swanson@gmail.com', 'Phạm Gia Thành', '2020-01-17 04:00:00', 'Nguyễn Thị Hân', '2020-01-17 04:00:00'),
('32e3be81-3548-6f8f-6380-7ed9d1ea06ea', 'NV-0205', 'Dương Kim Hùng', '1951-02-17', 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '008140341885', '2016-05-31', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Phường Khương Mai, Quận Thanh Xuân, Thành phố Hà Nội', '58098339', 'BIDV', NULL, 'Hà Nội', '0824718716', NULL, 'Lauryn.Abel889@yahoo.com', 'Nguyễn Thị Hân ', '2020-01-17 18:10:00', 'Phạm Gia Thành', '2020-01-17 18:10:00'),
('33589ecb-33ac-28c7-9241-c1ec321fe728', 'NV-0232', 'Trần Thị Trang', '1998-01-26', 1, '142cb08f-7c31-21fa-8e90-67245e8b283e', '002713914521', '2017-01-22', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'Phường Nguyễn Trung Trực, Quận Ba Đình, Thành phố Hà Nội', '58181160', 'Á Châu (ACB)', 'Chi nhánh Hà Đông', 'Hà Nội', '0343973765', '0280178478', NULL, 'Phạm Gia Thành', '2020-01-17 22:40:00', 'Nguyễn Thị Hân', '2020-01-17 22:40:00'),
('33ec4fea-4c03-3191-3ec2-579daad24557', 'NV-0180', 'Hoàng Thanh Uyên', '1960-06-08', 1, '469b3ece-744a-45d5-957d-e8c757976496', '001881470408', '2016-01-09', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Thực tập sinh', 'ã Ma Quai, Huyện Sìn Hồ, Tỉnh Lai Châu', '37125796', 'Vietcom Bank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0364143077', '0282780781', NULL, 'Phạm Gia Thành', '2020-01-17 14:00:00', 'Nguyễn Thị Hân', '2020-01-17 14:00:00'),
('34d0e3b5-6d5f-1fd7-0635-60b3ebf808a9', 'NV-0105', 'Phan Mai Nhung', '1991-06-15', 0, '469b3ece-744a-45d5-957d-e8c757976496', '005202735759', '2016-01-18', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Phường Trúc Bạch, Quận Ba Đình, Thành phố Hà Nội', '98352573', NULL, 'Chi nhánh Đông Anh', NULL, '0889167306', '0247059104', NULL, 'Phạm Gia Thành', '2020-01-17 01:30:00', 'Nguyễn Thị Hân', '2020-01-17 01:30:00'),
('350cf027-3245-532d-bcd2-89b22d10517e', 'NV-0082', 'Đỗ Thảo Thảo', '1993-08-04', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '007168834329', '2017-02-23', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Thực tập sinh', 'Phường Đội Cấn, Quận Ba Đình, Thành phố Hà Nội', '60711364', 'VietinBank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0914999494', '0284819105', NULL, 'Phạm Gia Thành', '2020-01-16 21:40:00', 'Phạm Gia Thành', '2020-01-16 21:40:00'),
('35ec2e7b-17b3-1b63-6080-7ed9d1ea06ea', 'NV-0168', 'Nguyễn Vân Thảo', '1991-12-26', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '005423826660', '2019-09-09', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Quản lý', 'Xã Liên Ninh, Huyện Thanh Trì, Thành phố Hà Nội', '97535296', 'VP Bank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0863431365', '0240822370', 'Braswell@gmail.com', 'Nguyễn Thị Hân ', '2020-01-17 12:00:00', 'Phạm Gia Thành', '2020-01-17 12:00:00'),
('360bd1e4-7bbf-3971-d41d-086412a8ea97', 'NV-0072', 'Trương Văn Chí', '1966-11-20', 1, '142cb08f-7c31-21fa-8e90-67245e8b283e', '005671921873', '2020-09-21', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Xã Liên Sơn, Huyện Kim Bảng, Tỉnh Hà Nam', '76814016', 'Tiên Phong - TPBank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0815239278', '0247418905', NULL, 'Nguyễn Thị Hân ', '2020-01-16 20:00:00', 'Phạm Gia Thành', '2020-01-16 20:00:00'),
('383760d5-6851-218b-4835-0028ed526dd0', 'NV-0156', 'Nguyễn Thùy Hân', '1995-03-06', 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '002364017000', '2016-01-05', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Trung Môn, Huyện Yên Sơn, Tỉnh Tuyên Quang', '62863377', 'VietinBank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0819170679', '0249611195', NULL, 'Phạm Gia Thành', '2020-01-17 10:00:00', 'Phạm Gia Thành', '2020-01-17 10:00:00'),
('38dc720e-654a-29d5-34c2-579daad24557', 'NV-0097', 'Lương Mai Ánh', '1961-11-04', 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '000454300318', '2021-06-14', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Xã Bản Giang, Huyện Tam Đường, Tỉnh Lai Châu', '55299518', 'VietinBank', 'Chi nhánh Chương Dương', 'Hà Nội', '0838574917', '0282022178', NULL, 'Phạm Gia Thành', '2020-01-17 00:10:00', 'Nguyễn Thị Hân', '2020-01-17 00:10:00'),
('395826c8-15a0-31f9-5980-7ed9d1ea06ea', 'NV-0118', 'Đỗ Minh Hòa', '1993-03-23', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '005505481819', '2016-11-24', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', 'Phường Nguyễn Trung Trực, Quận Ba Đình, Thành phố Hà Nội', '93946940', 'BIDV', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', '0921769265', '0249611074', NULL, 'Nguyễn Thị Hân ', '2020-01-17 03:40:00', 'Phạm Gia Thành', '2020-01-17 03:40:00'),
('395fb299-3c5f-46fe-8841-c1ec321fe728', 'NV-0119', 'Trương Vân Uyên', '1951-07-11', 0, '469b3ece-744a-45d5-957d-e8c757976496', '004603794021', '2016-04-29', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'ã Hội Sơn, Huyện Anh Sơn, Tỉnh Nghệ An', '73910471', 'Kỹ thương - Techcombank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0920191135', '0241914449', NULL, 'Nguyễn Thị Hân ', '2020-01-17 03:50:00', 'Phạm Gia Thành', '2020-01-17 03:50:00'),
('39f3c493-4680-145e-42c2-579daad24557', 'NV-0216', 'Nguyễn Văn Hùng', '1987-01-06', 2, '469b3ece-744a-45d5-957d-e8c757976496', '003814070530', '2019-12-22', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', '� Ea Drông, Thị Xã Buôn Hồ, Tỉnh Đắk Lắk', '18363684', 'BIDV', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0893687624', '0243828131', NULL, 'Phạm Gia Thành', '2020-01-17 20:00:00', 'Phạm Gia Thành', '2020-01-17 20:00:00'),
('3a425a4d-6066-116b-6bf6-423b4e874d0f', 'NV-0069', 'Trịnh Thanh Bách', '1998-06-20', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '001654076962', '2016-09-28', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Phố Huế, Quận Hai Bà Trưng, Thành phố Hà Nội', '16527608', 'BIDV', 'Chi nhánh Chương Dương', 'Hà Nội', '0971272763', '0285421915', NULL, 'Nguyễn Thị Hân ', '2020-01-16 19:30:00', 'Nguyễn Thị Hân', '2020-01-16 19:30:00'),
('3abffc51-2a43-18c6-6cf6-423b4e874d0f', 'NV-0075', 'Vũ Khánh Nguyệt', '1973-03-14', 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '001708014036', '2021-05-21', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Hang Kia, Huyện Mai Châu, Tỉnh Hoà Bình', '76743080', 'Sacombank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0987598705', '0240587417', 'Tad.Shumaker37@gmail.com', 'Nguyễn Thị Hân ', '2020-01-16 20:30:00', 'Phạm Gia Thành', '2020-01-16 20:30:00'),
('3ac85d96-49eb-7b1d-1135-60b3ebf808a9', 'NV-0215', 'Đỗ Phương Thảo', '1974-09-28', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '006345288381', '2017-12-22', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Đức Quang, Huyện Hạ Lang, Tỉnh Cao Bằng', '37050869', 'VietinBank', NULL, 'Hà Nội', '0328306659', NULL, NULL, 'Nguyễn Thị Hân ', '2020-01-17 19:50:00', 'Nguyễn Thị Hân', '2020-01-17 19:50:00'),
('3b668e3c-742f-4876-8e41-c1ec321fe728', 'NV-0188', 'Phạm Bảo Nghĩa', '1951-02-24', 1, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '002450359450', '2018-01-14', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'ường Tân Phú, Quận Cái Răng, Thành phố Cần Thơ', '91268916', 'BIDV', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0895271000', '0289206557', 'Eliseo_XAmes565@gmail.com', 'Nguyễn Thị Hân ', '2020-01-17 15:20:00', 'Nguyễn Thị Hân', '2020-01-17 15:20:00'),
('3b9ddf67-2552-6683-5a80-7ed9d1ea06ea', 'NV-0125', 'Trần Mai Mai', '1991-01-17', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '008862732857', '2016-01-17', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Trưởng phòng', 'Phường Phúc Lợi, Quận Long Biên, Thành phố Hà Nội', '13326779', 'MBBank', 'Chi nhánh Đông Anh', 'Hà Nội', '0847815315', '0244531800', 'scixs3777@gmail.com', 'Phạm Gia Thành', '2020-01-17 04:50:00', 'Phạm Gia Thành', '2020-01-17 04:50:00'),
('3cb58bb5-2fd7-6c15-8741-c1ec321fe728', 'NV-0103', 'Trần Vân Ngân', '2003-08-08', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '000693789620', '2016-01-02', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Phường Cự Khối, Quận Long Biên, Thành phố Hà Nội', '24658822', 'Vietcom Bank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0352829755', '0284257332', NULL, 'Nguyễn Thị Hân ', '2020-01-17 01:10:00', 'Nguyễn Thị Hân', '2020-01-17 01:10:00'),
('3cc7be2d-6406-4b95-3cc2-579daad24557', 'NV-0173', 'Nguyễn Minh Bảo', NULL, 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '008220718385', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', NULL, '01082552', 'Agribank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', NULL, '0280039324', NULL, 'Phạm Gia Thành', '2020-01-17 12:50:00', 'Phạm Gia Thành', '2020-01-17 12:50:00'),
('3d1266d8-49d7-3605-2477-d9ebc53aac3d', 'NV-0174', 'Bùi Văn Thành', '1951-01-18', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '003090620562', '2018-08-27', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Tân An, Thị Xã Nghĩa Lộ, Tỉnh Yên Bái', '80323019', 'Á Châu (ACB)', 'Chi nhánh Thăng Long', 'Hà Nội', '0355042693', '0288488594', NULL, 'Phạm Gia Thành', '2020-01-17 13:00:00', 'Nguyễn Thị Hân', '2020-01-17 13:00:00'),
('3d18d4c2-2f39-3dce-d61d-086412a8ea97', 'NV-0088', 'Nguyễn Khánh Hoàng', '1953-10-29', 1, '469b3ece-744a-45d5-957d-e8c757976496', '004463968074', '2016-04-23', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Phú Hòa, Huyện Định Quán, Tỉnh Đồng Nai', '63087529', 'Đông Á - Dong A Bank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0327628775', '0283107800', NULL, 'Phạm Gia Thành', '2020-01-16 22:40:00', 'Phạm Gia Thành', '2020-01-16 22:40:00'),
('3f7028bf-3771-75c5-2380-de64d090a2c2', 'NV-0157', 'Ngô Văn Hùng', '2002-07-29', 2, '142cb08f-7c31-21fa-8e90-67245e8b283e', '006735951797', '2021-02-20', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Giám đốc', 'Xã Quỳnh Hội, Huyện Quỳnh Phụ, Tỉnh Thái Bình', '61794727', 'VP Bank', 'Chi nhánh Chương Dương', 'Hà Nội', '0966886747', '0246557351', NULL, 'Phạm Gia Thành', '2020-01-17 10:10:00', 'Phạm Gia Thành', '2020-01-17 10:10:00'),
('40160288-72cf-185c-c8d2-89b22d10517e', 'NV-0241', 'Đỗ Thanh Tâm', '2002-01-16', 1, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '000874168551', '2016-01-29', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Minh Quán, Huyện Trấn Yên, Tỉnh Yên Bái', '81669231', 'VietinBank', 'Chi nhánh Hà Đông', 'Hà Nội', '0831464851', '0240159637', NULL, 'Nguyễn Thị Hân', '2020-01-18 00:10:00', 'Phạm Gia Thành', '2021-08-24 17:49:11'),
('4029deb6-568c-284f-8941-c1ec321fe728', 'NV-0129', 'Phạm Văn Chí', '1992-10-25', 2, '469b3ece-744a-45d5-957d-e8c757976496', '008878526704', '2018-01-13', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Tân Phúc, Huyện Nông Cống, Tỉnh Thanh Hóa', '91423772', 'VietinBank', 'Chi nhánh Thăng Long', 'Hà Nội', '0879410351', '0286632116', 'Beasley4@gmail.com', 'Phạm Gia Thành', '2020-01-17 05:30:00', 'Nguyễn Thị Hân', '2020-01-17 05:30:00'),
('405d596c-21be-7e1a-3dc2-579daad24557', 'NV-0176', 'Trịnh Vân Ánh', '2001-08-31', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '003037150845', '2017-01-17', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Thực tập sinh', 'Phường Cổ Nhuế 2, Quận Bắc Từ Liêm, Thành phố Hà Nội', '85342668', 'Á Châu (ACB)', 'Chi nhánh Chương Dương', 'Hà Nội', '0374703472', '0282673915', NULL, 'Nguyễn Thị Hân ', '2020-01-17 13:20:00', 'Phạm Gia Thành', '2020-01-17 13:20:00'),
('417f31fa-5c7b-6b08-6280-7ed9d1ea06ea', 'NV-0189', 'Trần Thùy Tâm', '1995-03-21', 1, '469b3ece-744a-45d5-957d-e8c757976496', '006916074987', '2020-06-05', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Phường Cửa Nam, Quận Hoàn Kiếm, Thành phố Hà Nội', '52681828', 'Agribank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0841356060', '0289359171', 'SamuelBilliot@yahoo.com', 'Nguyễn Thị Hân ', '2020-01-17 15:30:00', 'Phạm Gia Thành', '2020-01-17 15:30:00'),
('41f1acba-3177-4b1c-c4d2-89b22d10517e', 'NV-0171', 'Trần Bảo Thành', '1951-01-02', 1, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '005602689661', '2016-10-28', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Quản lý', 'Xã Ia Phìn, Huyện Chư Prông, Tỉnh Gia Lai', '66733426', 'Vietcom Bank', 'Chi nhánh Thăng Long', 'Hà Nội', '0937438270', '0243432212', NULL, 'Phạm Gia Thành', '2020-01-17 12:30:00', 'Phạm Gia Thành', '2020-01-17 12:30:00'),
('42a13e31-2abb-6171-dc1d-086412a8ea97', 'NV-0169', 'Đặng Ngọc Nga', '1992-12-24', 1, '142cb08f-7c31-21fa-8e90-67245e8b283e', '007528841924', '2020-05-19', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Tứ Hiệp, Huyện Hạ Hoà, Tỉnh Phú Thọ', '13228465', 'BIDV', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0846732691', '0284931895', 'CheryleAshworth861@gmail.com', 'Nguyễn Thị Hân ', '2020-01-17 12:10:00', 'Nguyễn Thị Hân', '2020-01-17 12:10:00'),
('42db9027-5e76-257b-33c2-579daad24557', 'NV-0093', 'Nguyễn Thảo Oanh', '1959-05-22', 1, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '007627938872', '2016-03-06', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Đội Cấn, Quận Ba Đình, Thành phố Hà Nội', '43754995', 'Tiên Phong - TPBank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0862495537', '0244246808', 'Jung648@gmail.com', 'Phạm Gia Thành', '2020-01-16 23:30:00', 'Nguyễn Thị Hân', '2020-01-16 23:30:00'),
('443674f7-78a9-5ffa-4f35-0028ed526dd0', 'NV-0212', 'Nguyễn Thùy Nguyệt', '1989-12-03', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '007376023178', '2021-07-13', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'hường Trung Liệt, Quận Đống Đa, Thành phố Hà Nội', '23146139', 'Á Châu (ACB)', 'Chi nhánh Hà Thành', 'Hà Nội', '0976781388', '0248940213', NULL, 'Nguyễn Thị Hân ', '2020-01-17 19:20:00', 'Phạm Gia Thành', '2020-01-17 19:20:00'),
('45c09477-664f-1904-0f35-60b3ebf808a9', 'NV-0203', 'Phạm Phương Thảo', '1993-05-15', 2, '469b3ece-744a-45d5-957d-e8c757976496', '006768796239', '2017-03-29', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Đắk Pne, Huyện Kon Rẫy, Tỉnh Kon Tum', '63692376', 'Agribank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0903755034', '0281832849', NULL, 'Nguyễn Thị Hân ', '2020-01-17 17:50:00', 'Phạm Gia Thành', '2020-01-17 17:50:00'),
('46325c89-599d-77ef-74f6-423b4e874d0f', 'NV-0167', 'Đoàn Kim Trung', '1968-05-26', 2, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '002804721277', '2018-12-07', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Thị trấn Krông Kmar, Huyện Krông Bông, Tỉnh Đắk Lắk', '83593567', 'Á Châu (ACB)', 'Chi nhánh Chương Dương', 'Hà Nội', '0326060438', '0248785267', NULL, 'Phạm Gia Thành', '2020-01-17 11:50:00', 'Nguyễn Thị Hân', '2020-01-17 11:50:00'),
('46421cb1-7414-1d61-2c80-de64d090a2c2', 'NV-0234', 'Đoàn Khánh Hoàng', '1994-08-01', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '009708113953', '2018-03-15', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'hường Khâm Thiên, Quận Đống Đa, Thành phố Hà Nội', '42598158', 'Kỹ thương - Techcombank', 'Chi nhánh Hà Đông', 'Hà Nội', '0898735456', '0241754944', NULL, 'Nguyễn Thị Hân', '2020-01-17 23:00:00', 'Phạm Gia Thành', '2021-08-24 17:49:30'),
('48147636-7e8f-6939-2580-de64d090a2c2', 'NV-0179', 'Trần Văn Huy', '2001-09-25', 1, '469b3ece-744a-45d5-957d-e8c757976496', '001990281178', '2017-12-02', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Quản lý', 'Xã Chính Nghĩa, Huyện Kim Động, Tỉnh Hưng Yên', '06854661', 'VietinBank', 'Chi nhánh Đông Anh', 'Hà Nội', '0398048519', '0248465267', NULL, 'Nguyễn Thị Hân ', '2020-01-17 13:50:00', 'Phạm Gia Thành', '2020-01-17 13:50:00'),
('4852769b-3986-7c69-2077-d9ebc53aac3d', 'NV-0140', 'Lê Văn Hùng', '1999-05-07', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '004859570263', '2016-09-04', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Phường Phúc Xá, Quận Ba Đình, Thành phố Hà Nội', '76528880', 'Việt Á - VietABank', 'Chi nhánh Hà Thành', 'Hà Nội', '0887743795', '0246404445', NULL, 'Phạm Gia Thành', '2020-01-17 07:20:00', 'Nguyễn Thị Hân', '2020-01-17 07:20:00'),
('4863fe5f-13df-4653-9041-c1ec321fe728', 'NV-0195', 'Trần Thùy Anh', '1951-01-06', 1, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '003126816405', '2016-11-26', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Nghi Thạch, Huyện Nghi Lộc, Tỉnh Nghệ An', '73804979', 'BIDV', NULL, 'Hà Nội', '0978171859', NULL, NULL, 'Phạm Gia Thành', '2020-01-17 16:30:00', 'Phạm Gia Thành', '2020-01-17 16:30:00'),
('4a9854e8-12ac-72ac-2877-d9ebc53aac3d', 'NV-0198', 'Vũ Mai Hiền', '1991-07-09', 1, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '006796440426', '2016-06-11', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Thực tập sinh', 'Thị trấn Châu Hưng, Huyện Vĩnh Lợi, Tỉnh Bạc Liêu', '30374966', 'BIDV', 'Chi nhánh Hà Đông', 'Hà Nội', '0914816355', '0241752838', NULL, 'Phạm Gia Thành', '2020-01-17 17:00:00', 'Phạm Gia Thành', '2020-01-17 17:00:00'),
('4b649055-43d5-2b07-de1d-086412a8ea97', 'NV-0208', 'Trần Ngọc Thảo', '1992-08-14', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '008051276465', '2019-05-23', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Xã Đắk Nên, Huyện Kon Plông, Tỉnh Kon Tum', '04010813', 'Việt Á - VietABank', 'Chi nhánh Thăng Long', 'Hà Nội', '0363014130', '0249440170', NULL, 'Nguyễn Thị Hân ', '2020-01-17 18:40:00', 'Phạm Gia Thành', '2020-01-17 18:40:00'),
('4bf4567b-1505-40db-dd1d-086412a8ea97', 'NV-0181', 'Phan Mai Nguyệt', '2002-10-26', 1, '469b3ece-744a-45d5-957d-e8c757976496', '009727368653', '2016-07-22', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Xã Gio Mai, Huyện Gio Linh, Tỉnh Quảng Trị', '01717059', 'VietinBank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0838631628', '0242970135', NULL, 'Phạm Gia Thành', '2020-01-17 14:10:00', 'Phạm Gia Thành', '2020-01-17 14:10:00'),
('4bf9ecda-2d8e-1724-1d80-de64d090a2c2', 'NV-0080', 'Đỗ Trung Khôi', '1956-02-27', 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '008901083975', '2017-12-29', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Quản lý', 'Phường 19, Quận Bình Thạnh, Thành phố Hồ Chí Minh', '18052726', 'Kỹ thương - Techcombank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0395547964', '0244654771', NULL, 'Nguyễn Thị Hân ', '2020-01-16 21:20:00', 'Phạm Gia Thành', '2020-01-16 21:20:00'),
('4c61c74b-4a9f-769e-0d35-60b3ebf808a9', 'NV-0186', 'Nguyễn Văn Nghĩa', '1991-01-02', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '002874711679', '2021-06-23', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'ường Trần Phú, Thành phố Bắc Giang, Tỉnh Bắc Giang', '84311729', 'BIDV', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0348582264', '0285387529', 'Everett@gmail.com', 'Phạm Gia Thành', '2020-01-17 15:00:00', 'Phạm Gia Thành', '2020-01-17 15:00:00'),
('4c9ebdde-5f9a-58dd-4235-0028ed526dd0', 'NV-0096', 'Lương Văn Chính', '1980-06-13', 2, '469b3ece-744a-45d5-957d-e8c757976496', '003623645110', '2016-01-09', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', '� Tiên Ngoại, Thị Xã Duy Tiên, Tỉnh Hà Nam', '28086444', 'Kỹ thương - Techcombank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0885649057', '0283845887', NULL, 'Phạm Gia Thành', '2020-01-17 00:00:00', 'Nguyễn Thị Hân', '2020-01-17 00:00:00'),
('4d536cce-31bf-335e-bfd2-89b22d10517e', 'NV-0110', 'Nguyễn Minh Chí', '1991-10-20', 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '001489919344', '2017-09-12', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Thực tập sinh', 'Xã Tân Quý Tây, Huyện Bình Chánh, Thành phố Hồ Chí Minh', '70337186', 'BIDV', 'Chi nhánh Chương Dương', 'Hà Nội', '0371889407', '0283521313', NULL, 'Phạm Gia Thành', '2020-01-17 02:20:00', 'Phạm Gia Thành', '2020-01-17 02:20:00'),
('4d6d3d5c-26da-45b3-2977-d9ebc53aac3d', 'NV-0213', 'Phạm Phương Nguyệt', '1957-12-01', 2, '142cb08f-7c31-21fa-8e90-67245e8b283e', '001604879397', '2019-01-02', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Xã Yên Trị, Huyện Yên Thủy, Tỉnh Hoà Bình', '76520342', 'VietinBank', 'Chi nhánh Thăng Long', 'Hà Nội', '0959170340', '0282294058', NULL, 'Nguyễn Thị Hân ', '2020-01-17 19:30:00', 'Phạm Gia Thành', '2020-01-17 19:30:00'),
('4dd0746a-6f49-64fa-1d77-d9ebc53aac3d', 'NV-0113', 'Nguyễn Thị Tâm', NULL, 2, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '000981036202', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', NULL, '16216555', 'BIDV', 'Chi nhánh Thăng Long', 'Hà Nội', NULL, '0287238840', NULL, 'Nguyễn Thị Hân ', '2020-01-17 02:50:00', 'Phạm Gia Thành', '2020-01-17 02:50:00'),
('4e2c885d-5347-35dc-79f6-423b4e874d0f', 'NV-0204', 'Lương Thị Hiền', '1997-11-09', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '006710898651', '2016-10-07', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Trung Thành Đông, Huyện  Vũng Liêm, Tỉnh Vĩnh Long', '53832679', 'VP Bank', NULL, 'Hà Nội', '0917818251', NULL, NULL, 'Nguyễn Thị Hân ', '2020-01-17 18:00:00', 'Nguyễn Thị Hân', '2020-01-17 18:00:00'),
('4eb131b8-234a-632f-4b35-0028ed526dd0', 'NV-0170', 'Phan Trung Chính', NULL, 2, '142cb08f-7c31-21fa-8e90-67245e8b283e', '008856249392', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Quản lý', NULL, '51663530', 'BIDV', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', NULL, '0241090537', NULL, 'Nguyễn Thị Hân ', '2020-01-17 12:20:00', 'Nguyễn Thị Hân', '2020-01-17 12:20:00'),
('4efc95ad-2cc2-3f45-bed2-89b22d10517e', 'NV-0106', 'Lương Ngọc Hiền', '1991-01-06', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '004061266162', '2016-01-08', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', 'Xã Yên Từ, Huyện Yên Mô, Tỉnh Ninh Bình', '54898943', 'Kỹ thương - Techcombank', 'Chi nhánh Hà Thành', 'Hà Nội', '0380009593', '0243161079', NULL, 'Phạm Gia Thành', '2020-01-17 01:40:00', 'Nguyễn Thị Hân', '2020-01-17 01:40:00'),
('4f65f6c1-4525-16e5-4135-0028ed526dd0', 'NV-0092', 'Nguyễn Văn Duy', NULL, 2, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '008867107731', NULL, 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Thực tập sinh', NULL, '48501410', 'Vietcom Bank', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', NULL, '0285161974', NULL, 'Nguyễn Thị Hân ', '2020-01-16 23:20:00', 'Phạm Gia Thành', '2020-01-16 23:20:00'),
('500b6761-1631-4f3a-c0d2-89b22d10517e', 'NV-0115', 'Nguyễn Vân Hoài', '1970-03-26', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '004262891535', '2018-06-11', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Nghĩa Đô, Quận Cầu Giấy, Thành phố Hà Nội', '67181362', 'Việt Á - VietABank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0341927127', '0244027381', 'Riley@gmail.com', 'Phạm Gia Thành', '2020-01-17 03:10:00', 'Phạm Gia Thành', '2020-01-17 03:10:00'),
('50b49b1f-3df8-4b52-db1d-086412a8ea97', 'NV-0155', 'Vũ Vân Uyên', '1984-06-09', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '009097791620', '2021-06-28', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Xã Yên Thái, Huyện Yên Mô, Tỉnh Ninh Bình', '49587567', 'BIDV', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0971831702', '0281317033', NULL, 'Phạm Gia Thành', '2020-01-17 09:50:00', 'Phạm Gia Thành', '2020-01-17 09:50:00'),
('50c07587-55d5-5b36-1b77-d9ebc53aac3d', 'NV-0094', 'Lê Thị Oanh', '1975-03-29', 1, '469b3ece-744a-45d5-957d-e8c757976496', '002942766038', '2018-07-01', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', 'Xã Suối Tọ, Huyện Phù Yên, Tỉnh Sơn La', '62586148', 'VietinBank', 'Chi nhánh Hà Đông', 'Hà Nội', '0906851714', '0245113561', 'AbrahamF@gmail.com', 'Nguyễn Thị Hân ', '2020-01-16 23:40:00', 'Phạm Gia Thành', '2020-01-16 23:40:00'),
('5163ba6d-4e5a-4043-df1d-086412a8ea97', 'NV-0230', 'Trịnh Trung Bắc', '1991-05-18', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '002487210742', '2018-12-25', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Thị trấn Tịnh Biên, Huyện Tịnh Biên, Tỉnh An Giang', '29273789', 'Á Châu (ACB)', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0889291534', '0288282930', NULL, 'Nguyễn Thị Hân ', '2020-01-17 22:20:00', 'Phạm Gia Thành', '2020-01-17 22:20:00'),
('517035f8-43a9-4c59-72f6-423b4e874d0f', 'NV-0141', 'Đặng Minh Khôi', NULL, 1, '142cb08f-7c31-21fa-8e90-67245e8b283e', '003431799571', NULL, 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', NULL, '73110666', 'Agribank', 'Chi nhánh Chương Dương', 'Hà Nội', NULL, '0247697941', NULL, 'Phạm Gia Thành', '2020-01-17 07:30:00', 'Nguyễn Thị Hân', '2020-01-17 07:30:00'),
('51b5ac10-6dea-17ad-2080-de64d090a2c2', 'NV-0114', 'Đường Bảo Chí', '1953-08-02', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '003465704933', '2020-05-11', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', '� Hưng Long, Huyện Yên Lập, Tỉnh Phú Thọ', '58505617', 'BIDV', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', '0359687745', '0280225625', NULL, 'Phạm Gia Thành', '2020-01-17 03:00:00', 'Nguyễn Thị Hân', '2020-01-17 03:00:00'),
('51c6e7d3-53bf-49ae-8a41-c1ec321fe728', 'NV-0134', 'Nguyễn Ngọc Diễm', '1991-02-27', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '001773331966', '2020-08-10', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường 17, Quận Gò Vấp, Thành phố Hồ Chí Minh', '62670179', 'Agribank', 'Chi nhánh Đông Anh', 'Hà Nội', '0959296702', '0288687541', 'Myung_Wolfe@gmail.com', 'Phạm Gia Thành', '2020-01-17 06:20:00', 'Phạm Gia Thành', '2020-01-17 06:20:00'),
('527e293c-2185-6d0a-5580-7ed9d1ea06ea', 'NV-0068', 'Lương Khánh Nam', '1959-11-28', 0, '469b3ece-744a-45d5-957d-e8c757976496', '004365409658', '2019-06-30', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Giám đốc', 'Xã Long Kiến, Huyện Chợ Mới, Tỉnh An Giang', '31043829', 'MBBank', 'Chi nhánh Hà Thành', 'Hà Nội', '0883951309', '0280251052', NULL, 'Phạm Gia Thành', '2020-01-16 19:20:00', 'Nguyễn Thị Hân', '2020-01-16 19:20:00'),
('52a36f9d-42d4-6841-38c2-579daad24557', 'NV-0139', 'Đặng Thùy Hân', '1953-12-23', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '009309707989', '2019-04-24', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'Xã Trung Giang, Huyện Gio Linh, Tỉnh Quảng Trị', '53337239', 'BIDV', NULL, 'Hà Nội', '0373212691', NULL, NULL, 'Nguyễn Thị Hân ', '2020-01-17 07:10:00', 'Phạm Gia Thành', '2020-01-17 07:10:00'),
('535ddd98-1493-7909-1e80-de64d090a2c2', 'NV-0102', 'Vương Thùy Diễm', '2003-12-17', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '005954089877', '2016-06-15', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', '� Minh Côi, Huyện Hạ Hoà, Tỉnh Phú Thọ', '63672217', 'Kỹ thương - Techcombank', 'Chi nhánh Hà Thành', 'Hà Nội', '0381294931', '0243769738', NULL, 'Phạm Gia Thành', '2020-01-17 01:00:00', 'Nguyễn Thị Hân', '2020-01-17 01:00:00'),
('56249d42-1aee-20b3-3fc2-579daad24557', 'NV-0187', 'Trịnh Phương Yến', '1954-07-23', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '001844619281', '2016-01-10', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Mai Dịch, Quận Cầu Giấy, Thành phố Hà Nội', '46854939', 'Agribank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0353646755', '0241693134', NULL, 'Phạm Gia Thành', '2020-01-17 15:10:00', 'Phạm Gia Thành', '2020-01-17 15:10:00'),
('565c3832-2fbc-2ad0-4735-0028ed526dd0', 'NV-0146', 'Triệu Bảo Hùng', NULL, 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '007575828991', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng phòng', NULL, '34640541', 'BIDV', 'Chi nhánh Đông Anh', 'Hà Nội', NULL, '0240241736', NULL, 'Phạm Gia Thành', '2020-01-17 08:20:00', 'Nguyễn Thị Hân', '2020-01-17 08:20:00'),
('5697b103-5179-7ac3-d31d-086412a8ea97', 'NV-0066', 'Ngô Ngọc Trang', '1995-04-08', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '007980143407', '2016-08-07', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Xã Đắk Tờ Re, Huyện Kon Rẫy, Tỉnh Kon Tum', '90033103', 'VP Bank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0815010413', '0240877256', NULL, 'Nguyễn Thị Hân ', '2020-01-16 19:00:00', 'Nguyễn Thị Hân', '2020-01-16 19:00:00'),
('57dc4273-5c51-4aea-4d35-0028ed526dd0', 'NV-0197', 'Hồ Thùy Ngân', '1996-11-29', 2, '469b3ece-744a-45d5-957d-e8c757976496', '001021787309', '2020-06-11', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', 'Xã Đức Hồng, Huyện Trùng Khánh, Tỉnh Cao Bằng', '18714405', 'Sacombank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0892969754', '0289961806', 'orpq265@gmail.com', 'Phạm Gia Thành', '2020-01-17 16:50:00', 'Phạm Gia Thành', '2020-01-17 16:50:00'),
('57e65423-37f0-74b0-71f6-423b4e874d0f', 'NV-0131', 'Nguyễn Thanh Ánh', '2001-07-31', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '001233337022', '2019-11-25', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Quản lý', 'Xã Ngũ Hiệp, Huyện Cai Lậy, Tỉnh Tiền Giang', '47124083', 'Tiên Phong - TPBank', 'Chi nhánh Đông Anh', 'Hà Nội', '0932989750', '0240809540', NULL, 'Phạm Gia Thành', '2020-01-17 05:50:00', 'Phạm Gia Thành', '2020-01-17 05:50:00'),
('58e49fff-2a42-4ce7-1c77-d9ebc53aac3d', 'NV-0104', 'Trần Minh Long', '1969-09-11', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '008094446149', '2016-02-18', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Thực tập sinh', 'ã Tân Lập 2, Huyện Tân Phước, Tỉnh Tiền Giang', '98889082', 'Vietcom Bank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0928368904', '0241688343', NULL, 'Phạm Gia Thành', '2020-01-17 01:20:00', 'Phạm Gia Thành', '2020-01-17 01:20:00'),
('592aba45-4643-52ff-c1d2-89b22d10517e', 'NV-0121', 'Hồ Bảo Tùng', '1959-07-21', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '003565086111', '2019-10-22', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Hưng Điền B, Huyện Tân Hưng, Tỉnh Long An', '80840690', 'Tiên Phong - TPBank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0874678873', '0282554012', NULL, 'Nguyễn Thị Hân ', '2020-01-17 04:10:00', 'Nguyễn Thị Hân', '2020-01-17 04:10:00'),
('59a2f614-253e-1202-6480-7ed9d1ea06ea', 'NV-0211', 'Phạm Thanh Huyền', '1953-03-29', 2, '469b3ece-744a-45d5-957d-e8c757976496', '001069496480', '2018-05-09', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Phường Tân An, Thị Xã Nghĩa Lộ, Tỉnh Yên Bái', '94929200', 'Agribank', 'Chi nhánh Bắc Từ Liêm', 'Hà Nội', '0964628207', '0288286994', NULL, 'Phạm Gia Thành', '2020-01-17 19:10:00', 'Nguyễn Thị Hân', '2020-01-17 19:10:00'),
('5b92dd14-27d6-12d0-0e35-60b3ebf808a9', 'NV-0201', 'Vũ Văn Tuấn', '2003-12-01', 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '002807032761', '2019-03-14', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Qui Hướng, Huyện Mộc Châu, Tỉnh Sơn La', '09294658', 'Agribank', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0968601971', '0240909174', NULL, 'Nguyễn Thị Hân ', '2020-01-17 17:30:00', 'Nguyễn Thị Hân', '2020-01-17 17:30:00'),
('5c762b70-6ca3-4343-2880-de64d090a2c2', 'NV-0206', 'Trần Đức Long', '2001-09-23', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '004322237829', '2017-05-03', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Phường Cống Vị, Quận Ba Đình, Thành phố Hà Nội', '35633602', 'Vietcom Bank', 'Chi nhánh Hà Đông', 'Hà Nội', '0892757944', '0248341313', NULL, 'Phạm Gia Thành', '2020-01-17 18:20:00', 'Nguyễn Thị Hân', '2020-01-17 18:20:00'),
('5dc832b0-169a-1395-37c2-579daad24557', 'NV-0132', 'Lê Anh Tuấn', '1951-01-10', 1, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '000141434201', '2019-08-02', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Quán Thánh, Quận Ba Đình, Thành phố Hà Nội', '69086122', NULL, 'Chi nhánh Chương Dương', NULL, '0925365511', '0241465941', NULL, 'Phạm Gia Thành', '2020-01-17 06:00:00', 'Phạm Gia Thành', '2020-01-17 06:00:00'),
('5eaa6527-768d-3ae7-1977-d9ebc53aac3d', 'NV-0089', 'Ngô Văn Chí', '1988-07-28', 2, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '009614775078', '2016-02-06', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'ã Hát Môn, Huyện Phúc Thọ, Thành phố Hà Nội', '92541320', 'BIDV', 'Chi nhánh Thanh Xuân', 'Hà Nội', '0979943258', '0246402484', NULL, 'Nguyễn Thị Hân ', '2020-01-16 22:50:00', 'Nguyễn Thị Hân', '2020-01-16 22:50:00'),
('5edb2be2-7849-4909-c2d2-89b22d10517e', 'NV-0130', 'Vương Thị Thảo', '1992-06-01', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '009538544459', '2020-08-27', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã An Ninh, Huyện Tiền Hải, Tỉnh Thái Bình', '14149441', 'BIDV', 'Chi nhánh Đông Anh', 'Hà Nội', '0832625858', '0283166317', NULL, 'Nguyễn Thị Hân ', '2020-01-17 05:40:00', 'Phạm Gia Thành', '2020-01-17 05:40:00'),
('5f4b1d0a-247b-7049-4435-0028ed526dd0', 'NV-0122', 'Lê Văn Bình', '1980-02-14', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '001064655735', '2018-06-07', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'ã EaTrol, Huyện Sông Hinh, Tỉnh Phú Yên', '05563387', 'HD Bank', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', '0972009483', '0245927908', NULL, 'Nguyễn Thị Hân ', '2020-01-17 04:20:00', 'Phạm Gia Thành', '2020-01-17 04:20:00'),
('5fd0a411-5945-70f7-4a35-0028ed526dd0', 'NV-0164', 'Nguyễn Mai Phương', '1991-02-08', 1, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '005654500180', '2017-03-15', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'ã Tân Thành, Thành phố Ngã Bảy, Tỉnh Hậu Giang', '46070227', 'Á Châu (ACB)', NULL, 'Hà Nội', '0936382781', NULL, NULL, 'Phạm Gia Thành', '2020-01-17 11:20:00', 'Nguyễn Thị Hân', '2020-01-17 11:20:00'),
('60b57ac2-2e01-384d-2980-de64d090a2c2', 'NV-0214', 'Nguyễn Thanh Mai', '1991-04-01', 2, '142cb08f-7c31-21fa-8e90-67245e8b283e', '004402966983', '2020-11-04', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'hường 07, Quận Bình Thạnh, Thành phố Hồ Chí Minh', '39981542', 'BIDV', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0939762121', '0242485534', NULL, 'Phạm Gia Thành', '2020-01-17 19:40:00', 'Nguyễn Thị Hân', '2020-01-17 19:40:00'),
('60fa924e-77de-55f3-2377-d9ebc53aac3d', 'NV-0165', 'Nguyễn Khánh Long', '1963-04-29', 1, '469b3ece-744a-45d5-957d-e8c757976496', '002554723377', '2017-11-12', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Tân Tây, Huyện Gò Công Đông, Tỉnh Tiền Giang', '10105913', NULL, NULL, NULL, '0338122514', NULL, 'Riggs@gmail.com', 'Phạm Gia Thành', '2020-01-17 11:30:00', 'Phạm Gia Thành', '2020-01-17 11:30:00'),
('613afd47-2fc1-15ed-0735-60b3ebf808a9', 'NV-0108', 'Nguyễn Thanh Chí', '1951-01-12', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '002867791980', '2019-11-27', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Phường Ngọc Hà, Quận Ba Đình, Thành phố Hà Nội', '14380948', 'Agribank', NULL, 'Hà Nội', '0945023909', NULL, NULL, 'Nguyễn Thị Hân ', '2020-01-17 02:00:00', 'Nguyễn Thị Hân', '2020-01-17 02:00:00'),
('619ecbc4-37bc-19ea-6ff6-423b4e874d0f', 'NV-0116', 'Ngô Thùy Trang', '1976-06-07', 2, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '008917328932', '2016-10-21', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', '� Tê Xăng, Huyện Tu Mơ Rông, Tỉnh Kon Tum', '74261646', 'Á Châu (ACB)', 'Chi nhánh Hà Thành', 'Hà Nội', '0972553864', '0245193858', NULL, 'Phạm Gia Thành', '2020-01-17 03:20:00', 'Nguyễn Thị Hân', '2020-01-17 03:20:00'),
('623727c0-4fb7-573d-c3d2-89b22d10517e', 'NV-0162', 'Lê Khánh Duy', NULL, 0, '469b3ece-744a-45d5-957d-e8c757976496', '004247341496', NULL, 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, NULL, '52334738', 'VP Bank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', NULL, '0289570261', NULL, 'Nguyễn Thị Hân ', '2020-01-17 11:00:00', 'Nguyễn Thị Hân', '2020-01-17 11:00:00'),
('6349b25b-78e2-2d06-2780-de64d090a2c2', 'NV-0202', 'Nguyễn Phương Trang', '1951-11-23', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '008338898050', '2016-05-10', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Bảo Đài, Huyện Lục Nam, Tỉnh Bắc Giang', '45098788', 'Đông Á - Dong A Bank', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', '0812095404', '0244403038', NULL, 'Nguyễn Thị Hân ', '2020-01-17 17:40:00', 'Nguyễn Thị Hân', '2020-01-17 17:40:00'),
('6399a2a5-2afd-3384-da1d-086412a8ea97', 'NV-0126', 'Đỗ Minh Chính', '1963-09-01', 2, '142cb08f-7c31-21fa-8e90-67245e8b283e', '000473946687', '2018-09-22', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', 'Phường Thanh Lương, Quận Hai Bà Trưng, Thành phố Hà Nội', '47291069', 'VietinBank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0388096359', '0246804588', NULL, 'Phạm Gia Thành', '2020-01-17 05:00:00', 'Phạm Gia Thành', '2020-01-17 05:00:00'),
('65ecf5c2-5298-156e-d51d-086412a8ea97', 'NV-0085', 'Đoàn Gia Khang', '1970-01-29', 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '009012238487', '2018-04-06', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Thực tập sinh', 'Xã Pú Nhi, Huyện Điện Biên Đông, Tỉnh Điện Biên', '59024554', 'MBBank', 'Chi nhánh Hà Đông', 'Hà Nội', '0859021138', '0249426108', NULL, 'Phạm Gia Thành', '2020-01-16 22:10:00', 'Phạm Gia Thành', '2020-01-16 22:10:00'),
('66ef0b11-1892-1443-1877-d9ebc53aac3d', 'NV-0081', 'Đường Vân Hân', '1996-06-29', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '002540578426', '2021-04-26', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Tam Thành, Huyện Phú Ninh, Tỉnh Quảng Nam', '35712566', 'Agribank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0962323892', '0242818524', NULL, 'Phạm Gia Thành', '2020-01-16 21:30:00', 'Phạm Gia Thành', '2020-01-16 21:30:00'),
('67e3818b-56b7-4eb0-5c80-7ed9d1ea06ea', 'NV-0145', 'Trịnh Mai Ngân', '1999-08-24', 0, '142cb08f-7c31-21fa-8e90-67245e8b283e', '006343856994', '2021-06-04', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Nhuận Phú Tân, Huyện Mỏ Cày Bắc, Tỉnh Bến Tre', '73944010', 'Kỹ thương - Techcombank', 'Chi nhánh Đông Anh', 'Hà Nội', '0936593838', '0240398103', NULL, 'Phạm Gia Thành', '2020-01-17 08:10:00', 'Phạm Gia Thành', '2020-01-17 08:10:00'),
('6a50ecc3-384e-2a54-2177-d9ebc53aac3d', 'NV-0150', 'Triệu Kim Thành', '1951-01-10', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '000589990628', '2019-11-15', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', 'ã Đề Thám, Huyện Tràng Định, Tỉnh Lạng Sơn', '04275501', 'Kỹ thương - Techcombank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0901022812', '0240973281', 'Cheek@gmail.com', 'Phạm Gia Thành', '2020-01-17 09:00:00', 'Phạm Gia Thành', '2020-01-17 09:00:00'),
('6b12b154-39d3-1a5b-2280-de64d090a2c2', 'NV-0147', 'Trần Thảo Oanh', '1988-10-02', 2, '142cb08f-7c31-21fa-8e90-67245e8b283e', '004539206557', '2020-06-20', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Lý Thái Tổ, Quận Hoàn Kiếm, Thành phố Hà Nội', '09032896', 'Á Châu (ACB)', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0995576195', '0249339540', 'Man_Arce122@gmail.com', 'Phạm Gia Thành', '2020-01-17 08:30:00', 'Phạm Gia Thành', '2020-01-17 08:30:00'),
('6b45cb9f-6de5-7a17-2d77-d9ebc53aac3d', 'NV-0245', 'Triệu Thùy Mai', '1992-09-04', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '000342964834', '2018-03-22', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', 'Phường Tràng Tiền, Quận Hoàn Kiếm, Thành phố Hà Nội', '66412350', 'BIDV', 'Chi nhánh Hà Thành', 'Hà Nội', '0323901959', '0241216132', NULL, 'Nguyễn Thị Hân', '2020-01-18 00:50:00', 'Phạm Gia Thành', '2021-09-13 16:58:51'),
('6b76d607-7d60-38a2-5680-7ed9d1ea06ea', 'NV-0083', 'Phạm Gia Long', '1999-11-09', 1, '469b3ece-744a-45d5-957d-e8c757976496', '003803844615', '2019-05-16', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Lê Hồ, Huyện Kim Bảng, Tỉnh Hà Nam', '54055085', 'BIDV', NULL, 'Hà Nội', '0336589308', NULL, 'ElfredaLynn@yahoo.com', 'Phạm Gia Thành', '2020-01-16 21:50:00', 'Phạm Gia Thành', '2020-01-16 21:50:00'),
('6bb2a723-7c18-1df2-0b35-60b3ebf808a9', 'NV-0160', 'Trần Bảo Chí', '1977-01-29', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '004401704254', '2016-06-15', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường Thượng Thanh, Quận Long Biên, Thành phố Hà Nội', '02231124', 'VP Bank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0359206377', '0286377652', NULL, 'Nguyễn Thị Hân ', '2020-01-17 10:40:00', 'Nguyễn Thị Hân', '2020-01-17 10:40:00'),
('6d7def1b-4b7e-52aa-8f41-c1ec321fe728', 'NV-0193', 'Phạm Thị Nga', '1967-07-07', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '005081153654', '2017-09-26', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'Xã Quảng Thái, Huyện Quảng Điền, Tỉnh Thừa Thiên Huế', '66117104', NULL, 'Chi nhánh Chương Dương', NULL, '0849982958', '0288971621', NULL, 'Phạm Gia Thành', '2020-01-17 16:10:00', 'Nguyễn Thị Hân', '2020-01-17 16:10:00'),
('6dcdb6b6-273a-6aaa-8541-c1ec321fe728', 'NV-0078', 'Nguyễn Văn Long', '1999-11-08', 1, '17120d02-6ab5-3e43-18cb-66948daf6128', '009077202087', '2019-10-30', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'hường Tiên Cát, Thành phố Việt Trì, Tỉnh Phú Thọ', '05573993', NULL, 'Chi nhánh Thanh Xuân', NULL, '0898257270', '0244835044', 'Sheets524@yahoo.com', 'Phạm Gia Thành', '2020-01-16 21:00:00', 'Phạm Gia Thành', '2020-01-16 21:00:00'),
('6e3f7a8c-2f78-16a9-36c2-579daad24557', 'NV-0127', 'Nguyễn Vân Trang', '2003-10-25', 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '003361490948', '2020-02-16', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'Xã Ba Nang, Huyện Đa Krông, Tỉnh Quảng Trị', '67892727', 'Tiên Phong - TPBank', NULL, 'Hà Nội', '0355403245', NULL, NULL, 'Nguyễn Thị Hân ', '2020-01-17 05:10:00', 'Phạm Gia Thành', '2020-01-17 05:10:00'),
('6e5bdc72-59a2-5141-7af6-423b4e874d0f', 'NV-0235', 'Nguyễn Văn Nghĩa', '1951-01-22', 0, '469b3ece-744a-45d5-957d-e8c757976496', '009300082387', '2018-08-15', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Thực tập sinh', 'Xã Xuân Thắng, Huyện Thới Lai, Thành phố Cần Thơ', '76427353', 'Agribank', 'Chi nhánh Chương Dương', 'Hà Nội', '0834949179', '0283018814', NULL, 'Nguyễn Thị Hân', '2020-01-17 23:10:00', 'Phạm Gia Thành', '2021-08-24 17:49:34'),
('6f1014db-2ff0-613b-bdd2-89b22d10517e', 'NV-0086', 'Phan Thị Oanh', '1967-06-17', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '004080475342', '2020-04-16', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Giám đốc', 'Xã Xuân Hội, Huyện Nghi Xuân, Tỉnh Hà Tĩnh', '27527568', 'Á Châu (ACB)', 'Chi nhánh Đông Anh', 'Hà Nội', '0373691011', '0289880474', NULL, 'Nguyễn Thị Hân ', '2020-01-16 22:20:00', 'Nguyễn Thị Hân', '2020-01-16 22:20:00'),
('70aead00-2db5-77f7-2277-d9ebc53aac3d', 'NV-0152', 'Vương Khánh Tuấn', '1992-06-30', 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '005127695343', '2016-01-09', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Giám đốc', 'Xã Yên Lương, Huyện Ý Yên, Tỉnh Nam Định', '91994280', 'Kỹ thương - Techcombank', 'Chi nhánh Điện Biên Phủ', 'Hà Nội', '0340380796', '0289464589', NULL, 'Nguyễn Thị Hân ', '2020-01-17 09:20:00', 'Nguyễn Thị Hân', '2020-01-17 09:20:00'),
('721b7460-7378-2203-0435-60b3ebf808a9', 'NV-0076', 'Lê Ngọc Hiền', '1966-03-18', 1, '469b3ece-744a-45d5-957d-e8c757976496', '007621355666', '2021-03-12', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', NULL, 'Xã Tân Hà, Huyện Hàm Tân, Tỉnh Bình Thuận', '42193733', 'HD Bank', NULL, 'Hà Nội', '0375092752', NULL, NULL, 'Nguyễn Thị Hân ', '2020-01-16 20:40:00', 'Phạm Gia Thành', '2020-01-16 20:40:00'),
('75ec2fe2-5965-48e6-9141-c1ec321fe728', 'NV-0199', 'Phạm Phương Anh', '1952-11-20', 2, '469b3ece-744a-45d5-957d-e8c757976496', '001876608900', '2019-10-20', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'Xã Pù Nhi, Huyện Mường Lát, Tỉnh Thanh Hóa', '98364008', 'BIDV', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0388694814', '0246271391', NULL, 'Phạm Gia Thành', '2020-01-17 17:10:00', 'Nguyễn Thị Hân', '2020-01-17 17:10:00'),
('762cf9e5-356b-56d7-5f80-7ed9d1ea06ea', 'NV-0163', 'Đường Thị  Hân', '1988-11-10', 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '004208940213', '2018-09-27', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'ã Bưng Riềng, Huyện Xuyên Mộc, Tỉnh Bà Rịa - Vũng Tàu', '06987851', 'Sacombank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0947333238', '0243542873', NULL, 'Phạm Gia Thành', '2020-01-17 11:10:00', 'Phạm Gia Thành', '2020-01-17 11:10:00'),
('76b3b772-27f3-37bf-75f6-423b4e874d0f', 'NV-0183', 'Nguyễn Văn Duy', '2000-03-28', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '006491898868', '2018-08-08', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Đức Lợi, Huyện Mộ Đức, Tỉnh Quảng Ngãi', '26744498', 'HD Bank', 'Chi nhánh Chương Dương', 'Hà Nội', '0839723079', '0246933708', NULL, 'Phạm Gia Thành', '2020-01-17 14:30:00', 'Nguyễn Thị Hân', '2020-01-17 14:30:00'),
('76cc3313-3932-7e97-4635-0028ed526dd0', 'NV-0142', 'Nguyễn Kim Khang', NULL, 0, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '008407334287', NULL, 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Giám đốc', NULL, '33348007', 'Vietcom Bank', 'Chi nhánh Hà Thành', 'Hà Nội', NULL, '0246667405', NULL, 'Nguyễn Thị Hân ', '2020-01-17 07:40:00', 'Nguyễn Thị Hân', '2020-01-17 07:40:00'),
('77d03350-6ba4-226c-77f6-423b4e874d0f', 'NV-0194', 'Bùi Gia Tùng', '2001-06-23', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '001455707545', '2016-01-09', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Đông Hòa, Huyện An Minh, Tỉnh Kiên Giang', '35284701', 'VietinBank', 'Chi nhánh Đông Anh', 'Hà Nội', '0949813897', '0246582905', NULL, 'Phạm Gia Thành', '2020-01-17 16:20:00', 'Nguyễn Thị Hân', '2020-01-17 16:20:00'),
('78b1d514-338c-3cdc-8641-c1ec321fe728', 'NV-0099', 'Lê Văn Bảo', '1995-08-03', 2, '17120d02-6ab5-3e43-18cb-66948daf6128', '000922109721', '2016-05-20', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Thị trấn Tĩnh Túc, Huyện Nguyên Bình, Tỉnh Cao Bằng', '73134011', 'Tiên Phong - TPBank', 'Chi nhánh Hoàn Kiếm', 'Hà Nội', '0961421329', '0243600691', NULL, 'Nguyễn Thị Hân ', '2020-01-17 00:30:00', 'Phạm Gia Thành', '2020-01-17 00:30:00'),
('7976650d-4e86-2615-8c41-c1ec321fe728', 'NV-0154', 'Phạm Văn Hoàng', '1993-04-02', 2, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '006175283800', '2018-09-25', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Xã Lê Lợi, Huyện Thường Tín, Thành phố Hà Nội', '11243124', 'Vietcom Bank', 'Chi nhánh Thăng Long', 'Hà Nội', '0916128286', '0241959030', NULL, 'Phạm Gia Thành', '2020-01-17 09:40:00', 'Nguyễn Thị Hân', '2020-01-17 09:40:00'),
('79806d6f-4830-6311-2577-d9ebc53aac3d', 'NV-0177', 'Nguyễn Mai Nguyệt', '1951-01-08', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '006485124685', '2017-10-22', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Thị trấn Tam Sơn, Huyện Quản Bạ, Tỉnh Hà Giang', '32151825', 'Agribank', 'Chi nhánh Đông Anh', 'Hà Nội', '0950083875', '0285758836', NULL, 'Nguyễn Thị Hân ', '2020-01-17 13:30:00', 'Phạm Gia Thành', '2020-01-17 13:30:00'),
('79dadd0d-69fa-5e30-35c2-579daad24557', 'NV-0111', 'Nguyễn Thị Uyên', '1951-03-30', 2, '142cb08f-7c31-21fa-8e90-67245e8b283e', '006875937905', '2016-12-25', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', NULL, 'Xã Trung Sơn, Huyện Đô Lương, Tỉnh Nghệ An', '20372919', 'BIDV', NULL, 'Hà Nội', '0914453049', NULL, 'CleoBurrell@gmail.com', 'Phạm Gia Thành', '2020-01-17 02:30:00', 'Nguyễn Thị Hân', '2020-01-17 02:30:00'),
('7a1114ad-76c4-3734-1f77-d9ebc53aac3d', 'NV-0137', 'Triệu Minh Bình', '1991-01-02', 2, '4e272fc4-7875-78d6-7d32-6a1673ffca7c', '003780204170', '2020-02-23', 'Cục Cảnh sát Quản lý hành chính về trật tự xã hội', 'Nhân viên', 'Xã Yên Thịnh, Huyện Yên Định, Tỉnh Thanh Hóa', '40463855', 'Tiên Phong - TPBank', 'Chi nhánh Nam Từ Liêm', 'Hà Nội', '0963390661', '0241171227', NULL, 'Nguyễn Thị Hân ', '2020-01-17 06:50:00', 'Nguyễn Thị Hân', '2020-01-17 06:50:00'),
('7a301ea4-331e-73f6-1a77-d9ebc53aac3d', 'NV-0091', 'Phan Khánh Bảo', '1997-02-16', 0, '17120d02-6ab5-3e43-18cb-66948daf6128', '002405056668', '2020-09-16', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Trưởng nhóm', 'Xã Thục Luyện, Huyện Thanh Sơn, Tỉnh Phú Thọ', '88867766', 'VP Bank', 'Chi nhánh Đông Anh', 'Hà Nội', '0845253407', '0282665649', NULL, 'Nguyễn Thị Hân ', '2020-01-16 23:10:00', 'Phạm Gia Thành', '2020-01-16 23:10:00'),
('7c86746a-4284-356e-e11d-086412a8ea97', 'NV-0248', 'Đoàn Minh Long', '1993-06-07', 0, '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', '001595278019', '2018-05-17', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Nhân viên', 'Phường 1, Thành phố Tuy Hoà, Tỉnh Phú Yên', '85213252', 'Đông Á - Dong A Bank', 'Chi nhánh Hai Bà Trưng', 'Hà Nội', '0341155212', '0240277457', '', 'Nguyễn Thị Hân', '2020-01-18 01:20:00', 'Nguyễn Thị Hân', '2021-09-12 09:58:55'),
('7f1b6c7c-2b74-3ebb-31c2-579daad24557', 'NV-0084', 'Nguyễn Văn Khôi', '1991-03-12', 0, '469b3ece-744a-45d5-957d-e8c757976496', '005973182044', '2019-02-19', 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư', 'Giám đốc', 'Xã Thuận Đức, Thành Phố Đồng Hới, Tỉnh Quảng Bình', '46413788', 'HD Bank', 'Chi nhánh Hà Thành', 'Hà Nội', '0342532196', '0288004627', NULL, 'Phạm Gia Thành', '2020-01-16 22:00:00', 'Nguyễn Thị Hân', '2020-01-16 22:00:00');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;